### ISSUE TITLE
Bare repository - tree/master not found.

### ISSUE THREAD

**Issue by akjoshi** [klaussilveira/gitlist#10]
Hi, 

In the config.ini, I used the bare repository folder. Should this not work?

I get the list of git folders but when I click on them, I get error:
ex: http://localhost/gitlist/compression.git/tree/master/
The requested URL /gitlist/compression.git/tree/master/ was not found on this server.

**Comment by ooichman** [comment]
all I did was to make sure the "AllowOverRide" at the /var/www/html directory was set to All and not to None ... that is it !

**Comment by xoneill007** [comment]
@chipit24: Worked for me as well FreBSD 11.x, Apache 2.4 - thanks!
