### ISSUE TITLE
Wrong timezone for authored date in commit view

### ISSUE THREAD

**Issue by pschirch** [klaussilveira/gitlist#140]
Hi,

Gitlist shows me the wrong authored datetime in commit view.

<table>
  <tr>
    <th>DateTime</th><th>Value</th>
  </tr>
  <tr>
    <td>System</td><td>15/08/2012 23:14:44</td>
  </tr>
  <tr>
    <td>Git log message</td><td>Wed Aug 15 23:14:44 2012 +0200</td>
  </tr>
  <tr>
    <td>Gitlist</td><td>15/08/2012 21:14:44</td>
  </tr>
</table>

PHP timezone configuration in `php.ini`  already set to: `date.timezone = "Europe/Berlin"`

Exists a configuration parameter for Gitlitsts `config.ini` or should Gitlist detect this automatically?

**Comment by mroesler** [comment]
Has the proposed change been reverted? It seems to be broken in 0.4.0 (gitlist)
