### ISSUE TITLE
"vendor" folder not found

### ISSUE THREAD

**Issue by ghost** [klaussilveira/gitlist#142]
I found this error on startup(before install/config):

Warning: require(vendor/autoload.php) [function.require]: failed to open stream: No such file or directory in C:\WWW\index\1\index.php on line 8

Fatal error: require() [function.require]: Failed opening required 'vendor/autoload.php' (include_path='.;C:\php\pear') in C:\WWW\index\1\index.php on line 8

**Comment by jdros** [comment]
Although this is pretty old, it is still not clear. Spent a bit of time with it as well :-(.
Had to install `php-xml` for DOM Extention and php composer. And obviously update and install gitlist dependencies afterwards.
