### ISSUE TITLE
Continuous: Please, edit the config file and provide your repositories directory

### ISSUE THREAD

**Issue by 1beb** [klaussilveira/gitlist#217]
I have a problem. I've followed the installation directions here: http://gofedora.com/insanely-awesome-web-interface-git-repos/ but I continually receive this message: `Please, edit the config file and provide your repositories directory.`

Currently, I'm pointing `config.ini` to `/home/user/dev/repos/` where I've copied a number of bare repositories with the following command 

``` sh
git clone --bare my_project /home/user/dev/repos/my_project.git
```

I'm using Ubuntu 12.04, the 000-default site profile just so I can have a local browser. I updated the file to have `AllowOverride All`, also after reading through other issues I added some elements to suit my usage case of http://localhost/gitlist below is my site file: 

``` text
<VirtualHost *:80>
        ServerAdmin webmaster@localhost

   DocumentRoot /var/www/
    <Directory />
        Options FollowSymLinks
        AllowOverride All
    </Directory>

    <Directory /var/www/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
        # This directive allows us to have apache2's default start page
                # in /apache2-default/, but still have / go to the right place
                #RedirectMatch ^/$ /apache2-default/
    </Directory>

# From another issue I thought could be related
Alias /gitlist /var/www/gitlist/
<Directory /var/www/gitlist>
AllowOverride All
</Directory>

        ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin">
                AllowOverride None
                Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
                Order allow,deny
                Allow from all
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn
```

Is there anything that you can see from my configuration that I could change to resolve this error?

**Comment by howpdm** [comment]
I had the same issue, I just added write/execute permissions to the folder containing my repos:

[root@E3ET0101 home]# ls -l
drwxr--r--. 20 git            git       4096 Apr  1 15:26 git

[root@E3ET0101 home]# chmod o+rx git

After this it worked fine.
