### ISSUE TITLE
Allow to use the gitweb compatible projects.list file

### ISSUE THREAD

**Issue by ddebernardy** [klaussilveira/gitlist#313]
While playing around with gitlist, it didn't seem possible to configure it in such a way that the public projects.list file generated by gitolite, which would normally be used by gitweb, gets used. Instead, it grabs all repos in the repositories folder, and proceeds to make everything public. Did I miss something? If not, would it be a valid feature request?

**Comment by ycollet** [comment]
+1 for this one.
This is still a really good idea

**Comment by michael-lazar** [comment]
This feature was added in GitList 0.6.0, but it doesn't appear to be documented anywhere. You can set up your config like this and it will only display the repos in your projects.list file. Works great with gitolite!

```
[git]
client = '/usr/bin/git' ; Your git executable path
default_branch = 'master' ; Default branch when HEAD is detached
project_list = '/home/git/projects.list'
repositories[] = '/home/git/repositories/' ; Path to your repositories
                                           ; If you wish to add more repositories, just add a new line
```

https://github.com/klaussilveira/gitlist/pull/564
