### ISSUE TITLE
Caching strategy

### ISSUE THREAD

**Issue by klaussilveira** [klaussilveira/gitlist#327]
GitList makes heavy use of Git's CLI tool in order to gather lot's of data from the repositories. If you are running GitList with large repositories, with gigabytes of history, things can get ugly. 

We need to implement the following caching solutions: 
- Repository list caching: prevents GitList from scanning the filesystem on every request
- Repository cache: prevents GitList from scanning the tree and commit log
- Stats cache

The stats cache can be a full-page cache without any strategy whatsoever, which can be accomplished by the end-user with Varnish or something similar. The first two, however, are important to make sure GitList scales well.

**Comment by garygreen** [comment]
I'm having a stab at this right now, I hope to make a PR soon. Personally I think the main repositories list should be cached and that's it. Caching any data inside a specific repository is probably going too far and not really required, as once your inside a repository it seems pretty snappy anyway?

**Comment by alehaa** [comment]
I think we could use the [silex-cache-service-provider](https://github.com/moust/silex-cache-service-provider) by @moust for optional caching, but there are other providers, too. However, I think this one looks pretty simple and thus follows the ideals of GitList.
