### ISSUE TITLE
New repository list layout

### ISSUE THREAD

**Issue by klaussilveira** [klaussilveira/gitlist#328]
The current repository list layout needs a facelift in order to support: 
- Nested repositories (see https://github.com/klaussilveira/gitlist/issues/311)
- Large amount of repositories (e.g.: https://github.com/klaussilveira/gitlist/pull/317)
- cloneurl (see https://github.com/klaussilveira/gitlist/issues/205)

**Comment by andymnc** [comment]
Hi,
was this ever solved? We really need the feature about showing clone link.
