### ISSUE TITLE
Gitlist can't access repository location. (Using gitolite)

### ISSUE THREAD

**Issue by abread** [klaussilveira/gitlist#345]
I installed gitolite in /home/git (Repos in /home/git/repositories). Then I've installed GitList in the same server on a (Plesk-made)VirtualHost. Before this installation I've managed to get GitList working with similar conditions.

First I received an error saying to add repositories in config.ini, traced the error and found out that php in the cli considered the folder a directory but on the website the exact opposite.
So I tried to exclude files and symlinks instead of including only directories on GitList code (!is_dir() to is_file() || is_link()) and I got a 500 error. In the apache error log:
PHP Fatal error: Uncaught exception 'UnexpectedValueException' with message 'DirectoryIterator::__construct(/home/git/repositories): failed to open dir: Permission denied' (stacktrace_here)
so I tried chmod 755 the directory, then 777. But nothing works.

Any idea of what's going on?

**Comment by mastash3ff** [comment]
I didn't see a posted solution, so here is mine.  I found this page http://www.sitepoint.com/installing-gitlist-for-local-repos/ helpful for resolving this issue.  Specifically the section, "Help! Page Not Found!"

**Comment by afranke** [comment]
> you have to continuously chmod

That's what the UMASK part of the explanation above is for.
