### ISSUE TITLE
Allow config setting to disable downloading of zip/tarballs

### ISSUE THREAD

**Issue by mewejo** [klaussilveira/gitlist#348]
Add a config to prevent certain branches from being downloaded as a ZIP/tarball.

So we could have a stable branch which is downloadable, but other branches like a development one/master are not.

That'd be awesome! :)

**Comment by ArcaneEngineer** [comment]
Submodules are not included in zip archives and thus repos that rely on these may lead new users of Library X to believe that the repo is broken. The solution would be to allow per-repo disabling of this button.

**Comment by Sajaki** [comment]
👍  
must have feature, this would avoid so many deployment issues !

**Comment by howpdm** [comment]
Was there any progress on this? If not, could anyone suggest which source file to edit?

**Comment by stdbull** [comment]
I'm interested too... I have tried the syntax above in some different places in the config file, but no no avail.

**Comment by klaussilveira** [comment]
Hey guys! gitlist is under maintenance mode and not many features are being added. However, that doesn't mean that if someone does this and send a PR it won't be merged. Nothing wrong with smaller features like this.

**Comment by andrewhamili** [comment]
> Per-repository or global? Like:
> 
> Per repository:
> 
> ```
> [archiving]
> repo-name = ["1.0", "1.1"] // Will only show the archive option to 1.0, 1.1 branches/tags on repo-name
> ```
> 
> Global:
> 
> ```
> archive = ["master", "dev"] // Will only show the archive option to master, dev branches/tags on all repos
> ```

Hi. Is this already available for version 1.0.2?
