### ISSUE TITLE
Only top README.md is used

### ISSUE THREAD

**Issue by thesamet** [klaussilveira/gitlist#364]
In my repository I have `README.md` in some subdirectories as well as in the repository root.

It seems that the root's `README.md` is displayed on all project pages. The behavior that I'd like to achieve is:
1. If there is a `README.md` in the current directory, display it beneath the file list.
2. If there is no `README.md` in the current directory - do not display anything.

**Comment by DrChr** [comment]
Should this still be open?
I'm just testing gitlist and it seems that a local README is shown when browsing to a subfolder.

**Comment by philipabbey** [comment]
I'm using GitList 0.4.0, and I'm getting the reported behaviour. I too would appreciate a fix as per @thesamet 's description.

**Comment by alehaa** [comment]
@philipabbey As you can see in the linked PR, this feature has been merged some time ago. Please upgrade to `>= v0.6`.

**Comment by philipabbey** [comment]
Slightly confusing... I downloaded and installed the latest *stable release* (0.5.0) within the last week, and its reported as 0.4.0 in the web page. Do you need to update the link to the latest stable release?

Thanks.

**Comment by alehaa** [comment]
Yes we do, sorry. (see #755).
