### ISSUE TITLE
Commit List: Pagination goes one page too far

### ISSUE THREAD

**Issue by lukx** [klaussilveira/gitlist#376]
When on the last page of the commit list (e.g.when looking at the GitList repo itself, currently Page 28: `/gitlist/commits/master?page=28`), one still gets the "Older" button, although we are already on the last page. 

This seems to be because `pager.last` is 29 (= 1-Indexed) while pager.current is 0-Indexed?

**Comment by alehaa** [comment]
In the current `master`, the *Older* button becomes hidden, if there are no more commits.
