### ISSUE TITLE
git repositories - how do I make it accessible to gitlist and my dev team

### ISSUE THREAD

**Issue by sridharpandu** [klaussilveira/gitlist#385]
I migrated my repositories from a Ubuntu server to Centos 6 server (after a few hiccups which I posted on this forum). My repositories are located in `/home/mydir/gitrepos`

I installed nginx and gitlist and had to change the ownership and group of the `/home/mydir/gitrepos` to *nginx:nginx* so that gitlist could read and render the repository list on my browser

Today I tried pushing my changes from my laptop to the remote repository and got a fatal: 
```
/home/mydir/gitrepos/myproject.git does not appear to be a valid repository fatal: The remote end hung up unexpectedly
```

I tried pulling and ended up with the same message. I suspected that the repositories were not being read. So changed the ownership of the gitrepos directory and am able to clone, push etc but then gitlist doesn't display the repository list.

Is there a way to set the permissions in such a way that I am able to achieve the following:
* GitList should be able to display the repository list page
* user1, user2 and other members of the devs group are able to clone, push and pull using ssh (e.g `git clone ssh://user1@myip:9999/home/mydir/gitrepos/myproject.git`)

To avoid my devs from pushing stale code to test and production servers I have asked them to clone the repositories onto the target servers. All devs login into production servers using their respective userid's using ssh and the public/private key pair. But are unable to clone from the git repository because there is no private key on the target server. If I generate a new pair of keys then I risk wiping out the existing public keys and locking out my devs. Is there a way out to achieve all of these.

Thanks in Advance

**Comment by alehaa** [comment]
@sridharpandu I'm not sure if this is still actual, but in general this shouldn't be a problem.

The repositories shouldn't be owned by *nginx:nginx* but a dedicated *git*  user. Additional software like Gitolite will then manage the shell access for all developers via the *git* user account, so all developers can access the repository via `git clone git@example.org:myproject.git`. You need to add nginx to the *git*  group, so it is able to read the contents of the repositories.
