### ISSUE TITLE
Errors with filenames having backticks (i.e. backquotes)

### ISSUE THREAD

**Issue by mcgwiz** [klaussilveira/gitlist#395]
In many circles, it is conventional to use backticks in names of C# files containing generic classes. Accessing a file with a backtick in the name causes the following error to be displayed:

> Oops! sh: 1: Syntax error: EOF in backquote substitution

Accessing a file with two backticks in the name, such as ```Source/filename`enclosed`.txt``` yields:

> Oops! sh: 1: enclosed: not found fatal: Path 'Source/filename.txt' does not exist in 'master'

**Comment by hannob** [comment]
Just a note if others find this: This looks very concerning, but looks like it's been fixed, I can't reproduce this in the current version.
