### ISSUE TITLE
Suggestion for improvement of cache folder

### ISSUE THREAD

**Issue by assarbad** [klaussilveira/gitlist#400]
Hi,

tried Gitlist the first time today and the only "annoyance" I came across was a hardcoded `cache` directory path.

What do you think about the following, which should ensure that old configuration files won't break:
1. change the INI value from boolean to boolean _or_ string (that is: `true`, `false` or the directory path)
2. implement logic so that the path is used according to the config

If you feel this is viable, I'd be willing to implement it and send a pull request. Any comments would be welcome.

Side-note: unless `app.cache` is meant to be the defining factor for caching, the code that checks whether the `cache` directory is writable should be  _after_ the reading of `config.ini`.

// Oliver

**Comment by garygreen** [comment]
Why is the cache path inside the app a problem? It's gitignored and if you really want to change the path then why not symlink?

**Comment by assarbad** [comment]
@garygreen I'm not sure what you're trying to say. I didn't insinuate that Git (and therefore `.gitignore`) was or should be involved.

It's a natural thing to want to separate program from program data and it has been proven as a sensible solution many times over. One good reason is backups. You don't want a cache to clutter your backups and you don't want every web application to store their cache inside the webroot either - well, if you're an admin that is.

Symlinks do not always work, only bind-mounts provide the required transparency. If I had to do a backup, what would I do? Exclude all symlinks? What if the author then decides to put a symlink into the source itself? Essentially the current scheme complicates things for any use case on a real server.

It's fine on a developer machine, but on a server you want to be able to assign ACLs and permissions in a certain way and make sure that setting them recursively for a web application opens up an attack surface.

**Comment by garygreen** [comment]
@assarbad Fair enough. Not much is actually being cached at the moment (actually, I think nothing is since it's been removed?). It wouldn't be too difficult adding a config option for the cache directory anyway, maybe a PR?

**Comment by assarbad** [comment]
@garygreen what's PR in this context?

**Comment by garygreen** [comment]
Pull request. I think the main dev has been inactive for some time so unlikely it'll get implemented, in any case a PR would be a good start. It would enable yourself and others to see the implementation and at least maintain their own fork and cherry pick it.

**Comment by assarbad** [comment]
@garygreen of course, didn't think of pull request.

Fair point, I'll see when I can squeeze in some time regarding this. Thanks.
