### ISSUE TITLE
Filename special characters issues

### ISSUE THREAD

**Issue by DamnDam** [klaussilveira/gitlist#419]
I'm having issues with special characters in UTF8 filenames.

For example, on tree, the file `Générateur.txt` will display
`"G\303\251n\303\251rateur.txt"`

Furthermore, the link points to 
`http://mygitserveur/myrepo.git/blob/master/%22G%5C303%5C251n%5C303%5C251rateur.txt%22`

When the correct URL should be:
`http://mygitserveur/myrepo.git/blob/master/G%C3%A9n%C3%A9rateur.txt`

Thanks for your help.

**Comment by alehaa** [comment]
Seems @rinu has another approach in #645.
