### ISSUE TITLE
Gitlist version not updated in footer

### ISSUE THREAD

**Issue by feeloow** [klaussilveira/gitlist#480]
Downloaded and installed latest 5.0 stable from http://gitlist.org/
Vesion shown in footer is still 0.4.0 (wish is vulnerable).
CF :  https://github.com/klaussilveira/gitlist/blame/master/themes/default/twig/footer.twig#L2

**Comment by afranke** [comment]
This has been fixed in master.

**Comment by alehaa** [comment]
As there's already a [v6.0.0 release](https://github.com/klaussilveira/gitlist/releases/tag/0.6.0) I don't think there will be a new tarball for `v5.0.0`. However, this issue has been fixed in e70cb0f as described in #654.
