### ISSUE TITLE
Cache control?

### ISSUE THREAD

**Issue by donnekgit** [klaussilveira/gitlist#484]
Gitlist is a very attractive frontend, but one issue has arisen.  I have a series of smallish Git repos which come to 750Mb.  But since installing Gitlist in mid-June, I now have a series of files in cache/archives which come to 15Gb!  Worse, many files seem to be cached in both tar and zip formats, doubling the amount of space used:
```
-rw-r--r-- 1 www-data www-data 78551040 Jul  4 07:52 7c3e1040744b96f24c931c8cfc3c40bca66673.tar
-rw-r--r-- 1 www-data www-data 43556372 Jul  4 07:50 7c3e1040744b96f24c931c8cfc3c40bca66673.zip
```
This seems to be the same issue as: #350, but it's unclear from the answers there what, if anything, was done, or should be done, to address this.

1. Is it safe to delete these cache/archives files?
2. Is there any way to control the creation of these cache/archives files?  I suppose the simplest thing would be to turn off caching, but if that will lead to problems, is there any way to tell Gitlist to remove the previous archive before it creates another one (à la logrotate)?

It seems to me that creation of these insanely large files is a pretty serious problem for Gitlist.

**Comment by Smarre** [comment]
+1 for getting this fixed...

**Comment by eleazan** [comment]
These file should be created here:
https://github.com/klaussilveira/gitlist/blob/e535ddc4c5e60a8d5f1290a5e73deaf47edf90d2/src/GitList/Controller/TreeController.php#L76

So, it's when you go to {repo}/{format}ball/{branch}. If file not exists, the system should create one ;).

**Comment by andytruong** [comment]
Ahhhhhh! My server only has 20GB, gitlist only more than 10GB ):
