### ISSUE TITLE
CentOS 7 installation problem

### ISSUE THREAD

**Issue by smartseal** [klaussilveira/gitlist#489]
After I git clone gitlist to /var/www/html/gitlist and I ran ant to build gitlist.
I copied the config.ini and edit the repositories to /home/git/repositories

During build, I got an test failure
```
[exec] /var/www/html/gitlist/tests/InterfaceTest.php:258
[exec]  
[exec] FAILURES!  
[exec] Tests: 6, Assertions: 53, Failures: 1.
```

I restart httpd 2.4 even I got this failure, and there is a error:
```
Please, edit the config file and provide your repositories directory
```

Currently, I have no director to solve the problem:-)

**Comment by richjenks** [comment]
I'm having the same issue with the latest stable build from http://gitlist.org/, as are https://github.com/klaussilveira/gitlist/issues/612 and https://github.com/klaussilveira/gitlist/issues/491
