### ISSUE TITLE
Default view for repository

### ISSUE THREAD

**Issue by Grinnz** [klaussilveira/gitlist#492]
Please add a configuration option to change the default view to "Commits" instead of "Files". When first opening a repository, changing branches/tags or clicking the repository name while looking at commits, it brings you back to the tree view.

**Comment by garygreen** [comment]
Nope, I vote to leave it as the files view, just like github does.

**Comment by Norkep** [comment]
Please, stop mail !

**Comment by garygreen** [comment]
@Norkep if you want to stop emails relating to a thread you need to go on Github and unsubscribe. Making such a reply by your email isn't helpful.

**Comment by Grinnz** [comment]
At the least, when on the commits tab, changing to a different branch or tag should remain on the commits tab. (ditto for Stats tab)
