### ISSUE TITLE
[Req] Password-protected Repos

### ISSUE THREAD

**Issue by Nushio** [klaussilveira/gitlist#5]
Hey! I just learned about Gitlist, it was incredibly easy to set up and I wanted to use at $DayJob, however the Boss is obviously concerned about the security, so I was wondering if some sort of user/password setup was in the roadmap for this project. This wouldn't be used to protect the actual git repo, just to display the stuff via web. 

Thanks.

**Comment by escoreal** [comment]
Hello,

I would like to see some authorization functions in GitList, too. For example like in WebSVN. There you can use Apache authentication and use the "AuthzSVNAccessFile" to specify the repository permissions.

esco

**Comment by mgraupe** [comment]
Hi, 

I love gitlist and I would like to support the request to build in some sort of password protection. 

Thanks,
Michael

**Comment by acrolink** [comment]
Great work :-) I agree with most people here, this utility needs to provide some in-built access control.

**Comment by sharkydog** [comment]
Just want to share my solution on the issue using http auth in nginx.
Based on nginx config from [INSTALL.md](https://github.com/klaussilveira/gitlist/blob/master/INSTALL.md#nginx-serverconf), this asks for password when listing repositories and for every repo in the root directory, but not for repos in the pub direcotory like /pub/somerepo.git.

`
server {
	server_name some.domain.com;
	
	root /some/document/root/path;
	index index.php;
	
	location = /robots.txt {
		allow all;
		log_not_found off;
		access_log off;
	}
	
	location ~* ^/index.php.*$ {
		include custom-common/php5;
	}
	
	location ~* ^/pub {
		try_files $uri @gitlist;
	}
	
	location ~* ^/(.+\.git/)?$ {
		auth_basic "Protected";
		auth_basic_user_file /some/htpasswd/path;
		allow 192.168.1.0/24; # next three lines to allow direct access from LAN
		deny all;
		satisfy any;
		
		try_files $uri @gitlist;
	}
	
	location / {
		try_files $uri @gitlist;
	}
	
	location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
		add_header Vary "Accept-Encoding";
		expires max;
		try_files $uri @gitlist;
		tcp_nodelay off;
		tcp_nopush on;
	}
	
	location ~* \.(git|svn|patch|htaccess|log|route|plist|inc|json|pl|po|sh|ini|sample|kdev4)$ {
		deny all;
	}
	
	location @gitlist {
		rewrite ^/.*$ /index.php;
	}
}
`

**Comment by dvbava** [comment]
I agree here that it needs basic access control feature in-build. gitlist has expose many companies source code on internet without company/admin actually knowing it.
 ex. 
1.  http://git.blue-mind.net/     
2. http://git.maxx.matrixdev.net/matrix.git/maxx17.2/
 You can see their entire source code..

Want to find more? just google gitlist and scroll through next few pages in result.

Its obvious that everyone is not well experienced in security aspects at least.

**Comment by alehaa** [comment]
Maybe this could be solved with "plugins" (see #739), so one could add access protection easily.

However, this should be an optional plugin. The default GitList installation shouldn't be bloated.

**Comment by dvbava** [comment]
think so, and the download as ZIP/tar makes it worse on internet..     You can own anyone code literally.

**Comment by DannyvdSluijs** [comment]
One could reason that we should disallow google bot and others to avoid being indexed by search engines. This could be done with a small robots.txt.

**Comment by klaussilveira** [comment]
How is that a responsibility of GitList? If you want to restrict access, you do it yourself, based on your own needs. Same for restricting bots. Some people might think that robots.txt are enough, others will probably need Varnish or an web application firewall.

@dvbava You are hosting a repository viewer on your public Apache/Nginx server. It is kind of obvious that everything will be public. It's up to you to restrict access by IP, VPC or just add a simple HTTP Basic on your Apache/Nginx configuration.
