### ISSUE TITLE
Cannot view JSP

### ISSUE THREAD

**Issue by nodtem66** [klaussilveira/gitlist#501]
Gitlist cannot view jsp source code. However, the JSP raw file is normally shown.
https://www.google.co.th/search?q=gitlist+jsp
![image](https://cloud.githubusercontent.com/assets/220425/3838955/03bb6e00-1e0b-11e4-9d22-bc3af43d54f7.png)

**Comment by monkiki** [comment]
I can confirm the issue still exists in version 0.5.0

**Comment by monkiki** [comment]
I've found a fix: edit src/GitList/Util/Repository.php and change "jsp" mime type to "application/x-jsp".

:)

**Comment by monkiki** [comment]
Have you fixed it in the source code? I can't see the commit.

**Comment by monkiki** [comment]
Ok, thanks a lot!
