### ISSUE TITLE
Tarred file should be prepended with repo name and appended with .tar

### ISSUE THREAD

**Issue by jfposton** [klaussilveira/gitlist#503]
Currently the downloaded filename of a archived (zipped or tarred) repo archive is simply `<version>`. This isn't very helpful especially when there are multiple repos that  you are trying to archive and manage. So, when a repo is tarred the filename should be in the format `<reponame>-<version>.tar`

This gives three pieces of vital information: 
- general idea of what the contents is 
- what version of the content is in the file 
- what the format of the file is

versus
- a version

**Comment by alehaa** [comment]
Fixed in 7bf67f880bef06d2ff9a2728cd1d83e0077f67c0.
