### ISSUE TITLE
very poor performance vieweing files with ~8000 lines of code

### ISSUE THREAD

**Issue by erez-o** [klaussilveira/gitlist#510]
I'm trying to view a c file with 7700 lines of code.
It starts by only showing the first 404 lines, If you don't press the gitlist scrollbar, it doesn't continue reading the file.
After pressing, it only updates till 1200 lines of code, then you need to press again, then another 1200 lines, etc...
when the 7700 lines are finally read, the browser scrollbar acts by itself, and moves up in tiny steps of ~200 lines of code.

If someone sends you a url with a specific line e.g. #L5069, it still only shows you the beginning 404 lines, and gitlist doesn't alert user that the file has not finished reading.

I think the solution should be:
1) Update automatically till end of file
2) If syntax highlighting is a bottleneck and file will take too long to read, display without highlighting until it completes.

Thx very much, and great work

**Comment by garygreen** [comment]
Related to #605
