### ISSUE TITLE
Doesn't seem to be working on Windows

### ISSUE THREAD

**Issue by tobya** [klaussilveira/gitlist#511]
I did some work a long time ago to get gitlist working in a simple fashion in windows.  I just came back to gitlist and again am having difficulty getting it to run on windows.

Has anyone else managed to get the latest version working on windows?  With Apache?

I would be interested in working with another php windows developer to get gitlist working reliably on windows.  Is anyone interested?

**Comment by garygreen** [comment]
Duplicate of #574
