### ISSUE TITLE
Lighttpd rewrite issue maybe

### ISSUE THREAD

**Issue by Blueness-** [klaussilveira/gitlist#515]
I'm using lighttpd 1.4.28
I've added gitlist to the base of `/var/www` so it is `/var/www/gitlist/`
My `config.ini` points to `/home/git/` for my repos

So I get 404's everywhere when I don't do lighttpd url.rewrite-once.  (as expected)
When I do the rewrites on my `lighttpd.conf` as instructed in `INSTALL.MD`, my repos are now reachable but all the graphics and buttons are gone.  On closer inspection in the page source and clicking the element links, I get things like 
```
Oops! No route found for "GET /themes/default/js/jquery.js"
```
(from "http://xxxxxxxxx.xxx/gitlist/")

Somebody better than me at this suspects the url rewrite is also rewriting the links to the stuff in themes but I am not sure.  This might be an issue on my end so any help would be welcome.  I tried chmod 777 on the themes folder to see its not a permission issue.  

Everything on the page seems to work except all the theming is gone.  Not sure where the problem is residing.  I was looking at this for a possible solution but no luck:
http://serverfault.com/questions/293208/lighttpd-rewrite-rules-ignore-a-directory-recursively

I definitely restarted my Lighttpd server between my changes to the .conf file. I could be missing something very simple as I am not that great with this stuff. Any insight is welcome.

**Comment by krypty** [comment]
Thanks I had the same problem which is solved using your snippet.

**Comment by v01d** [comment]
Same here, changed "web" rewrite to "themes" (don't know if "web" is still used).
