### ISSUE TITLE
There are no GIT repositories in ....

### ISSUE THREAD

**Issue by radaway** [klaussilveira/gitlist#532]
There are no GIT repositories in /home/git/wiki/

create teste.php whith content

<?php
echo file_exists('/home/git/wiki/HEAD');
echo "</br>";
echo file_get_contents('/home/git/wiki/HEAD');
?>

return

1
ref: refs/heads/master 

my git OK

remote: Counting objects: 23, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 15 (delta 12), reused 0 (delta 0)
Unpacking objects: 100% (15/15), done.
From fisto01.dbseller:/home/git/wiki
   692999d..c3a741e  master     -> origin/master
Updating 692999d..c3a741e
Fast-forward
 infraestrutura/files/script/ubuntu/install_ecidade.sh |  2 +-
 infraestrutura/infra-base-dbdownloader.md             | 48 ++++++++++++++++++++++++++++++++++++++++++++++++
 infraestrutura/infra-roti-instalar-estacao.md         | 54 +++++++++++++++++++++++++++---------------------------
 3 files changed, 76 insertions(+), 28 deletions(-)

**Comment by bpetit** [comment]
Same problem here, on a fresh folder after a git init.
Tried using the path to /my/repository/ /my/repository /my/repository/.git/ and /my/repository/.git without success.

**Comment by DannyvdSluijs** [comment]
Based on both your paths I would say you need to correct your config and point it to a directory higher. As gitlist isn't a single repository viewer but an multiple repository viewer.

You need to point the config to the directory that contains all your repositories. 
@radaway I guess yours would be ```/home/git```
@bpetit  I guess yours would be ```/my```

**Comment by bpetit** [comment]
You're right. Using the parent directory it's ok. Thank you.
