### ISSUE TITLE
Minor version issue at the bottom

### ISSUE THREAD

**Issue by Blueness-** [klaussilveira/gitlist#534]
The latest build and the latest released version don't have an updated version number 0.5 at the bottom.  Still seems to be 0.4 unless i'm mistaken.  This made me try several times to reinstall the software because I thought I broke something hehe.

**Comment by dkozel** [comment]
This has been partially fixed in https://github.com/klaussilveira/gitlist/commit/e70cb0ff7892ae2c1046b8656804baf1d8929bfd so an install of master now shows 0.5.0. 

A request to make the version string dynamic is tracked over at https://github.com/klaussilveira/gitlist/issues/570.

**Comment by garygreen** [comment]
Has been fixed.

**Comment by ooxi** [comment]
[Official download](https://s3.amazonaws.com/gitlist/gitlist-0.5.0.tar.gz) still reports the wrong version

> Powered by GitList 0.4.0

**Comment by dkozel** [comment]
@ooxi The official download is the 0.5.0 release from June 29, 2014 and the version number was fixed August 14, 2014. Until a new release occurs an installation from source is needed to get the correct version number to be displayed.

**Comment by ooxi** [comment]
@dkozel how about releasing 0.5.1 as minor bugfix release? This seams really trivial bug gives a bad impression to the stability of this project.

Nevertheless the software itself looks good!

**Comment by dkozel** [comment]
@ooxi I am not a developer with the project, just a user. There was a discussion about the next release some time ago but there seems to be a lot of work left to do. In the meantime it is not too difficult to install GitList from source if you need any of the fixes and updates since the 0.5.0 release.

**Comment by ooxi** [comment]
Sorry I thought you are one of the developers :)
