### ISSUE TITLE
Problem with hyphen in git name

### ISSUE THREAD

**Issue by mimocx** [klaussilveira/gitlist#535]
I installed both 0.5.0 and the development master on Windows 7 with XAMPP, running PHP 5.6.3.
I cloned two gits from github.com and I receive these error in gitlist:
```
Oops! An exception has been thrown during the rendering of a template ("Parameter "repo" for route "repository" must match "lunifera\\-xtext\\-runtimebuilder|valo\\-demo" ("lunifera-xtext-runtimebuilder" given) to generate a corresponding URL.") in "index.twig" at line 16.
```
When I rename to get directory names without Hyphen it works!
But I can't just force anyone to use directory names without hyphens, or maybe without dots too?

Is there a fix for that, when using hyphens in directory names? It seems that some code encodes the hyphens...

config.ini
```
[...]
repositories[] = 'C:\local\GIT\gitlisttest\'
[...]
```

Directory listing of C:\local\GIT\gitlisttest\
```
lunifera-xtext-runtimebuilder
valo-demo
```

**Comment by garygreen** [comment]
Fixed in PR #554
