### ISSUE TITLE
Not able to view files with a ~ (tilde) in their name.

### ISSUE THREAD

**Issue by Anialation81** [klaussilveira/gitlist#537]
My team and I are unable to view files with tilde's in the file name. We have a hack solution for ourselves for now, but I doubt that this is a proper fix for the problem.

The tilde gets escaped and comes out as "\~" instead of "~".

We've added a line to part of the Symfony framework to do a str_replace to swap it out, but obviously that is out of scope for this project, but was a quick hack to fix our small issue.

**Comment by garygreen** [comment]
Confirmed, it's some kind of bug in Symphony. @Anialation81 what part of Symphony / Silex did you narrow it down to?

**Comment by garygreen** [comment]
Related to #419 once the escaping issue is fixed these 2 can be closed.
