### ISSUE TITLE
Demo site running 0.4.0

### ISSUE THREAD

**Issue by drakej** [klaussilveira/gitlist#539]
I noticed the demo site linked in README.MD is still running the older 0.4.0 version of gitlist.

**Comment by x29a** [comment]
yeah, downloading the 0.5.0 stable tarball still results in a "powered by GitList 0.4.0"

**Comment by diskerror** [comment]
Yup, it 0.5.0 still shows "0.4.0".

**Comment by khornberg** [comment]
I think I updated it last year to 0.5.0 but I'll check on it.

**Comment by khornberg** [comment]
It's updated to 0.5.0. The version tag was not updated.

**Comment by garygreen** [comment]
Has been updated.
