### ISSUE TITLE
Simple "Clone" Block wanted

### ISSUE THREAD

**Issue by eits-admin** [klaussilveira/gitlist#549]
I would like a very simple "legend" block on the right side of the repo browser called:  "Clone Repo" with clone information configured in config.ini so the legend appears as a URL that I can copy/paste into my git client.

that way I don't have to remember my server information/path, etc.

Cool tool!  thanks for this!

**Comment by klaussilveira** [comment]
Duplicate of: https://github.com/klaussilveira/gitlist/issues/205
