### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by rich-pixley** [klaussilveira/gitlist#551]
I dunno what I'm doing wrong but all I get is a blank page.

rhel7

**Comment by x29a** [comment]
Which operating system, which webserver, can you state the steps you followed to install? which version of gitlist are you using? with that information, we might be able to check logfiles which might lead to more useful information

**Comment by dopejack** [comment]
I solved this by changing permissions for my directory containing the repositories:

`chmod 705 /myrepos`

**Comment by garygreen** [comment]
You might not simply have any repositories found in the path defined in your `config.ini` -- at the moment gitlist does not gracefully give an message, instead it throws an exception, which will likely not show if you have debugging turned off.

**Comment by klaussilveira** [comment]
Make sure you follow the installation instructions correctly. Check your webserver and PHP error logs. Provide more information in the future so we can help you.
