### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by IgorDePaula** [klaussilveira/gitlist#560]
É possível ter algum tipo de autenticacao mesmo que um usuario e senha estaticos?

**Comment by klaussilveira** [comment]
Você pode fazer isso através do Nginx ou Apache, mas não é o foco do projeto oferecer funcionalidades de gerenciamento, autenticação ou autorização em repositórios.

ps.: Next time, please write issues in english so other users can benefit from Q/A.

**Comment by IgorDePaula** [comment]
Thank you, your response is very useful!

Em 6 de fevereiro de 2015 13:47, Klaus Silveira <notifications@github.com>
escreveu:
