### ISSUE TITLE
Browsing commits not showing latest commits

### ISSUE THREAD

**Issue by kjkeefe** [klaussilveira/gitlist#561]
I have gitlist set up to display a repo. After a new commit is made, I can view it by entering the url of the commit directly:

www.example.com/MyProject/commit/9e68a443bc6b081525ee7cc0ac0ff4d13f1d3769

However, if I browse commits, it is not in the list of commits:

www.example.com/MyProject/commits/master

Do I have to do something to refresh the list of commits in the browsing view?

**Comment by alehaa** [comment]
@kjkeefe Seems like the commit was not part of `master`. Please reopen the issue, if its still affecting you.
