### ISSUE TITLE
Is this project still actively developed?

### ISSUE THREAD

**Issue by jniggemann** [klaussilveira/gitlist#565]
- open PR for this project haven't been merged since quite some time
- last commit to master branch almost 4 months ago
- Klaus can be found responding to issues every now and then

**Comment by klaussilveira** [comment]
Me, and probably the other contributors as well, don't have the time we wanted to spend on the project. GitList needs some serious refactoring, specially in terms of performance. Right now it doesn't scale very well and we need to change how it communicates with Git to solve this. 

Therefore, i'm not dedicating enough time to new features. The best place to focus your attention, if you're willing to contribute to the project, would be the Gitter library: https://github.com/klaussilveira/gitter

We have create an Adapter-ish architecture for Git communication, allowing easy integration with libgit and whatever might come in the future. We also need a better output handling protocol.

**Comment by jniggemann** [comment]
Thanks for letting us know and for merging!

**Comment by klaussilveira** [comment]
Just ping me if i take too long to merge something. Or scream/curse at me. If it's still unmerged and without a comment, i didn't see it or didn't had time to properly see it (not just a scan).
