### ISSUE TITLE
Support for content-type when serving blobs in raw mode

### ISSUE THREAD

**Issue by vgheo** [klaussilveira/gitlist#571]
Use case :  
A git repositiory is used to store static web contents (html, xhtml, xml+xsl). 
Files contain links with relative paths within the same tree.
When the repo is browsed in gitlist at any commit:
- a) the 'raw' URLs for  html / xhtml/ xml+xsl files shall be properly presented by the browser
- b) the relative links in the files shall resolve to respective files in the same commit

Currently all files in raw mode are served as text/plain, which prevents the desired behaviour.

Note that gitweb does generate proper mime types in raw mode. However, due to the URL structure, gitweb cannot support requirement b) above.

I have [experimented](https://github.com/vgheo/git-serve-xml) by changing the gitlist BlobController.php to serve only text/xml, and results are positive.  (see [patch](https://github.com/vgheo/git-serve-xml/blob/master/gitlist-serve-xml.patch)).

**Comment by alehaa** [comment]
Seems to be related to #451 and #452.
