### ISSUE TITLE
Are you cloning repos in order to get commits and branches?

### ISSUE THREAD

**Issue by goors** [klaussilveira/gitlist#572]
Hi,

I just have one question and that is are you cloning repos in some /tmp or something in order to obtain 
branches or commits?

I am asking this because you are saying in your Client class run method something like git -c "color.ui"=false branch repopath (what is your repo path by the way repo name?), and you are setting setTimeout to 180.

Why is that?
It would be great if you can answer this question.

**Comment by goors** [comment]
I can use git ls-remote to get remote branches but to get commits that is a real problem, not to mention to get some file. I would really appreciate your answer.

**Comment by goors** [comment]
I see you are running this command for example/usr/bin/git -c "color.ui"=false branch /home/git/repositories/repo.git in order to get branches but when i run it i just get 

<pre>Not a git repository (or any of the parent directories): .git</pre>

**Comment by fauxpark** [comment]
There's no cloning of repos going on. The "/home/git/repositories/repo.git" part isn't included as part of the command, it's specified as a separate parameter to the Process constructor to tell it *where* to run the command from (the "working directory").

The "-c color.ui=false" bit is just telling Git (versions higher than or equal to 1.7.2) not to output in colour, as the extra control characters used for that mess up Gitter's parsing. Git allows you to set config values for the command being run.

**Comment by goors** [comment]
You did not really answer all my questions but never mind. I will try to figure out on my own so I can make some simpler python lib.

**Comment by klaussilveira** [comment]
GitList does not clone repos. It sits on the same server as your central remote git server, or any kind of relay server. When you configure the application, you specify the path where your repos are, usually, `/home/git`.

**Comment by goors** [comment]
It would be great if code is explained a little bit more so i can understand directly from code how to list branches and commits without doing deep debug of code.

I will post update once i finish python lib for this.
--
Sent from myMail app for Android
Monday, 30 March 2015, 03:44PM +02:00 from Klaus Silveira <notifications@github.com>:

**Comment by fauxpark** [comment]
I think you might be looking in the wrong repository. Gitlist doesn't handle listing branches and commits etc. by itself. It's just a web interface for viewing repositories.

Instead it uses [gitter](https://github.com/klaussilveira/gitter) to do the heavy lifting. The methods you're looking for are in there in the Repository class.

**Comment by goors** [comment]
I see that this Gitter is same as this project. Both are using some Client class to get this stuff like branches and commits. But I do not see how. Can you explain?

**Comment by fauxpark** [comment]
The Client and Repository classes in Gitlist extend Gitter's Client and Repository classes. They only exist in Gitlist to do stuff specific to Gitlist that wouldn't belong in Gitter, like getting paginated commits and generating ZIP/TAR files.

They also override a couple of Gitter's methods, again for Gitlist-specific reasons. For example, Gitter's Client::getRepository() method returns an instance of Gitter\Repository, but since Gitlist extends the Repository class, it needs to return a instance of Gitlist\Git\Repository instead.

**Comment by goors** [comment]
I did is: 
<pre>cd  /home/git/repositories/repo.git</pre>

And then run:
<pre>/opt/local/bin/git -c "color.ui"=false log --pretty=format:"<item><hash>%H</hash><short_hash>%h</short_hash><tree>%T</tree><parents>%P</parents><author>%an</author><author_email>%ae</author_email><date>%at</date><commiter>%cn</commiter><commiter_email>%ce</commiter_email><commiter_date>%ct</commiter_date><message>%s</message></item>"</pre>

This is great. Now I can write anything. I just need to make small api with Flask + Python now.
I will keep you posted.
