### ISSUE TITLE
Bare repo gives Oops! fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by makerimages** [klaussilveira/gitlist#574]
Well, the title pretty much says it. in my repos folder i have a bare repo named sth.git. When I try to open that, the error `Oops! fatal: Not a git repository (or any of the parent directories): .git
` throws up. Any regular repos cloned from Gh into that dir work just fine...

**Comment by makerimages** [comment]
could be that the repo name is actually sth.ee.git ? Maybe doesnt like that?

**Comment by SamMousa** [comment]
Confirmed, it just fails on when the repo is bare.

**Comment by fauxpark** [comment]
Works fine for me, even in a subdirectory: http://git.fauxpark.net/subdir/sth.ee.git/

Might be more a configuration issue than a bug, I think. What OS are you running GitList on?

**Comment by TheNotary** [comment]
Maybe issue #553 will help?  A tut I read said to use regular repo clones which concerned me, but I think it might work on bare repos too (if you setup permissions where the person pushing to the repo doesn't block gitlist from accessing it).

**Comment by tribis** [comment]
I've just made a clean install of gitlist with bare repos, it works fine.
I guess it's the same problem as in here:
https://github.com/klaussilveira/gitlist/issues/345
If you are using gitolite, reading this:
http://gitolite.com/gitolite/g2/rc.html
 (for gitweb, but the issue is the same) might help

**Comment by JBlond** [comment]
I tried bare repos on Debian an Windows. Both work fine.

**Comment by bjornl** [comment]
If you do experience this problem (regular repos display, but bare repos display error "Oops! fatal: Not a git repository" it is a access problem related to directory and file privileges.

I found out then recursive ownership is root.root regular repos do work but bare repos do not. Solution is to change repo ownership to that of the Apache daemon.

Stand in the top-level repo directory and issue:
chown -R apache:apache .

**Comment by JBlond** [comment]
On my Debian server the apache run as www-data, The files are owned by JBlond JBlond and it works without an issue.
