### ISSUE TITLE
Add better gitolite integration

### ISSUE THREAD

**Issue by protobits** [klaussilveira/gitlist#576]
With gitolite, different users have access to different repos. The access level can be checked at runtime (since it depends on a non-fixed set of rules), for example using a simple bash script.

The idea would be to use simple htpasswd based authentication first (simple webserver configuration) and then use the supplied username and repo name to check access. If a user does not have access the repo will not show in the project list.

Is there interest for this?

**Comment by sstackcta** [comment]
@v01d, we use Gitolite, so yes there's interest. Would not this require a user to login to view Gitlist? Or use defaults from anonymous access?

**Comment by v01d** [comment]
In gitweb this is solved by using webserver authentication (i.e. htpasswd
file). Gitolite already can generate this file and supplies a nice
interface to creating the password for any user. So, the whole gitlist
would be behind this user/pass check. You can then require a valid user. If
no authentication is configured (user has not supplied htpasswd file),
gitlist should detect this and set as username some special name (say
gitlist) which can be made to have full read permission.

**Comment by Malcolm** [comment]
I ran into the same issue when wanting to deploy for my company.  I'm doing auth with Apache and LDAP or unixgroup, came up with this hacky solution:
```diff
--- --      2014-06-29 23:07:23.000000000 -0400
+++ gitlist/src/GitList/Git/Client.php  2016-07-04 15:43:37.048000000 -0400
@@ -50,6 +50,24 @@
             return strtolower($k2)<strtolower($k1);
         });

+        $repomask = array();
+        $out = shell_exec("GL_USER={$_SERVER['PHP_AUTH_USER']} HOME=/path/to/gitolite /path/to/gitolite/src/gitolite info -json");
+        if($out) {
+          $out = json_decode($out, true);
+        }
+        if($out){
+          foreach($out['repos'] as $repo => $_){
+            if(substr($repo, -3) != '..*'){
+               $repomask[] = '/path/to/gitolite/repositories/' . $repo . '.git';
+            }
+          }
+          foreach($allRepositories as $index => $details){
+            if(!in_array($details['path'], $repomask)){
+              unset($allRepositories[$index]);
+            }
+          }
+        }
+
         return $allRepositories;
     }
```

Hope that help's someone out, not sure how this would be looped into the main app.  You'd probably want to validate the input on $_SERVER['PHP_AUTH_USER'], so you don't have someone running stuff on your server, like our friend [bobby tables](https://xkcd.com/327/).
