### ISSUE TITLE
Does this work for `git clone` commands?

### ISSUE THREAD

**Issue by nhr** [klaussilveira/gitlist#579]
I tried to run the clone command against a server where I am running `gitlist`, but I am seeing a 500 error:

    $ git clone http://192.168.1.175/gitlist/foo
    Cloning into 'foo'...
    fatal: unable to access 'http://192.168.1.175/gitlist/foo/': The requested URL returned error: 500

Is gitlist intended to work this way, or it i just for viewing and grabbing tarballs of git repos?

**Comment by DannyvdSluijs** [comment]
Gitlist works as a viewer.

**Comment by nhr** [comment]
That makes me sad :-( Any plans to enable git clone support?

**Comment by brunogaspar** [comment]
@nhr You'll need to create a Git server for that, as @DannyvdSluijs mentioned, this is only a repository lister/viewer.

You can Google for how to's and tutorials on how to achieve this.
