### ISSUE TITLE
Show last modification

### ISSUE THREAD

**Issue by SamMousa** [klaussilveira/gitlist#580]
It would be really great if we could have configurable columns like modification date for repositories and files.

**Comment by klaussilveira** [comment]
This is planned, but we really have to implement a cache layer before.

**Comment by garygreen** [comment]
I've re-added the caching back into my forked version of gilist, if your interested https://github.com/garygreen/gitlist/commit/ec6e3084e4a8e9ef1a6107050021164779c069e8

To me gitlist is unusable without caching, so needed it adding whatever the implementation. :-)
