### ISSUE TITLE
Feature request: Append ".zip" or ".tar" to downloads

### ISSUE THREAD

**Issue by sstackcta** [klaussilveira/gitlist#584]
If you are browsing a branch or tag named, say, "v6.0.0" and click either the Zip or Tar button, the download is named "v6.0.0". This confuses users who are expecting a .zip or a .tar in their download folder. Especially bad in Windows file explorer where the file Type becomes "0 File". 

Please consider appending a file extension to the download.

**Comment by zielu701** [comment]
That would be awsome...

**Comment by bjoernffm** [comment]
@garygreen Is that suitable for fixing the issue?

**Comment by garygreen** [comment]
Yes, thanks :)
