### ISSUE TITLE
Slow In WAMP

### ISSUE THREAD

**Issue by hunyoboy** [klaussilveira/gitlist#593]
Hi,

Everything is perfect except it's just really slow in WAMP. I'm running it locally and I turned-on cache too. Just to prove that it's slow in WAMP, I installed gitlist on Ubuntu with Apache server and everything is blazing fast. Really a big difference in page loading speed when running in Ubuntu. Is there a configuration I need to tweak so it will be faster in WAMP? I'm using gitlist on my work and we're running it on Windows Server using WAMP. Am I missing something to make it faster in WAMP?

**Comment by JBlond** [comment]
I can confirm that it is even with cache enabled mucg slower on windows not matter if I use git 1.9.5 or 2.4.0

**Comment by garygreen** [comment]
This is likely because caching was stripped out a while back. On every page load it now transverses all the directories looking for git repos. I've forked gitlist and added caching back in if you interested in taking a look: https://github.com/garygreen/gitlist/tree/caching

**Comment by JBlond** [comment]
@garygreen Did you open a pull request for that yet?

**Comment by garygreen** [comment]
Caching is a known issue atm, will be fixed in next major release or possibly 0.* when I find the time.
