### ISSUE TITLE
Twig runtime error if a git repo has a dash in the name on Windows

### ISSUE THREAD

**Issue by JBlond** [klaussilveira/gitlist#594]
Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Parameter "repo" for route "repository" must match"app\\-cache" ("app-cache" given) to generate a corresponding URL.") in "index.twig" at line 16.

**Comment by garygreen** [comment]
Known issue. Looks like @klaussilveira is inactive as I've open a PR for this way back in Feb and no news. PR #554
