### ISSUE TITLE
gitlist.org shows Renew Now

### ISSUE THREAD

**Issue by rbeede** [klaussilveira/gitlist#595]
It looks like the domain hosting for gitlist.org has expired.   No longer able to download stable builds :(

**Comment by simonsmiley** [comment]
it is down, but you can download them under releases in github

**Comment by mkasu** [comment]
It seems the packages in "releases" aren't really release builds. I needed to use composer app to download third party libraries, even though they are supposed to be bundled.

**Comment by simonsmiley** [comment]
yeah, that's the only downside (that I know of)
they can't be bundled in github releases, since they are just tags. the archives contain all the files from that tag.

**Comment by djmattyg007** [comment]
The URL to download the latest version is still available:
https://s3.amazonaws.com/gitlist/gitlist-0.5.0.tar.gz

**Comment by JBlond** [comment]
The website is back.

**Comment by rbeede** [comment]
Verified gitlist.org is back to original site with the renew notice gone.
