### ISSUE TITLE
Message : Please, edit the config file and provide your repositories directory

### ISSUE THREAD

**Issue by gugansankar** [klaussilveira/gitlist#599]
When I go and type the url in browser, it shows the message as "Please, edit the config file and provide your repositories directory" . 

This is my config.ini file entry:

===============
[git]
client = '/usr/bin/git' ; Your git executable path
default_branch = 'master' ; Default branch when HEAD is detached
repositories[] = '/home/user1/repo/' ; Path to your repositories
                                           ; If you wish to add more repositories, just add a new line

[app]
debug = false
cache = true
theme = "default"
baseurl = 'http://172.20.5.202:7074/'

; If you need to specify custom filetypes for certain extensions, do this here
[filetypes]
; extension = type
; dist = xml

; If you need to set file types as binary or not, do this here
[binary_filetypes]
; extension = true
; svh = false
; map = true

; set the timezone
[date]
; timezone = UTC
; format = 'd/m/Y H:i:s'
==============================

@klaussilveira  Is there any configuration issues there?. Please give some suggestion

**Comment by gugansankar** [comment]
I fixed it finally.

**Comment by dkozel** [comment]
@gugansankar Can you add what you did to fix it for future reference?

**Comment by gugansankar** [comment]
@dkozel  The issue was because of repository Folder permission.

**Comment by andymnc** [comment]
so how to set permissions? 755, 777 or what else?
