### ISSUE TITLE
Unnamed repositories

### ISSUE THREAD

**Issue by m-legrand** [klaussilveira/gitlist#601]
How can we get rid of this message, even present in the demo : http://gitlist-khornberg.rhcloud.com/ ?
> Unnamed repository; edit this file 'description' to name the repository.

**Comment by m-legrand** [comment]
http://stackoverflow.com/questions/2041993/how-to-rename-a-git-project-name

**Comment by dkozel** [comment]
The message could be improved to say which file to edit.

    Unnamed repository; edit the file '.git/description' to name the repository

**Comment by DannyvdSluijs** [comment]
@dkozel. Suggested is correct for non bare repositories. Bare repositories have no .git folder. In a master repo server you tend to work with a bare repo over non bare repos

**Comment by dkozel** [comment]
@DannyvdSluijs Right! The grammer change should be done though.

    Unnamed repository; edit the 'description' file to name the repository
