### ISSUE TITLE
missing /vendor folder

### ISSUE THREAD

**Issue by j88per** [klaussilveira/gitlist#602]
installed per instuctions on github, enabled display_errors, and am receiving this message.  There is no vendor folder in install nor on github.

Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/gitlist/index.php on line 21

Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/gitlist/index.php on line 21

**Comment by brunogaspar** [comment]
You'll need to have Composer installed, after that run `composer install` or `php composer.phar install`.

Otherwise just download the file from http://gitlist.org/ which comes bundled with the vendor folder aka dependencies.
