### ISSUE TITLE
preg_match compilation failed - your regular expression is too large

### ISSUE THREAD

**Issue by toosacrowd** [klaussilveira/gitlist#603]
```
PHP Warning: preg_match(): Compilation failed: regular expression is too large at offset 35165 in ../gitlist/vendor/symfony/routing/Symfony/Component/Routing/Matcher/UrlMatcher.php on line 134
```

We're get the above message (with various numbers around 35000) in my apache error_log... I get the feeling that it's down to the number of gits we're trying to serve. Have been adding 20-30 gits a day and went over 1200 on Friday (whilst I was away) and at some point this error started appearing. (we're using v0.5.0 btw)

When trying to go to the root of the gitlist directory (where the index appears) I get a very long error listing all the gits and saying it can't find a match... when trying to go into a specific git directly we see an error along the lines of `Oops can't find route to GET /foo/bar.git`.

**Comment by SeLLeRoNe** [comment]
Hi am actually having the same issue with the root repository folder contains 70 repositories (and some are folders that have sub-repos).

Is there any suggestioin to fix this?

Thanks
Best regards
Andrea

**Comment by alehaa** [comment]
I don't think there's a quick fix.

At the moment, all available repositories get compiled into a regex to match the URL instead of searching for them on-demand. The related code and its logic needs to be changed to support more repositories.

**Comment by SeLLeRoNe** [comment]
Hi, thanks for your reply.

I see your point, do you happen to know what would the current limit be?

Thanks
Andrea

**Comment by SeLLeRoNe** [comment]
I see.

Thanks for the info :)
