### ISSUE TITLE
line number deeplinks not anchoring correctly

### ISSUE THREAD

**Issue by ollyjackson** [klaussilveira/gitlist#605]
As the line number anchors are generated at render time in main.js they don't function as "proper" anchors. Sharing links to specific files within a repo with an anchor to a particular line number is quite a useful feature.

**Comment by garygreen** [comment]
+1 would be very useful.

**Comment by erez-o** [comment]
I think that anchors not working is only a small part of the problem. 

The bigger issue is when you view a normal sized source file, and (1) it's not fully displayed, (2) there is no indication that the file hasn't finished reading, (3) you have to manually reclick the scroll bar in order for the file to continue being read.

**Comment by garygreen** [comment]
Agreed, the feedback to the user / overall experience of lazy loading the file needs to be improved.

**Comment by erez-o** [comment]
:thumbsup:

**Comment by ollyjackson** [comment]
I've got a WIP fix for the anchoring issue -  basically updating to a newer version of CodeMirror and using `scrollIntoView` . I'll post an update here once I've polished it a bit.

**Comment by erez-o** [comment]
Just my 2 cents:
If I remember correctly, for viewing purposes, Codemirror is quite slow, since it allows you to edit as well, which is not needed here.
Highlights.js is a common syntax higlighter, but it doesn't support line numbers, so I don't think its a good choice.
There are others, but unfortunately, I didn't find on the web a good comparative speed test that was done lately

**Comment by garygreen** [comment]
Maybe this could be of use? http://www.minh.io/tech/2013/08/17/highlightjs-line-numbers/

**Comment by erez-o** [comment]
Before we discuss a change in syntax higlighter, is the edit ability of codemirror needed? Cause it's the only syntax higlighter I know that has it. I also see that it does have a readonly mode, maybe it's not slower than the alternatives in this mode.

Each syntax highlighter has its quirks, for example prism has limitations that I don't know if will fit Gitlist - http://prismjs.com/#limitations

I think that for big files, there's no alternative except highlighting using sever side. I'm not familiar with php, but from googling, Geshi looks like a common library.
