### ISSUE TITLE
Gitlist Page Not Found

### ISSUE THREAD

**Issue by ibanks** [klaussilveira/gitlist#606]
Hello to all.

This is my first time using gitlist. I had it setup before to track the git repo that I'm working on. However, I had to recreate the git repo that gitlist was tracking. I didn't think it would be an issue if I just recreated the git repo in the same path that gitlist was pointing to but it appears to have broken something. I'm not sure. 

The message I'm getting is: 
"Sorry, the page you are looking for could not be found:"
"NotFoundHttpException in RouteCollection.php line 143:"

Then it provides some stack trace information. I already downloaded a fresh stable copy of gitlist from the main site (gitlist.org). I followed the instructions to configure it as it is still pointing to the same path as the directory that holds the git repositories. I also set the group of the gitlist directory to "www-data" so apache could read and execute the files. I have my cache folder created and writable and I changed the config.example file to config.ini. It appears I've done everything but I'm still getting that error. 

Any assistance would be much appreciated. Thanks.

**Comment by alehaa** [comment]
Please reopen the issue, if you're still affected by this bug, as I couldn't find a bug like this one in my installation.
