### ISSUE TITLE
Git repository "Page not found"

### ISSUE THREAD

**Issue by cloareq** [klaussilveira/gitlist#609]
I installed gitlist in /var/www/gitlist

I configured my config.ini in order to specify my git repository path.

When I go on "http://myserver/gitlist" I see the repository I want

But when I click on it I have a 404 not found.

I added 

Alias /gitlist /var/www/gitlist/
<Directory /var/www/gitlist>
  AllowOverride All
</Directory>

in my apache2.conf but I still have the issue

**Comment by garygreen** [comment]
Looks like a server configuration error and not gitlist related. You'd probably be better off asking on stackoverflow.
