### ISSUE TITLE
Please, edit the config file and provide your repositories directory

### ISSUE THREAD

**Issue by Echarnus** [klaussilveira/gitlist#612]
As the title says, I'm getting a  `Please, edit the config file and provide your repositories directory` error. The solutions I found were always about the permissions of the folder. My folder already has the permissions 775 (even tried 777). 

My config file: 
```
[git]
client = '/volume1/@optware/bin/git' ; Your git executable path
repositories[] = '/volume1/git/' ; Path to your repositories

; You can hide repositories from GitList, just copy this for each repository you want to hide
; hidden[] = '/home/bob/code/SecretProject'

[app]
baseurl = 'http://localhost/gitlist' ; Base URL of the application
```
My system is a Synology NAS using DSM 5.2.

**Comment by shatadru** [comment]
Same issue with Fedora 22

**Comment by Krozark** [comment]
same issue with Ubuntu 14.04 and gitlist 0.5

**Comment by dfleury2** [comment]
Under Synology, I found that Vi adds a caracter at the beginning of the file so it removes the git section.
(adding some trace into src/GitList/Config.php)

**Comment by xstrex** [comment]
Same issue on Synology 6.0.1-7393 Update 1.

**Comment by JayEn84** [comment]
@Krozark Were you able to solve this? I am running into the same problem on Ubuntu. Obviously, the Apache user does not have the permission to read the repositories directory, but  I do not know what to do. See [here](http://stackoverflow.com/questions/42833378/gitlist-does-not-work-possibly-because-of-linux-user-permissions) for a detailed description.

**Comment by alenmeister** [comment]
I'm having the same issue on my OpenBSD 6.5 server with OpenBSD's own httpd server and PHP 7.1 - The git user has its home folder located under /var/www/htdocs/git, which is what I've pointed config.ini to. Permissions are set to 755 and shouldn't be an issue. I've also tried with a bunch of other user permissions and nothing seems to do the trick. What could be the problem?
