### ISSUE TITLE
Does not work with bare repository

### ISSUE THREAD

**Issue by rambabusaravanan** [klaussilveira/gitlist#616]
Works fine for my repositories, but when I added a bare repository, it throws the following error.

Oops! An exception has been thrown during the rendering of a template ("Parameter "repo" for route "repository" must match "sample\\.git|SharesLocal|gitblit" ("sample.git" given) to generate a corresponding URL.") in "index.twig" at line 16.

I am using windows 7 64bit.

**Comment by garygreen** [comment]
This has been fixed in master, just not tagged yet. 12080cee1a195336986ffe2a5e1bcfcec076d68b
