### ISSUE TITLE
download v0.5 from homepages contains v4.0

### ISSUE THREAD

**Issue by cavebeat** [klaussilveira/gitlist#617]
https://s3.amazonaws.com/gitlist/gitlist-0.5.0.tar.gz leads to v0.4.0

**Comment by wohlben** [comment]
urm, yeah. i just now checked which version i've downloaded last year (august 26). the downloaded package is named 0.5.0 but the branding at the button of the website says 0.4.0...

**Comment by garygreen** [comment]
It is the 0.5v but there was a bug where it would list the old version number in the footer. Has been fixed in master.
