### ISSUE TITLE
Search in commit is case sensitive

### ISSUE THREAD

**Issue by NicolasPicard** [klaussilveira/gitlist#624]

**Comment by greyboard** [comment]
This was very good, if you can fix it.

**Comment by tnguyen14** [comment]
I would love to have search be case insensitive too! Or smart case sensitivity would be best! (insensitive if all lowercase, sensitive if there's uppercase)

**Comment by fauxpark** [comment]
I actually fixed this a while ago, there just hasn't been a new release since: https://github.com/klaussilveira/gitlist/commit/a623cd1

**Comment by tnguyen14** [comment]
Thanks @fauxpark. @garygreen I don't think this issue should be closed until there's a release. I can't really access this feature now.
