### ISSUE TITLE
Missing data on repos

### ISSUE THREAD

**Issue by lebogan** [klaussilveira/gitlist#625]
When viewing a repo, the commits screen is blank and the network screen just shows a progress indicator. Running version 0.5.0 which shows up as 0.4.0 on the main home page. All other features work as expected. What have I missed?

Thank you for any help you can give. I appreciate all the work that has gone into this application.

My system:
Linux gitserver.earthsea.local 4.1.6-201.fc22.x86_64 #1 SMP Fri Sep 4 17:49:24 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

My config file:
[git]
client = '/usr/bin/git' ; Your git executable path
default_branch = 'master' ; Default branch when HEAD is detached
repositories[] = '/opt/git/' ; Path to your repositories
                                           ; If you wish to add more repositories, just add a new line

[app]
debug = true
cache = true
theme = "default"

; If you need to specify custom filetypes for certain extensions, do this here
[filetypes]
; extension = type
; dist = xml

; If you need to set file types as binary or not, do this here
[binary_filetypes]
; extension = true
; svh = false
; map = true

; set the timezone
[date]
; timezone = UTC
; format = 'd/m/Y H:i:s'

![screenshot from 2015-09-16 22-00-15](https://cloud.githubusercontent.com/assets/1024382/9925307/8957e9ce-5cbe-11e5-9530-eac87b85eefe.png)

**Comment by garygreen** [comment]
How big is your repository (MB/s and number of commits)?

**Comment by lebogan** [comment]
Thank you for the reply.
This repository currently is 520K with 7 commits. All my repos total 5M with various amounts of commits per repo. My largest repo is 1.8M.

**Comment by lebogan** [comment]
After trying three browsers, I finally got this error to show up with Opera when trying to view commits. It looks like I have something configured incorrectly but, for the life of me, I can't find it. Still looking:

![screenshot from 2015-09-23 14-04-32](https://cloud.githubusercontent.com/assets/1024382/10058807/44039d44-61fc-11e5-97ba-14b47c4b156d.png)

**Comment by garygreen** [comment]
Haven't got a clue. Looks like a server configuration issue to me. Have you
tried installing gitlist on an absolute url like
http://gitserver.earthsea.local/logger.git/...
Also have you checked any other issues on gitlist, like does PR #587
possibly help?

**Comment by lebogan** [comment]
Thanks. PR#587 didn't help. I did get this in the httpd error_log at the same time I requested the commits:

PHP Fatal error:  Class 'SimpleXmlIterator' not found in /var/www/html/gitlist/vendor/klaussilveira/gitter/lib/Gitter/PrettyFormat.php on line 22, referer: http://gitserver.earthsea.local/gitlist/index.php/logger.git/tree/master/

I checking on this.

**Comment by garygreen** [comment]
It's probably down to the way you've compiled php, possibly with the `--disable-simplexml`. See https://bugs.php.net/bug.php?id=39704

**Comment by lebogan** [comment]
I rebuilt the server using the development version and composer/ant.
Everything works as advertised. Who knew...
On Thu, 2015-09-24 at 01:50 -0700, Gary Green wrote:
> Closed #625.
> —
> Reply to this email directly or view it on GitHub.
-- 
> It is as easy to create a castle as a button. It's just a matter of whether you're focused on a castle or a button.
> 
> --- Abraham

**Comment by jackwu833016** [comment]
I've bumped into this problem as well, but reinstalling development version, composer and ant doesn't help until I found this.
[Class SimpleXMLIterator not found in zend framework 1 when zf create project ZendApp with PHP7](https://stackoverflow.com/questions/39820205/class-simplexmliterator-not-found-in-zend-framework-1-when-zf-create-project-zen)

**Comment by ghuser** [comment]
For ubuntu 16: `sudo apt install php7.0-xml` solved the issue.
