### ISSUE TITLE
git commit

### ISSUE THREAD

**Issue by VirusEntertainment** [klaussilveira/gitlist#626]
hello i just discovered this tool. I have gitlist on my local webserver..

I can get to the page that lists my repositories.. When i click on a repo it says "Oops! fatal: your current branch 'master' does not have any commits yet"

I tried to git commit -am "init" that folder but still this message

what i do wrong? Have i missed something? I followed the install.md

**Comment by DannyvdSluijs** [comment]
Gitlist had issue with empty repos. Try making an initial commit

**Comment by VirusEntertainment** [comment]
It is not empty..
Gitlist is in X:\gitlist
I have Made the rewrite /gitlist/

Then i have set inside .ini X:\repositories as folder

Then i have

X:/repositories/mywebsite/(everything Also .git folder)

i can see the folder but nothing inside of it.. Maybe it's because i moved after "git init" the files in the folder?

**Comment by patackett** [comment]
I see this is closed but do not see the resolution.  I have the same problem and my repo is not empty.  git log shows multiple commits but the error message says there are not commits.
