### ISSUE TITLE
ZIP/TAR button not working in bootstrap3 Theme

### ISSUE THREAD

**Issue by haikarthikssk** [klaussilveira/gitlist#628]
When i try to download the git as ZIP archive , it is downloading normally in default theme . But in bootstrap3 theme , the button remains in hover state , without any action.

**Comment by LanceSandino** [comment]
Had the same issue, at first I was just going to do "onclick="location.href='XXXX';"
but thought that there could be some browser compatability issues.

So I decided on this:

<a href="{{ path('archive', {repo: repo, branch: branch, format: 'zip'}) }}" class="btn btn-default btn-xs">ZIP</a>
<a href="{{ path('archive', {repo: repo, branch: branch, format: 'tar'}) }}" class="btn btn-default btn-xs">TAR</a>

You can remove (or comment out like I did) the two lines in: themes/bootstrap3/twig/tree.twig

![gitlist](https://cloud.githubusercontent.com/assets/1300195/11149467/89ad89fe-89e8-11e5-9658-9db449e0f607.PNG)

**Comment by georgesuba** [comment]
Hi guys, did you fixed? I modified whole theme and fixed those buttons also code views are now displaying properly..

**Comment by alehaa** [comment]
In `v0.6.0` this seems to be fixed.

**Comment by georgesuba** [comment]
@alehaa hi, i forgot to close that issue, I've fixed in bootstrap theme this on my own about same day ive created this issue, also fixed blob displaying etc.. basically made it fully working for my self however I need it something more....so I am not using gitlist any more. Thanks.

**Comment by alehaa** [comment]
Sorry to hear you're not using GitList anymore, but thanks for fixing the issue! ;)
