### ISSUE TITLE
Repositories on Newtwork Device on Windows

### ISSUE THREAD

**Issue by RrOoSsSsOo** [klaussilveira/gitlist#636]
There is a problem in `config.ini` for the repositories on Newtwork Device on Windows, i.e. `\\192.168.1.x\html\repo` or even for a _mapped_ remote folders like `Z:\repo`... gitlist reported 

**Please, edit the config file and provide your repositories directory** 

or 

**One or more of the supplied repository paths appears to be wrong. Please, check the config file** (for multiple repositories)

**Comment by JBlond** [comment]
if you installed apache or nginx as a service then apache / nginx can't map anything from the network. You need to run the service with a different local windows account.

**Comment by MinchinWeb** [comment]
Basically the 'user' Windows runs the webserver on doesn't (by default) load network shares, and so doesn't have access to them :(
