### ISSUE TITLE
The CI link in the website topbar is wrong

### ISSUE THREAD

**Issue by stof** [klaussilveira/gitlist#637]
It points to http://ci.gitlist.org:8080 which does not work.

**Comment by LanceSandino** [comment]
I don't think it's wrong, I just think it's down.

There have been no updates to this repo since Sept.

**Comment by stof** [comment]
well, the CI seems to use Travis. Is there another CI server too ?

**Comment by klaussilveira** [comment]
We used to have a Jenkins setup, but Travis is cheaper than having to maintain AWS stuff just for a small CI.

**Comment by stof** [comment]
That's fine with me, but then you should remove the link in the website topbar (or make it go to Travis)
