### ISSUE TITLE
Where are the colours? (C Syntax highlighting deviates from CodeMirror demo)

### ISSUE THREAD

**Issue by camilstaps** [klaussilveira/gitlist#638]
Why is it that e.g. http://gitlist-khornberg.rhcloud.com/git/blob/master/abspath.c is little colourful while it is very colourful when I copy the code to the CodeMirror demo on https://codemirror.net/mode/clike/index.html? 

Is there a way to get more colours? The syntax highlighting is little helpful to me at the moment, I'd like to see more colours.

**Comment by klaussilveira** [comment]
Probably we're running on an older version of CodeMirror. Marking this as bug!

**Comment by camilstaps** [comment]
I cannot reproduce this any more, probably it has been fixed.
