### ISSUE TITLE
I installed it but get a blank page

### ISSUE THREAD

**Issue by deavmi** [klaussilveira/gitlist#641]
When I visit the directory holding my `gitlist` install I get presented with a blank page. I followed the install steps presented as text on that page.

**Comment by deavmi** [comment]
I have set permissions and all.

**Comment by deavmi** [comment]
Do I have to install to `/var/www/gitlist`? As I chose a different directory.

**Comment by SkeletonEye** [comment]
A blank page may be result of a 500 Internal Server Error. You could check the server's log for information about what went wrong. In case of a php-error, you may look what file/line caused the error and this may help you finding out what you did wrong.
