### ISSUE TITLE
New theme with Bootstrap 4

### ISSUE THREAD

**Issue by ruby232** [klaussilveira/gitlist#647]
I created the new theme [gatys](https://github.com/ruby232/gatys)

**Comment by PerfectSlayer** [comment]
Can you share a screen ?

There is a typo in your Github project description: 
> Theme for gitlist, wiht Bootatrap 4, Saas and Angular Js 
I guess you mean "with".

**Comment by ruby232** [comment]
@PerfectSlayer Done

**Comment by klaussilveira** [comment]
Very nice. Feel free to make a PR with it!
