### ISSUE TITLE
Network graph broken. Can only view master.

### ISSUE THREAD

**Issue by milieu** [klaussilveira/gitlist#649]
Visiting a url like `https://some.host.server/project.git/network?branch=not-master` only shows the master branch, despite explicitly switching to another branch before viewing the network "graph".

Being able to view a full network graph of multiple branches would be ideal.

**Comment by Boehrsi** [comment]
> Being able to view a full network graph of multiple branches would be ideal.

That would be really awesome. +1 for that!

**Comment by alehaa** [comment]
#702 has been merged.
