### ISSUE TITLE
branch name limit to 40 characters

### ISSUE THREAD

**Issue by mahanmp** [klaussilveira/gitlist#650]
when a branch name exceeds with 40 characters it returns the following error

Oops! fatal: ambiguous argument 'abcdefghijklmpnopqrstuvwxyzabcdefghijklm': unknown revision or path not in the working tree. Use '--' to separate paths from revisions

**Comment by amdei** [comment]
Yes, 40 characters is not enough for a branch name.
Hit the same issue.

**Comment by myfreescalewebpage** [comment]
Probably exactly the same cause as #697. Need to check if the correction I have proposed is correcting this issue also.
