### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by jniggemann** [klaussilveira/gitlist#654]
http://gitlist.org/ has a blue button saying "Latest stable (0.5.0)" and links to https://s3.amazonaws.com/gitlist/gitlist-0.5.0.tar.gz.
Having installed from this file, the version shows "0.4.0".

**Comment by joshburt** [comment]
I've confirmed this same issue.  

The version is with the .\themes\default\twig\footer.twig file.  The "latest" 0.5.0 release indicates it's version 0.4.0.

**Comment by dkozel** [comment]
The issue was fixed in https://github.com/klaussilveira/gitlist/commit/e70cb0ff7892ae2c1046b8656804baf1d8929bfd but that was after the 0.5.0 release so you have to build from source to get the change.

Issue https://github.com/klaussilveira/gitlist/issues/617 talks about this as well.

**Comment by alehaa** [comment]
As there's already a [v6.0.0 release](https://github.com/klaussilveira/gitlist/releases/tag/0.6.0) I don't think there will be a new tarball for `v5.0.0`.
