### ISSUE TITLE
#feature Detect issue tracker issue ids and provide links to issue tracker

### ISSUE THREAD

**Issue by gene-pavlovsky** [klaussilveira/gitlist#655]
It would be nice if issue ids in commit message and body were detected and transformed to links to the issue tracker.
E.g. the way it works in TortoiseGit (`Settings > Hook Scripts > Issue Tracker Config`)
There's two regexps, first detects mentions of one or more issues, the second extracts issue ids from the matching strings.

```
\b([Ff]eatures?|[Bb]ugs?|[Ii]ssues?|[Tt]ickets?|[Tt]asks?|[Ii]mplement(ed|s)|[Ff]ix(ed|es)|[Cc]los(ed|es))(\s+|:\s*)(#\d+((\s*,\s*|\s+and\s+|\s+)#\d+)*)\b
\d+
```

Another setting specifies the Issue Tracker URL template
`http://dev.example.com/kanboard/?controller=task&action=show&task_id=%BUGID%`

**Comment by andreixk** [comment]
+1
