### ISSUE TITLE
Allow relative image paths in markdown files (contextual README)

### ISSUE THREAD

**Issue by DrChr** [klaussilveira/gitlist#659]
I'd like to suggest that relative linking to embedded images should work in README.md:s.

I tested using gitlist v0.4.0 (via a docker container with gilist), so please let me know if this should already work in 0.5.0.  When I've embedded an image in a markdown file using relative link, the image isn't shown. See below for example of the markup, for which the resulting URL becomes `http://192.168.0.100:8888/test/tree/master/someSubfolder/a_photo.jpg`. I'm guessing a correct URL here could be `http://192.168.0.100:8888/test/raw/master/someSubfolder/a_photo.jpg`.

By looking at the HTML in a browser debugger I saw that showdown.js is used to convert markdown to HTML, so perhaps a pre-processing stage could be used on relative image URLs in the markdown to automatically prepend the relative path with something like "/<repo-name>/raw/<branch>/<path>/"?

```
Should be an image below
![Some illustration](a_photo.jpg)
Is there an image above?
```

/Christian

**Comment by robwiss** [comment]
I wrote a patch for showdown.js to do this, probably not the best way to do it but it works

https://gist.github.com/robwiss/34f7780737351554558659c107360d53

**Comment by DrChr** [comment]
I gave up on using markdown, so I think I it's unlikely I will be testing this.

Note: Using markdown was frustrating and I now mainly do the corresponding task using Emacs' org-mode, with which I'm very happy. The markdown syntax differs to much to other markups (e.g. our wiki), resulting in to much tedious correction of minor errors. Further, the markup wasn't powerful enough in a for me significant number of cases.

**Comment by alehaa** [comment]
As mentioned in #866, the "preprocessed path" needs to be contextual depending on where the markdown page is rendered. E.g. the root's `README.md` is embedded in the repository's index page, while explicitly opening the same file has a different path.
