### ISSUE TITLE
Found two issues when installing gitlist

### ISSUE THREAD

**Issue by ghost** [klaussilveira/gitlist#660]
Hi Klaus,

it took me some time to figure out, that in the config file `path/to/repo` must not be a softlink. The error message, when `isdir($repository)` fails should be more clear about that.

But when I finally fixed that, I still got not fully working, as all the static stuff required to display the pages correctly and supply page functionality resulted into a 404 error. At this point I should say that I chose lighttpd as the web server. So it took even more time to figure out that not `www/gitlist/` but `www/gitlist/src/GitList/` is considered root. My workaround has been to add a rewrite rule to lighttpd.config. Now everything seems to be fine.

I suggest mentioning this issues in the `install.md`. When google-ing for help I found quite some people running into the same problems.

Cheers, Klaas

**Comment by siburny** [comment]
I just stepped into the "static" trap as well. It would best to add some kind cacheing that uses "cache" variable from config
