### ISSUE TITLE
Error make Kamailio with MySQL as Database

### ISSUE THREAD

**Issue by duybkict** [klaussilveira/gitlist#661]
$ sudo /usr/local/sbin/kamdbctl create
MySQL password for root: 
INFO: test server charset
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
INFO: creating database kamailio ...
mysql: [Warning] Using a password on the command line interface can be insecure.
INFO: granting privileges to database kamailio ...
mysql: [Warning] Using a password on the command line interface can be insecure.
INFO: creating standard tables into kamailio ...
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1101 (42000) at line 1: BLOB, TEXT, GEOMETRY or JSON column 'a_rr' can't have a default value
ERROR: Creating core tables failed at topos!

**Comment by DannyvdSluijs** [comment]
@duybkict Doesn't feel like anything related to the project, are you sure it was reported accordingly.

**Comment by alonsolai** [comment]
When I was installing the kamailo, I also stop by the error. I think this is an easy issue. Why no guys reply?

**Comment by Pauldic** [comment]
I got this error too

MySQL password for root: 
INFO: test server charset
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
INFO: creating database my_db_name ...
mysql: [Warning] Using a password on the command line interface can be insecure.
INFO: granting privileges to database my_db_name ...
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
INFO: creating standard tables into my_db_name ...
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1101 (42000) at line 1: BLOB, TEXT, GEOMETRY or JSON column 'a_rr' can't have a default value
ERROR: Creating core tables failed at topos!

**Comment by rustc-org** [comment]
same error on mac os
Enter character set name: 
latin1
\E[37;33mINFO: creating database kamailio ...
mysql: [Warning] Using a password on the command line interface can be insecure.
\E[37;33mINFO: granting privileges to database kamailio ...
mysql: [Warning] Using a password on the command line interface can be insecure.
\E[37;33mINFO: creating standard tables into kamailio ...
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1101 (42000) at line 1: BLOB, TEXT, GEOMETRY or JSON column 'a_rr' can't have a default value
\E[37;31mERROR: Creating core tables failed at topos!

**Comment by Pauldic** [comment]
I was able to solve this issue. Critical look at the error indicates there is an attempt to set default value for column '**a_rr**' which is of type either BLOB, TEXT, GEOMETRY or JSON. 

Hence, I was able to locate 'a_rr' and others in `/PATH/TO/kamailio-4.4.3/utils/kamctl/mysql/topos-create.sql` using command below:

`grep -r 'TEXT' /PATH/TO/kamailio-4.4.3/utils/kamctl/mysql/`

Observe:
`x_via MEDIUMTEXT DEFAULT '' NOT NULL,
 x_via CLOB DEFAULT '',
x_via TEXT DEFAULT '' NOT NULL,
x_via MEDIUMTEXT DEFAULT '' NOT NULL,`

and delete all occurrences  DEFAULT '' for columns of type BLOB, TEXT, CLOB, GEOMETRY, MEDIUMTEXT or JSON.

Once your are done editting run

`make clean && make proper`

and restart your installation process, the error will disappear

**Comment by rustc-org** [comment]
I solve it:
vim /usr/local/etc/my.cnf
[client]
port = 3306
socket = /tmp/mysql.sock
default-character-set = utf8

[mysqld]
collation-server = utf8_unicode_ci
character-set-server = utf8
init-connect ='SET NAMES utf8'
max_allowed_packet = 64M
bind-address = 127.0.0.1
port = 3306
socket = /tmp/mysql.sock
innodb_file_per_table=1
sql_mode=NO_ENGINE_SUBSTITUTION

[mysqld_safe]
timezone = '+0:00'

and mysql.server restart

**Comment by Pauldic** [comment]
Hi @rustc-org you might like to read [copied](http://dba.stackexchange.com/questions/143124/mysql2error-blob-text-column-cant-have-a-default-value) statement below:

>  
    BLOB, TEXT, GEOMETRY, and JSON columns cannot be assigned a default value.

    http://dev.mysql.com/doc/refman/5.7/en/data-type-defaults.html

What you are in essence asking -- without realizing it, presumably -- is how to force MySQL to revert to its old, incorrect behavior of ignoring your incorrect table definition and pretending that you really said ALTER TABLE items ADD description text NOT NULL but with the default value missing because that is the only alternative. So you are left with a nonsensical table definition.

The new, correct behavior is indeed tied to the new recommended @@SQL_MODE defaults. You're going to make trouble for yourself it your preferred solution is to unfix the server, rather than unbreak your table definition.

**Comment by rustc-org** [comment]
@Pauldic You are right! It's a temporary practice, I need a sip server on my mac to debug my iOS sip client in a hurry，Thank you!
