### ISSUE TITLE
remove link to gitlist.org

### ISSUE THREAD

**Issue by DavidBruchmann** [klaussilveira/gitlist#668]
In the file README.md in root-directory the site gitlist.org ist still mentioned. But the domain is parked or somehow else inactive.
So remove the link and if a replacement is available that would be great.

**Comment by dkozel** [comment]
Hell David. gitlist.org works correctly for me. Try checking your DNS settings.

**Comment by DannyvdSluijs** [comment]
@David in the Netherlands it works fine for me aswell.

**Comment by DavidBruchmann** [comment]
Fine, don't know what went wrong but now I can see it too and it looks like being correct.
Before I saw a page that the domain was expired.
Ok, issue can be closed ;-)
