### ISSUE TITLE
Use libravatar

### ISSUE THREAD

**Issue by afranke** [klaussilveira/gitlist#669]
In the spirit of decentralization, just like people may choose to use GitList rather than Github, libravatar offers an alternative to gravatar.

**Comment by netbrothers-tr** [comment]
I support the idea! As I see it this [should be possible with the upcoming release](https://github.com/klaussilveira/gitlist/commit/73c362fa5200dc0e3d92c17a867f1db6a282925f) but I didn't try it because we're running 0.5.0.
