### ISSUE TITLE
separated repos depending on customer

### ISSUE THREAD

**Issue by DavidBruchmann** [klaussilveira/gitlist#671]
The following text can be added to the manual if desired:

having installed gitlist in the beginning I just had one directory with all the repositories. So each customer can see all repos.
I changed the structure than like this:

```
Repositories
    customer_1_repos
        repo_1
        repo_2
    customer_2_repos
        repo_3
        repo_4
```

This is working already in general but is still not separating the customers' access.
In the web-directory I made the following structure:

```
gitlist-x-x-x (original download with version number, no config-file)
gitlist  (symlink to gitlist-x-x-x, no config-file)
customer_1
    src    (symlink to ../gitlist/src)
    themes    (symlink to ../gitlist/themes)
    vendor    (symlink to ../gitlist/vendor)
    boot.php    (symlink to ../gitlist/boot.php)
    index.php    (symlink to ../gitlist/index.php)
    cache   (dir)
    config.ini
    .htaccess
customer_2
    src    (symlink to ../gitlist/src)
    themes    (symlink to ../gitlist/themes)
    vendor    (symlink to ../gitlist/vendor)
    boot.php    (symlink to ../gitlist/boot.php)
    index.php    (symlink to ../gitlist/index.php)
    cache   (dir)
    config.ini
    .htaccess
```

This is working in general too but leads to some errors because files are not found and ajax-calls are not working.
At this point the only problem then is the `.htaccess` file.
I never spent much time on changing it, so my solution might be much improvable but it's working:

```
<IfModule mod_rewrite.c>
    Options -MultiViews +SymLinksIfOwnerMatch

    RewriteEngine On
    RewriteBase /path/to/repos/for/customer/

    # IMPORTANT: This rule has to be the very first RewriteCond in order to work!
    # RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    # Network-View isnt working if 'json' is added in the following list:
    RewriteRule ^(.*)\.(php|js|css|png|jpg|gif|gzip|md|yaml|dist|xml|eot|svg|ttf|woff)$ $1.$2 [L]

    # Access block for folders
    RewriteRule (themes|src|vendor)/.*\.(?:.*)$ - [F]

    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php?$1 [L,NC]
</IfModule>
<Files config.ini>
    order allow,deny
    deny from all
</Files>
```

If the `.htaccess` still makes problems try to comment the 2nd line like this:

```
#    Options -MultiViews +SymLinksIfOwnerMatch
```

**Comment by Hologos** [comment]
I integrated gitlist with gitolite so only repositories readable to the authentificated user is shown (and accessable). Check [my patch file](https://github.com/klaussilveira/gitlist/files/465833/support-for-gitolite.txt) to see all necessary changes. Just change the line where you get the repolist and you are good to go. Also, you need to setup some kind of authentification (hence $_SERVER['PHP_AUTH_USER']). I used Apache authentification integrated with our Active Directory.

**Comment by DavidBruchmann** [comment]
Sorry never remarked your post earlier.
Thanks for the reply, will check it out ;-)

**Comment by Hologos** [comment]
@DavidBruchmann I made a PR which integrates GitList with gitolite, it's more polished that what I sent you earlier. It wasn't merged because some part of code isn't indented properly (spaces), I'll correct that today.

**Comment by alehaa** [comment]
@DavidBruchmann I think another approach would be an implementation as described #521 combined with access control.
