### ISSUE TITLE
Travis CI failing / errored

### ISSUE THREAD

**Issue by matkoniecz** [klaussilveira/gitlist#672]
https://github.com/klaussilveira/gitlist#gitlist-an-elegant-git-repository-viewer

**Comment by AlphaJuliettOmega** [comment]
?????

**Comment by alehaa** [comment]
@matkoniecz can you provide some additional information to reproduce this issue?

**Comment by matkoniecz** [comment]
According to readme of this project build is ending in error (link in original report links to this badge).

Either it is really failing or readme displays wrong status.

**Comment by alehaa** [comment]
Now I understand the issue ... Travis CI builds are failing at the moment due some errors while installing the dependencies.

**Comment by alehaa** [comment]
Closed in favour of #745.
