### ISSUE TITLE
Class 'GitList\Controller\TreeGraphController' not found

### ISSUE THREAD

**Issue by naeemshah** [klaussilveira/gitlist#677]
i getting the following error 

Fatal error: Class 'GitList\Controller\TreeGraphController' not found in /var/www/html/boot.php on line 12

**Comment by ank91** [comment]
edit ```boot.php``` like:

```php
$app->mount('', new GitList\Controller\TreeController());
```

Seems like class name has changed.

**Comment by naeemshah** [comment]
Thanks @ank91  solved  it by moving TreeController.php to other src/Controller directory

**Comment by Hologos** [comment]
I suggest creating a symlink
`cd <project_root>/srcln -s ../GitList/Controller/TreeGraphController.php TreeGraphController.php`

**Comment by ericcotelnu** [comment]
I moved the file. I suspect it didn't get updated yet as to where to find this file and its classes. I dunno how that sort of thing works, but IME and TMK it just looks in various subdirs until it finds it. But then I see the error we get from this, and it makes me think my knowledge is faulty ;).

**Comment by marceldeglau** [comment]
This issue can be closed. It was fixed by me in pull request #682 (already merged to master).

Stay awesome guys. :-)
