### ISSUE TITLE
Wrong content of archive on the homepage

### ISSUE THREAD

**Issue by Hologos** [klaussilveira/gitlist#679]
I found out that the content of downloadable archive on http://gitlist.org even though it says "Latest stable (0.5.0)" and points to https://s3.amazonaws.com/gitlist/gitlist-0.5.0.tar.gz contains files from version 0.4. It even says that in the footer (Powered by GitList 0.4.0). The same applies for "Development build (master)".

**Comment by dkozel** [comment]
Hello Hologos,

This is a bug which has been fixed since the last stable release.
https://github.com/klaussilveira/gitlist/issues/617
https://github.com/klaussilveira/gitlist/issues/654

**Comment by Hologos** [comment]
Silly me, didn't use search function. I already built from the source code. You can close this issue.
