### ISSUE TITLE
Ability to add new repository

### ISSUE THREAD

**Issue by kafermeister** [klaussilveira/gitlist#680]
Hi,

Currently in our company we use git and gitlist hosted from a OS X Server host.  Any new repositories I currently create for people via SSH (since using SSH and creating bare repositories etc. is additional steps we don't want to burden most of our primarily Windows devs with).

Having a "Create New Repository" option within gitlist (and therefore more more intuitive) would be a great feature!

Thanks
Peter

**Comment by Hologos** [comment]
Repositories should not be writeable to the user which apache is running under. So it would be rather tricky to implement this feature (= compiling apache with suexec, writing suexec wrapper script).

**Comment by DannyvdSluijs** [comment]
@Hologos this could be solved with use of a queue with some listeners for their respective task running as the correct user

However this goes beyond the rationale of what the Gitlist should be. As per the core maintainer's opinion it shall be only an git repo viewer

**Comment by alehaa** [comment]
As @DannyvdSluijs already explained, GitList is - and should be - a repository viewer only. 

However, as Silex is quite extensible, you may add a custom provider for your needs and define a new route for the "create repository" action and add a link to this endpoint in the template file.
