### ISSUE TITLE
Unable to generate a URL for the named route "treegraph" as such route does not exist.

### ISSUE THREAD

**Issue by barbuslex** [klaussilveira/gitlist#681]
Hi,

An error occurs when i click on a repository in gitlist : 

> Oops! An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "treegraph" as such route does not exist.") in "menu.twig" at line 6.

![image](https://cloud.githubusercontent.com/assets/113057/18125682/d014608c-6f77-11e6-8faa-87906e4172bf.png)

Have you an idea ?

Thanks

**Comment by Hologos** [comment]
Check this [pull request](https://github.com/klaussilveira/gitlist/pull/676/files). I think it might solve your problem.
