### ISSUE TITLE
The URI you submitted has disallowed characters.

### ISSUE THREAD

**Issue by RobbiNespu** [klaussilveira/gitlist#684]
I have problem with my gitlist.. my repo are located at `/var/www/` and i store gitlist inside it which located at `/var/www/gitlist/`
here is my config file : 

```
[git]
client = '/usr/bin/git' ; Your git executable path
default_branch = 'master' ; Default branch when HEAD is detached
repositories[] = '/var/www/' ; Path to your repositories
                                           ; If you wish to add more repositories, just add a new line

; WINDOWS USERS
;client = '"C:\Program Files (x86)\Git\bin\git.exe"' ; Your git executable path
;repositories[] = 'C:\Path\to\Repos\' ; Path to your repositories

; You can hide repositories from GitList, just copy this for each repository you want to hide
; hidden[] = '/home/git/repositories/BetaTest'

[app]
debug = true
cache = true
theme = "default"

; If you need to specify custom filetypes for certain extensions, do this here
[filetypes]
; extension = type
; dist = xml

; If you need to set file types as binary or not, do this here
[binary_filetypes]
; extension = true
; svh = false
; map = true

; set the timezone
[date]
; timezone = UTC
; format = 'd/m/Y H:i:s'

```

The main page are working as below
[![Capture.jpg](https://s12.postimg.org/q1q65tpod/Capture.jpg)](https://postimg.org/image/v0dokcth5/)

and this happen when I click the repo
[![c.jpg](https://s11.postimg.org/73pjtybcz/image.jpg)](https://postimg.org/image/i3ar5k1rz/)}

I access it using subdomain eg : 
sub.domain.com <-- my git project
sub.domain.com/gitlist  <-- my gitlist

**Comment by DavidBruchmann** [comment]
The important part you made impossible to read: the domain. I had this error when i used a subdomain with underscore. So assure that the domainparts respect the standards.
