### ISSUE TITLE
confusing behavior in gitlist directory (no repo path given)

### ISSUE THREAD

**Issue by kotoroshinoto** [klaussilveira/gitlist#694]
if I input the URL: http://localhost:8080/gitlist/

I get a pink error  message: 
```
Oops! An exception has been thrown during the rendering of a template ("Parameter "repo" for route "repository" must match "AngabladeDownloaders|dissertation|derp\.git|Prospectus|Memes" ("derp.git" given) to generate a corresponding URL.") in "index.twig" at line 16
```

If I put in the url to point it at a repository it behaves properly, but I notice that clicking the upper left "GitList" text links back to this base URL, so I assume it is supposed to display something like a listing of available repositories.

I'm not sure what is wrong.

**Comment by Hologos** [comment]
Did you change the RewriteBase path in .htaccess?

**Comment by kotoroshinoto** [comment]
I changed it to the path where gitlist sits relative to the domain name (so its just /gitlist/).

**Comment by kotoroshinoto** [comment]
if I hadn't done that, I don't think the gitlist functions would work on defined repository paths though, and it was. Its only the base URL that doesn't work.

**Comment by Hologos** [comment]
I'll install gitlist according to your setup and will check it out.

**Comment by Hologos** [comment]
I cannot reproduce this behavious. Can you post your .htaccess here?
