### ISSUE TITLE
Provide an example .htaccess file in version control as with config.ini

### ISSUE THREAD

**Issue by netbrothers-tr** [klaussilveira/gitlist#699]
I'd propose to remove the `.htaccess` file from version control since it is likely to be customized in some installations. Just as with the `config.ini` I think there should be an example file in the repository from which the user can make his own original file. Pros and cons anyone?

**Comment by DavidBruchmann** [comment]
Having a .htaccess that is working in most cases is not bad, I don't see a reason to remove it ...
I have adjusted versions but think it's useful even as base for own versions.

**Comment by netbrothers-tr** [comment]
Hi @DavidBruchmann, thanks for your comment! The main reason for which I think it's useful is if you want to run a cloned version and want to stay able to pull updates at any time. At least, that's what I'm trying to do at the moment. When the file isn't under version control, then you don't have to worry about it being overwritten or running into conflicts when pulling. Albeit this affects a smaller number of people, you still have to consider other reasons wanting to place this web server configuration in a different place. Some examples:

- not using Apache but nginx (where users are discouraged to use `.htaccess` for performance reasons)
- using neither Apache nor nginx but yet another web server
- using a custom htaccess file name for security reasons

Of course, for most users (Apache standard configuration) the downside is, that they will have to adjust two files (`config.ini` and `.htaccess`) instead of just one. But since they already have to create at least one file, the `config.ini`, IMHO it shouldn't be asked too much, if they also had to do this `cp .htaccess-example .htaccess`.

Either way it's just a proposal! :wink:

**Comment by DavidBruchmann** [comment]
As long there is a .htaccess file that can be easily activated I think that's ok - just the readme and manual had to be adjusted too, don't know if you considered that in your PR.

**Comment by netbrothers-tr** [comment]
It's not a PR yet. I just referenced this issue when committing. Didn't know Github would show those here in the thread. I'm quiet new to the workflow after all. But I'll try to set up a complete PR (with adjusted docs) and report back here in this thread.
