### ISSUE TITLE
cloning via HTTP not work for nginx(not tested under Apache)

### ISSUE THREAD

**Issue by Ecareyu** [klaussilveira/gitlist#701]
No matter how I set up, when I want to go through the http pull my code, will be an error

`
fatal: repository 'https://xxx@git.xxx.com/repo/sample.git/' not found
`
I don't know how to set "url_subdir"

I set up a virtual directory to point to my repository root, but still no use.
```
...
location /repo/ {
         alias /home/git/repo/;
}
...
```

Can somebody tell me how to set it?

**Comment by aligator** [comment]
to use git whith http you need this:
https://gist.github.com/massar/9399764
`location ~ /git(/.*) {
                # Set chunks to unlimited, as the body's can be huge
                client_max_body_size                    0;

                fastcgi_param   SCRIPT_FILENAME         /usr/lib/git-core/git-http-backend;
                include         fastcgi_params;
                fastcgi_param   GIT_HTTP_EXPORT_ALL     "";
                fastcgi_param   GIT_PROJECT_ROOT        /srv/git;
                fastcgi_param   PATH_INFO               $1;

                # Forward REMOTE_USER as we want to know when we are authenticated
                fastcgi_param   REMOTE_USER             $remote_user;
                fastcgi_pass    unix:/var/run/fcgiwrap.socket;
        }
`

**Comment by Ecareyu** [comment]
@aligator thx,it's working!
