### ISSUE TITLE
get('date', 'timezone')) error

### ISSUE THREAD

**Issue by xav12358** [klaussilveira/gitlist#705]
Hello,

I just install gitlist with apache2 and when I launch the localhost/gitlist the page contain that:
`get('date', 'timezone')) { date_default_timezone_set($config->get('date', 'timezone')); } $app = require 'boot.php'; $app->run(); `

Is it a compatible problem with php? I have install php5.0

**Comment by kellsaro** [comment]
I had the same issue. I was able to solve it this way:

1- Be sure you have php7 correctly installed and with the apache2 module properly enabled/configured. I use ubuntu, for me it was enough with:

sudo apt-get -y install php7.0 libapache2-mod-php7.0

2- Be sure your gitlist folder has the right permisions for the web user. I use apache2(.4):

sudo chown -R www-data:www-data <path-to-gitlist>

3- Also check in your gitlist config.ini file that you are pointing to the folder containing the git repos, not to the git repos:

repositories[]= '/home/user/repositories'

4- Restart de apache service:

systemctl restart apache2

I hope this helps.
