### ISSUE TITLE
bug/feature request

### ISSUE THREAD

**Issue by josephRice** [klaussilveira/gitlist#707]
the ssh clone feature in master, when evaluating I noticed that the `git clone git@some_server:/project.git` is not correct, as that you should have the full path of the repo. So for example If i have my git repo's under `/home/someuser/prj/gitrepos/` and a `.git` project called `myproject.git` under that directory the clone link should be `git clone username@some_server:/home/someuser/prj/gitrepos/myproject.git`

I've seen some cases the main git repository could be `/var/gitrepo/` or `/GITROOT/`  with companies that I have worked with. So we really should have a way to specify the base git repo as a clone option, or be smart enough to pull in the repo under the git configuration settings.

**Comment by Hologos** [comment]
Sadly, it is "known issue" as I mentioned in PR #688. Either #689 or #704 has to be merged. I'm not able to contact @klaussilveira. The easiest way for you is to merge @peterverraedt 's PR #704 because mine contains gitolite integration (which you don't need currently).

**Comment by robwiss** [comment]
I feel silly asking this but after setting `show_ssh_remote = true ;` in my `config.ini` I don't see a ssh clone url anywhere at all. Is there something I've missed?

**Comment by Hologos** [comment]
You should see additional button in repository view. Check screenshot in #688. It should work in both themes. Also don't forget to clear the cache (of set cache = false in config.ini).

**Comment by robwiss** [comment]
I tried #704 and #689 with no luck. I'm on a really old version of php (5.3.3 on CentOS 6), perhaps that has something to do with it. #704 seems to have no effect at all. Gitlist won't load if I install #689.

**Comment by Hologos** [comment]
Is there anything in error_log?

Instead of #689 try to apply [this patch only](https://github.com/Hologos/gitlist/commit/8dacca4490313305b901ae82589cdb60ab593951.patch).

**Comment by robwiss** [comment]
Here's a patch that fixes the issue for me.

https://gist.github.com/robwiss/78777fe1aefbdb8debf84dcbe618c14c
