### ISSUE TITLE
404

### ISSUE THREAD

**Issue by lluiscab** [klaussilveira/gitlist#713]
I'm trying to run the app on my raspberry pi 2 and I can't seem to make this work. I keep getting a 404 error when trying to see a repo. The refresh button does also not work. Apache error log shows no errors.

http://imgur.com/a/h8zC0

> <IfModule mod_rewrite.c>
>     Options -MultiViews +SymLinksIfOwnerMatch
> 
>     RewriteEngine On
>     RewriteBase /
> 
>     RewriteCond %{REQUEST_FILENAME} !-f
>     RewriteRule ^(.*)$ index.php/$1 [L,NC]
> </IfModule>
> <Files config.ini>
>     order allow,deny
>     deny from all
> </Files>

```
[git]
client = '/usr/bin/git' ; Your git executable path
default_branch = 'master' ; Default branch when HEAD is detached
repositories[] = '/home/git/repos/' ; Path to your repositories
                                           ; If you wish to add more repositories, just add a new line

; WINDOWS USERS
;client = '"C:\Program Files (x86)\Git\bin\git.exe"' ; Your git executable path
;repositories[] = 'C:\Path\to\Repos\' ; Path to your repositories

; You can hide repositories from GitList, just copy this for each repository you want to hide
; hidden[] = '/home/git/repositories/BetaTest'

[app]
debug = false
cache = true
theme = "default"

; If you need to specify custom filetypes for certain extensions, do this here
[filetypes]
; extension = type
; dist = xml

; If you need to set file types as binary or not, do this here
[binary_filetypes]
; extension = true
; svh = false
; map = true

; set the timezone
[date]
; timezone = UTC
; format = 'd/m/Y H:i:s'

```

**Comment by nblackburn** [comment]
You need to configure Apache correctly by adding `AllowOverride All` to your configuration.

**Comment by fonger900** [comment]
It doesn't even help..
