### ISSUE TITLE
Error with files with single quote in filename

### ISSUE THREAD

**Issue by MatteoBattilana** [klaussilveira/gitlist#714]
I got this error message when trying to open a file with single quote(') in the filename:
`Oops! fatal: Path 'testfile\\' testfile.txt' does not exist in 'master' `

Everything is ok with the normal files, this problem is also applied to the folder with this error:
`Oops! fatal: Not a valid object name master:folder \'2015 - 2016/ `

**Comment by netbrothers-tr** [comment]
Hi @MatteoBattilana , I'm curious: on which platform (Linux, Windows server) are you?

**Comment by MatteoBattilana** [comment]
I'm on Debian

**Comment by netbrothers-tr** [comment]
I can confirm the error. I created a fresh file with the name `Testfile' Testfile.txt` and GitList showed the same error to me.

**Comment by netbrothers-tr** [comment]
Hey @MatteoBattilana , I think it's best to report this issue at [Gitter](https://github.com/klaussilveira/gitter).
