### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by FalcoSuessgott** [klaussilveira/gitlist#716]
I'm really sorry for disturbing you guys, which some lame installation problems, but I just can't figure it out, how to get GitList working.

The error message on my browser (Im accessing GitList from a remote IP btw) says:
`The requested URL /gitlist/ was not found on this server.`

what  I did so far:

```
apt-get install php apache2 git
cd /var/www/
mkdir gitlist
wget https://s3.amazonaws.com/gitlist/gitlist-0.5.0.tar.gz
tar xvzf gitlist
mkdir cache
chmod 777 cache
mv config.ini-example config.ini
* changed repositories[]= 'path/to/my/git directory/*
* changed RewriteBase to /var/www/gitlist * 
```

When I enter *IP-to-my-vps*/gitlist I receive the previoulsy mentioned error message, do you guys can help me, get this working? The error-log doesn't show anything. I declared my git-directory in my home-directory of my main user with  `git init`

**Comment by smacz42** [comment]
Have you configured apache or the `.htaccess` file at all?

**Comment by FalcoSuessgott** [comment]
currently the .htaccess file looks like this in /var/www/gitlist/
```
<IfModule mod_rewrite.c>
    Options -MultiViews +SymLinksIfOwnerMatch
    RewriteEngine On
    RewriteBase /var/www/gitlist/
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php/$1 [L,NC]
</IfModule>
<Files config.ini>
    order allow,deny
    deny from all
</Files>
```

**Comment by smacz42** [comment]
Take a look at your `RewriteBase`. That is not talking about the filesystem, it's talking about the URL - so maybe try:

```
RewriteBase /gitlist/
```

**Comment by FalcoSuessgott** [comment]
changed it. But it still says that page could not be found.
Any other ideas?:(

**Comment by ranaivomahaleo** [comment]
Hi,
I think that this problem is related to apache virtual host configuration.
Try to find in your apache virtual host configuration something like:

<Directory ...>
AllowOverride None
</Directory>

Change it to
<Directory ...>
AllowOverride all
</Directory>

**Comment by FalcoSuessgott** [comment]
Hey,
I can access my own written webpages. So the apache in general is accessable. 
So the line you mentioned is already like your approach.
I believe I won't get this working soon :(

**Comment by DavidBruchmann** [comment]
if your (sub)domain is already mapped on the directory /var/www/gitlist/ then the RewriteBase is just / and not /gitlist/.

**Comment by FalcoSuessgott** [comment]
Didnt't work.
Is it possible that It does not work, because I have PHP 7.0 installed, and gitlist is only supported for PHP5.3 ?

**Comment by DavidBruchmann** [comment]
Yes, I don't know about the upwards-compatibility but this is probably the reason.

**Comment by FalcoSuessgott** [comment]
Okay, damn I hate it to remove packages, because I never remove them completly

**Comment by smacz42** [comment]
@FalcoSuessgott I can point you to a known-good apache config [here](https://github.com/smacz42/ansible-role-httpd/blob/master/templates/gitlist_ssl.conf.j2) with the variables defined [here](https://github.com/smacz42/ansible-role-httpd/blob/master/defaults/main.yml) OR overridden [here](https://github.com/smacz42/ansible-role-gitlist/blob/master/defaults/main.yml)

**Comment by FalcoSuessgott** [comment]
@smacz42 can you confirm, that gitlist for me probably does not work, because I have php7.0 installed ? Or does the version not matte?

**Comment by smacz42** [comment]
Here's a tip, if you are seeing errors in `/var/log/httpd/error_log`, then it's an apache setup problem. And i'm 98% sure that it's some error in your paths. What does your apache virtual host configuration look like? Sometimes the apache `DirectoryRoot` is `/var/www/html` instead of `var/www`. 

Also, you said that you could access your own webpages that you put on your server. Where did you put those?

------------------------------

Also, side note, when you do get this working, you're going to want to open up new repos with `git init --bare` instead of plain old `git init`. [source](https://www.atlassian.com/git/tutorials/setting-up-a-repository)

**Comment by FalcoSuessgott** [comment]
Hey,

virtualhost config:
```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <Directory "/var/www/html">
        AuthType Basic
        AuthName "Restricted Content"
        AuthUserFile /etc/apache2/.htpasswd
        Require valid-user
        </Directory>
</VirtualHost>
```
apache2 conf:
```
<Directory />
        Options FollowSymLinks
        AllowOverride None
        Require all denied
</Directory>

<Directory /usr/share>
        AllowOverride None
        Require all granted
</Directory>

<Directory /var/www/>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
```
config.ini:
```
client = '/usr/bin/git' ; Your git executable path
default_branch = 'master' ; Default branch when HEAD is detached
repositories[] = '/home/USER/GIT/' ; Path to your repositories
                                           ; If you wish to add more repositories, just add a new line
...
[app]
debug = false
cache = true
theme = "default"
#baseurl = 'http://localhost/gitlist'
....
```
With those configs it says: 
```
Not Found

The requested URL /index.php/ was not found on this server.
```
When I point the URL in my webbrowser to:` IP/gitlist/index.php` I actually download the index-file.
The errorlog doesn't show anything when I enter the URL.
My websites are stored under `/var/www/html/ `I can access them.

Guess either it has something to do with missing or wrong rights (cache folder on 777). Or missing packages.

**Comment by tobi-the-fraggel** [comment]
Has there been any update on this problem?
I am wondering about having a similar issue but while running NginX + php7.0 on Ubuntu-16.04
I don't get the error messages described by the OP. When accessing the gitlist website I just get this message on my browser: '**Please, edit the config file and provide your repositories directory**'

Aside from changing the path to my repository config.ini is still in factory condition:
`[git]
client = '/usr/bin/git' ; Your git executable path
default_branch = 'master' ; Default branch when HEAD is detached
repositories[] = '/var/git/repositories/prbf2' ; Path to your repositories
                                           ; If you wish to add more repositories, just add a new line

; WINDOWS USERS
;client = '"C:\Program Files (x86)\Git\bin\git.exe"' ; Your git executable path
;repositories[] = 'C:\Path\to\Repos\' ; Path to your repositories

; You can hide repositories from GitList, just copy this for each repository you want to hide
; hidden[] = '/home/git/repositories/BetaTest'

[app]
debug = false
cache = true
theme = "default"

; If you need to specify custom filetypes for certain extensions, do this here
[filetypes]
; extension = type
; dist = xml

; If you need to set file types as binary or not, do this here
[binary_filetypes]
; extension = true
; svh = false
; map = true

; set the timezone
[date]
timezone = UTC
format = 'd/m/Y H:i:s'
`

I had gitlist running exactly as configured above on my Ubuntu-12.04 server. Just after migrating to Ubuntu-16.04 it stopped working. I reinstalled gitlist completely but to no avail. I suspected php7.0 and looked for other people having similar problems. That's how I ended up here. So @alehaa if you did discover more information about this issue, me and others might be happy to hear about it.

If you don't have further information. Can you recommend trying out the current repo version? It seems to support php7.0.
