### ISSUE TITLE
Does GitList provide support for serving Go repositories via go get?

### ISSUE THREAD

**Issue by mschaefer01** [klaussilveira/gitlist#717]
Can GitList be configured to support Go repositories?

The repo page should contain the `<meta>` tag inside the `<head>` tag:

`<meta name="go-import" content="example.org git https://code.org/r/p/exproj">`

See https://golang.org/cmd/go/ for documentation about providing the <meta> tag.

**Comment by netbrothers-tr** [comment]
IMHO the answer is no.

**Comment by alehaa** [comment]
I'm not familiar with Go, but I think this requires cloning via HTTP. GitList is just a repository viewer and thus doesn't provide any mechanism to clone the repository via HTTP. However, you may add the `<meta>` tag into the template file, pointing to a valid link to clone the repository.
