### ISSUE TITLE
Can't load repos with .git extension in the repo name

### ISSUE THREAD

**Issue by yorikw** [klaussilveira/gitlist#720]
I found that repo names with `.git` extension at the end won't load. 
The quick fix I made was in the `Client.php` file when building the repo names collection. 
Here is my fix: 

```
if (!$topLevel) {
  $repoName = $file->getPathInfo()->getFilename() . '/' . $this->getName($file->getFilename());
} else {
  $repoName = $this->getName($file->getFilename());
}

private function getName($str, $char = '.'){
   return substr($str, 0, strpos($str, $char));
}
```

I hope you'll fix this soon.
Thanks

**Comment by alehaa** [comment]
Fixed in cc1dc5af14e83dc7ca602694a1d2bfb7878d3aa8.
