### ISSUE TITLE
Gitlist repository search for commits only returning results in master branch

### ISSUE THREAD

**Issue by alexsim88** [klaussilveira/gitlist#728]
Hi,

Not sure if this is expected, but I recall previously I was able to search based on commit message in other repository other than Master.

However, now, it seems that my results are always only for master branch.

Please see below screenshot of what I mean

Searching on SR Branch

there is SR2017-0005 item in SR Branch
![image](https://user-images.githubusercontent.com/28618227/27011197-8bb43366-4ee9-11e7-813b-ce4c530939b6.png)

Searching it returns no results

![image](https://user-images.githubusercontent.com/28618227/27011208-b1caf4cc-4ee9-11e7-9423-c8b7fe5a0d48.png)

Now if I search for SR2016-0020 it will return me this instead of what is in the first screenshot

![image](https://user-images.githubusercontent.com/28618227/27011216-dc6669fa-4ee9-11e7-8634-87b27b87bb8a.png)

The above is actually a commit on Master Branch and not SR Branch. Is this expected? Hope to hear something because I seemed very sure I was able to search on my other branches previously. Thank you!

**Comment by PABourdin** [comment]
We plan to fix this problem inside gitlist-php/gitlist#7
