### ISSUE TITLE
release on gitlist.org not up-to date

### ISSUE THREAD

**Issue by flototh** [klaussilveira/gitlist#729]
the 'latest stable' build on gitlist.org does not seem to be up to date. The link and filename says 0.5.0, however the extracted files correspond to 0.4.0.

**Comment by DannyvdSluijs** [comment]
I believe what @p3x-robot is trying to say is that this repo (the official) is no longer maintained by the original developer. P3x is having a fork which is having active bug fixing.

**Comment by ardichoke** [comment]
Additionally, the extracted files are from 0.5.0, they just failed to update the version number in the theme files before release. I just went down the same rabbit hole myself.

**Comment by netbrothers-tr** [comment]
@ardichoke is right. The displayed version is 0.4.0 whereas the actually distributed version is 0.5.0. Also, I recommend switching to another solutions because of the non-activity of this project. @p3x-robot seems to be actively maintaining a fork at https://github.com/patrikx3/gitlist.

**Comment by flototh** [comment]
Thank you for the information. I will move to @p3x-robot's fork.
