### ISSUE TITLE
commits webpage shows 500 error

### ISSUE THREAD

**Issue by JanetChangB** [klaussilveira/gitlist#730]
We can see the directories ,files, and the contents of file already, but it shows 500 error if we click the commits or history button. It looks like there are something wrong if we would like to see the logs.

**Comment by netbrothers-tr** [comment]
Just an idea...

Do you experience this problem on every commit? I've experienced problems when commit messages contain non-standard characters, e.g. Unicode emojis. Are your commit messages often or mostly in a non-western language?

**Comment by JanetChangB** [comment]
Yes, every commit. We use english to commit logs. No emojis.

**Comment by daumiller** [comment]
I had the same issue. Inspecting apache's error log showed a missing ```SimpleXmlIterator``` php class.
Installing the ```php7.0-xml``` package and restarting the webserver fixed the issue for me.

**Comment by rodrigocostasensedia** [comment]
> I had the same issue. Inspecting apache's error log showed a missing `SimpleXmlIterator` php class.
> Installing the `php7.0-xml` package and restarting the webserver fixed the issue for me.

Thank you, @daumiller !!!!

**Comment by r-bhikhie** [comment]
This was the missing piece in my install as well!
Using version 1.0.2.

Can this please be mentioned in the troubleshooting steps? Together with how to detect this.
Thanks!
