### ISSUE TITLE
Error with Apache 2.4 - Primary script unknown

### ISSUE THREAD

**Issue by garyee** [klaussilveira/gitlist#733]
Hi,

I want to use gitlist on my Synology Diskstation.
I followed the installation instructions but ran into this fault:

```
2017-08-02T15:33:54+02:00 Server [Wed Aug 02 15:33:54.575323 2017] [proxy_fcgi:error] [pid 27803:tid 1379922976] [client 192.168.178.52:37851] AH01071: Got error 'Primary script unknown\n'
```

When I deleted the .htaccess I could see the repo list but when I wanted to see the files I got a 404 error.

My solution was to switch back to Apache 2.2

**Comment by alehaa** [comment]
@garyee Would be nice, if you could open an issue in the "new" repo as mentioned by @p3x-robot (see #725), so we can fix it in this fork.

**Comment by PABourdin** [comment]
I had a similar issue and have simply stopped using the .htaccess example file. Instead, I use a virtual host configuration file and made my changes there. All I needed to do was to append the gitlist base path and the Git repository base path to my "php_admin_value open_basedir" and to define a ScriptAlias and the Directory settings. Please note I use here the authentication via a htpasswd file, see attached example.
[apache-2.4_conf.txt](https://github.com/klaussilveira/gitlist/files/1194249/apache-2.4_conf.txt)

**Comment by klaussilveira** [comment]
The .htaccess file targeted Apache 2.2 only.
