### ISSUE TITLE
Tag names in URLS for commits

### ISSUE THREAD

**Issue by IvanUrwin** [klaussilveira/gitlist#735]
This is a wish-list thing rather than a bug.

I store my problem reports using a problem tracking system called "Trac".
I can write something like 

    fixed on version:project:1.2.3.4 by fix:project:987

and Trac will automatically create a hyperlink to URIs like ...

    http://mygitserver/gitlist/project.git/commits/v1.2.3.4
    **http://mygitserver/gitlist/project.git/commit/fix987/**

unfortunately the second does not work and I have to link to 

    http://mygitserver/gitlist/project.git/commits/fix987/

The difference is the letter S to change the word commit to the plural "commits".
For a link to the commit for a release I would like to see the list of features and fixes in the release and commits (plural) is fine.
For a link to the commit for a fix I would just like to see the code for the change and I would like the link ...

    http://mygitserver/gitlist/project.git/commits/fix987/

to function by interpreting the tag name fix987 and displaying the same contents as 

    http://mygitserver/gitlist/project.git/commit/6df61207c71c266aa9bd3cc67ae586ebde045a95

I realize that this is a feature request, not a bug fix, but I suspect it is a simple change since tag names already works for "commits" (with an S, plural).

**Comment by IvanUrwin** [comment]
I would like the link ...

    http://mygitserver/gitlist/project.git/commit/fix987/

to function by interpreting the tag name fix987 and displaying the same contents as

    http://mygitserver/gitlist/project.git/commit/6df61207c71c266aa9bd3cc67ae586ebde045a95

**Comment by alehaa** [comment]
@IvanUrwin This repo is afaik not developed anymore (see #725). However you may submit this issue in gitlist-php/gitlist, where new features can be implemented (if they're accepted).

**Comment by IvanUrwin** [comment]
I don't understand the last remark, but thanks for the reply about maintaining the repo and your enthusiasm for continued development.

I will look into making the changes myself that I want/require, and if successful then I will try to commit them and send them somewhere accessible, e.g. your gitlist-php/gitlist.

**Comment by PABourdin** [comment]
@IvanUrwin 
I would also suggest you to submit this as a feature request to https://github.com/gitlist-php/gitlist

Do I understand correctly, that you like to have `commit/xyz/` redirected to `commits/xyz/` if `xyz` is not a valid commit hash?

**Comment by IvanUrwin** [comment]
I would like to have commit/fix987 display the same as commit/6df61207c71c266aa9bd3cc67ae586ebde045a95 if fix987 is a lightweight tag associated with that commit.

**Comment by alehaa** [comment]
You may add custom redirections with some Silex-magix to the application by defining a custom route before the commit routes get registered. However, I don't think this should be a feature of the GitList core, as tags are already accessible via `/<tag>`.

**Comment by IvanUrwin** [comment]
If I use /fix282 I am shown a list of files. I am not interested in a list of a thousand files if I changed three.

If I then click on "commits" I am redirected to /commits/fix282. This does not show me the commit, but the list of commits leading up to it. 

If I then click "view" for the top commit - which is the one I want, I can finally see the commit contents. In the process it redirected me to /commit/475e62aacd45c34cfba0c396b0e216f57daae294 It would be nice if I could refer to this screen as /commit/fix282 

Thanks for the help. I will see what I can do. As a single parent with a 2 year old child, that will unfortunately not be much, sorry!

**Comment by alehaa** [comment]
Ok, seems legit. I'll think about plugins for optional (redirection-) routes in #739.
