### ISSUE TITLE
Syntax highlight for *.html.twig

### ISSUE THREAD

**Issue by jwmwalrus** [klaussilveira/gitlist#736]
Hi.

I installed GitList a few days ago and everything seems fine, except for the `*.html.twig` files not being highlighted.

Is that  the intended behavior or do I have to install/configure something extra? GitList's documentation is not clear about it.

I already tried adding `html.twig = twig`, `twig = twig`, `twig = jinja`, etc., to the config file, but the result is the same ---i.e., no highlight.

**Comment by DannyvdSluijs** [comment]
There is no twig extension support in the application. This can be overloaded from the configuration. Could you add below to your config:
```
[filetypes]
twig = twig
```

**Comment by jwmwalrus** [comment]
As I mentioned before, I already tried adding that to the config.ini file, but the twig block is still not highlighted.

Looking at one of the generated pages' source code, when the config.ini file has `twig = twig` in the `[filetypes]` section, I can see that the twig block is surrounded by `<pre id="sourcecode" language="twig"> ... </pre>`. So the configuration is being taken into consideration, but the block is still not highlighted.

**Comment by DannyvdSluijs** [comment]
@jwmwalrus sorry, I've missed the config options you tried already. 
After some quick scanning the codemirror in GitList is dated from 17 May 2014. Codemirror added Twig support on 2 June 2015. So it seems we need to update the code mirror library to include twig support.

This doesn't change that we need to support Twig out of the box. Support for this needs to be added to the Util class.
