### ISSUE TITLE
Provide an API for plugins

### ISSUE THREAD

**Issue by alehaa** [klaussilveira/gitlist#739]
After reviewing lots of issues and some PRs in this repository, I found several requests like "support feature xy" or "add integration for ...", which require changes in the GitList core. In my opinion, GitList ist just a repository viewer - no more and no less - and shouldn't include any third-party solutions, as the core should be really minimalistic with low overhead. However, GitList should also be extensible by any feature you'd love to include, as Silex itself is.

I'd suggest to add some provider interfaces in GitList for common tasks, which may be registered by the user as third-party plugins. E.g. there could be a Gitolite provider that will check the users's rights for a specific repository or a CI plugin adding a button in the commit list to link jobs to the corresponding commit.

**Comment by klaussilveira** [comment]
I like this idea. The problem, however, is the plugin installation and distribution. Are they just normal PHP libraries on Composer, so people can mix and match and customize their GitList integration? What about those that do not use the composer version of the application and rely only on their final build? 

Where do we draw the line between application and distribution builds? Do we, as an application, provide a custom packagist-like package installer? Or do we abandon the application concept and focus on GitList as a framework? 

These are all very important questions. To me, GitList is a very simple application that can be done over a weekend in pretty much any language. There are tons of libraries that allow interfacing with Git, Mercurial and SVN in all language ecosystems out there.

Let's all be honest here: The usefulness of GitList comes with the fact that you just need to drop it on a standard PHP/Apache distribution (that you can find on all Linux distros) and you're done. It scratches an itch and does that well. Quick and dirty. No strings attached. No complexity.

**Comment by alehaa** [comment]
I agree with you, GitList simplicity is a huge pro. I mean ... something like GitLab has lots of features, but it doesn't work in five minutes. However, I think one could get way more of GitList, if it would be extensible by plugins.

In my opinion GitList should provide just the basics - it is just a repository viewer. As an example, I think the RSS-feeds for repositories are not "basics", as this isn't a feature required by all users, whereas viewing the commit history is. So the RSS-feed for repositories could be out-sourced into a plugin, so the overhead of the core application would be decreased, if one doesn't like to have this feature. 

Plugins would be Silex providers and just need to be registered. Using composer has the advantage that files will be included automatically via the autoloader, but the plugin may also be included via an `autoload.php` file in the plugin's directory if shipped as zip - I think Debian uses this technique for shipping composer libraries. There shouldn't be an extra installer - using composer or download the zip (and include the `autoload.php`) should just be fine.

**Comment by klaussilveira** [comment]
The problem that i see with the Composer approach is that we can't expect the average GitList user to even know what Composer is. It's a pretty internal tool exclusive to the PHP ecosystem, that people coming from different backgrounds might get confused. Specially if they are system administrators that just want to get something done. 

In order to get plugins into the application, i think a custom solution is needed. Either by uploading zip/phar files in a specific folder and loading them during runtime, or some other approach.

**Comment by alehaa** [comment]
That's right. I thought about something like „Install via composer *OR* download zip into `plugins/`, then add `$app->register(...);` to your `index.php`“.

**Comment by alehaa** [comment]
It seems to be pretty easy to [extend composer for our needs](https://getcomposer.org/doc/articles/custom-installers.md) capable of installing plugins to a plugin folder and maintaining the plugin loading.

I'm not sure, if an alternative way of installing plugins should be offered. It should be easy to scan a `plugins/` folder for `autoload.php` files to include, which will register the plugin, but managing the plugin's dependencies to third-party libraries could end in a mess. Therefore I suggest testing plugins with a extended version composer first as a beta-feature.

**Comment by alehaa** [comment]
At the moment I think the following provider interfaces should be useful: 

* `RepositoryTabInterface`: Provider for tabs at repository specific pages.
  ![bildschirmfoto 2018-01-10 um 16 34 59](https://user-images.githubusercontent.com/6250567/34780760-43c60e66-f624-11e7-91db-87aea70e98ba.png)
  This interface provides a method `registerTab($repository)`, which returns an array (or object?)
  with the name and URL, an icon and a priority for the new tab. A service in the application will collect all tabs for a specific repository. Routes will be registered via Silex's `ControllerProviderInterface`.

  This interface may be used by the GitList internal providers for tree-view, commit history, etc. and additional features like embedding other services like issues.

* `RepositoryButtonInterface`: Provider for additional buttons at repository specific pages.
  ![bildschirmfoto 2018-01-10 um 16 44 08](https://user-images.githubusercontent.com/6250567/34781211-80cbdcd6-f625-11e7-85fb-2c1e942838b4.png)
  This provider is similar to the `RepositoryTabInterface`, except it is responsible for adding buttons instead of tabs. It could be used for the RSS feed or external links.

* `SecurityInterface`: This interface will be used by providers implementing repository access security. A method like `isAuthorized($user, $repository)` should tell the callee, if the user is allowed to access this repository and will be called for each repository found by GitList or for the specific repository when accessing it.
  However, this is not enough for implementing access security: Depending on the backend, Silex's `SecurityServiceProvider` needs to be configured. Therefore it would be useful to extend from it and enhancing it with the `isAuthorized()` method.

**Comment by DannyvdSluijs** [comment]
I’m liking the draft @alehaa. I would even trust the OS community to be creative on finding a solution for packaging with plugins. Optionally we can document simple installation (package) and advanced (git or composer) installation.

**Comment by alehaa** [comment]
@DannyvdSluijs thanks! ;)

I think we should evaluate the workflow of Symfony 4, how plugins could be used in here. Maybe there's a simple solution for this, as they use plugins internally for their components.

**Comment by alehaa** [comment]
After searching for different solutions, I ended up in using GitLab for now. However, I miss the simplicity of GitList and especially that it's not as hungry for resources as the 4 GB of RAM GitLab uses. However, all I really need is just an repository viewer, an issue tracker and any kind of CI integration. Maybe some kind of an admin-panel would be nice, too.

What do you think of using the plugin approach to make GitList to such an extensible, powerful tool? I could imagine something like installing a slim version thats just a repository viewer as it is already or a version with several plugins pre-installed to add collaboration tools. That would give users the choice to select what they really need and to make GitList flexible for all kind of needs.
