### ISSUE TITLE
Feature idea(s): Sorting project lists and/or starring projects

### ISSUE THREAD

**Issue by ThraaxSession** [klaussilveira/gitlist#740]
Hi!

A way of sorting projects (to starred) one might be good. Anyway I gitlist, I have to scroll down, to the project I like to work with.

Best regards
Gino

**Comment by alehaa** [comment]
Maybe you can add this to #673? ;)

**Comment by alehaa** [comment]
In general, GitList ist just a repository viewer and doesn't change information (which would be required, if users could star the repositories). However I think this may be related to #380 or a plugin as described in #739?

**Comment by DannyvdSluijs** [comment]
@alehaa I see an option where the starred data is stored as separate meta data in the plugin. As long as that can be achieved no change in the repo is needed.
