### ISSUE TITLE
'Issue' folder 

### ISSUE THREAD

**Issue by apmascalabs** [klaussilveira/gitlist#742]
Hi, 
Is there a possibility to add the 'Issue' folder ?
Thanks

**Comment by DannyvdSluijs** [comment]
Hello @apmascalabs

Could you explain your feature. As it seems now it would not fit the GitList philosophy of being just a git viewer. Perhaps there is something I missed that needs some clarification.

**Comment by apmascalabs** [comment]
Hi @DannyvdSluijs,
Do not misunderstand me, I do not want to change the philosophy of the project, but it seemed to me to be a good way to create a 'communication channel' among the users of the same repo. 
The 'issues' could be created as the 'commits', remaining only visible on the repo. 
Do you think it's a wrong way to see the project? 
thank you

**Comment by netbrothers-tr** [comment]
Hi @apmascalabs,

I guess this feature would oppose the philosophy of the project when thought of it as being a part of GitList's core but there's a discussion going on in #739 about how to make Gitlist extensible. As far as I've understood @klaussilveira, he's in favor of keeping the core rather basic and put any additional features into plugins. However, there is no plugin architecture in place at this point other than the architecture provided by the underlying framework [Silex](https://github.com/silexphp/Silex) and Composer, which is fine in my opinion. There's also a [pretty active GitList fork](https://github.com/patrikx3/gitlist) by @p3x-robot. You could ask the author about his views on this feature request. Lastly, @alehaa [maintains a fork, too](https://github.com/gitlist-php/gitlist), which has been [outlined to be a group effort](https://github.com/klaussilveira/gitlist/issues/725#issuecomment-322462830) to ensure the future development of GitList but right now seems to be maintained only by himself.

I hope this info may help you!
Cheers

P.S. [other forks exist](https://github.com/klaussilveira/gitlist/network/members)

**Comment by apmascalabs** [comment]
Ok, thanks for your answer, reading the #739 discussion I have understand the 'issues'. I will check some forks.
Thanks @netbrothers-tr

**Comment by alehaa** [comment]
@netbrothers-tr our fork is dead, as contribution will take place in this repo again. See gitlist-php/gitlist#42.

**Comment by netbrothers-tr** [comment]
Thanks @alehaa for the info! Pleased to hear!
