### ISSUE TITLE
Travis build is failing / Un-installable on PHP < 7.1

### ISSUE THREAD

**Issue by DannyvdSluijs** [klaussilveira/gitlist#745]
When wanted to merge #744 I noticed the build has been falling since cc1dc5af14e83dc7ca602694a1d2bfb7878d3aa8 .

See the transcript of Travis below:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for doctrine/annotations v1.5.0 -> satisfiable by doctrine/annotations[v1.5.0].
    - doctrine/annotations v1.5.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
  Problem 2
    - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
  Problem 3
    - doctrine/annotations v1.5.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.5.0 requires doctrine/annotations ^1.2 -> satisfiable by doctrine/annotations[v1.5.0].
    - Installation request for friendsofphp/php-cs-fixer v2.5.0 -> satisfiable by friendsofphp/php-cs-fixer[v2.5.0].
```

The introduction of  friendsofphp/php-cs-fixer seems to pull in quite some dependancies. Would the previous squizlabs/php_codesniffer not fit the job? As we could run `./vendor/bin/phpcbf --standard=PSR2 ./src` to forcefully apply the code style, or run `./vendor/bin/phpcs --standard=PSR2 ./src` to only generate a report?

**Comment by DannyvdSluijs** [comment]
@alehaa, @PABourdin, @klaussilveira I would like you opinion. Ideally I would like GitList to support the active PHP version. This would include 5.6.x as well.

**Comment by PABourdin** [comment]
@DannyvdSluijs the oldest current LTS ubuntu (14.04) has PHP 5.5.9. I would strongly suggest to also support this.

PHP up to 7.1 should of course also be supported.

**Comment by alehaa** [comment]
Maybe the dependencies could be downgraded. I'm sure one could run Silex with older versions of Twig not requiring PHP 7, too.

**Comment by klaussilveira** [comment]
GitList works well on anything higher than 5.4. Unfortunately, the libraries we use on dev are causing the version bump. I think we can safely target one version for runtime and another for dev, no? Maybe different build paths.

**Comment by PABourdin** [comment]
On the ``gitlist-php`` fork I did the Silex2 migration - and it worked fine with older PHP versions.

I do not really understand, what went wrong here.
Must be one of the other merged forks that we did not (yet) merge in ``gitlist-php``.

**Comment by alehaa** [comment]
@PABourdin cc1dc5af14e83dc7ca602694a1d2bfb7878d3aa8 introduced updates in the `composer.json` file. As composer uses the versions from the `composer.lock` file, these are causing incompatibilities with PHP < 7.1. We should discuss how to handle the locked versions in #747.

**Comment by mckaygerhard** [comment]
i'll like to use the gitlist software in the php 5.4 instalations too, well if not php 5.5 at leas!

**Comment by mckaygerhard** [comment]
???

**Comment by alehaa** [comment]
@mckaygerhard wrong issue. #747 was the right place for discussion.
