### ISSUE TITLE
Unknown preg_match() modifier "g"

### ISSUE THREAD

**Issue by utak3r** [klaussilveira/gitlist#746]
New release 0.6.0 against php 7.0.22 gives many warnings at header:
`Warning: preg_match(): Unknown modifier 'g' in /var/www/gitlist_php7/src/Git/Client.php on line 188`
Old release 0.4.0 works as expected.

**Comment by elisiano** [comment]
Even with php 7.1.1.
A couple of days back I tried to debug this and it seems to be related to the hidden repo code.
Commenting the `hidden[]=...` in the config.ini got rid of the message (obviously not a solution, just a workaround if you can live without hiding repos).

**Comment by utak3r** [comment]
You're right, commenting hidden repo out solves the problem - of course, temporarily.

**Comment by fmunch** [comment]
Adding `@` in front of the `preg_match` (src/Git/Client.php line 188) solves temporarily the problem without having to change the configuration.

**Comment by Aranad** [comment]
I'm getting this same issue on every request, but mines unknown modifier "w":
(Unknown modifier 'w' in /var/www/domains/gitlist/src/Git/Client.php on line 188)

**Comment by camilstaps** [comment]
@klaussilveira could I ask why this was closed? I'm still experiencing this issue with the current master branch.

**Comment by siburny** [comment]
It looks like you have incorrectly formatted "hidden" repos regular expression. Could you post that line from your config?

**Comment by camilstaps** [comment]
@siburny thanks, one of the lines that causes the warning:

```
hidden[] = '/home/git/repositories/cv.git'
```

Perhaps I missed an update, and this configuration value should look differently now? I can't remember if it was a regex last time I modified the config.

**Comment by siburny** [comment]
Based on the code it has be to either 1-to-1 match or regular expression. It appears that 1-to-1 match fails, so it resorts to regex: https://github.com/klaussilveira/gitlist/blob/master/src/Git/Client.php#L188

you could try doing this:
`hidden[] = '\/home\/git\/repositories\/cv\.git'`

**Comment by camilstaps** [comment]
@siburny thanks, that helps. The code is odd though; if the checked path does not match exactly, the value is interpreted as a regex. You'd expect that that interpretation does not depend on the checked path, but purely on the value in the hidden array.

Anyway, it now works. I needed to add slashes around the regex:

```
hidden[] = '/\/home\/git\/repositories\/cv\.git/'
```

**Comment by siburny** [comment]
Yes, thanks for that. I updated my answer as well. 
You can actually specify a short version like this - no need for the full path:
`hidden[] = '/cv\.git/'`

**Comment by klaussilveira** [comment]
Since gitlist is mostly used by technical people, should we just make the documentation clearer, or create an alternative implementation?

**Comment by siburny** [comment]
We can adjust the logic to only do regex when the search string starts and ends with '/'. Otherwise, it's string comparison.
