### ISSUE TITLE
Target PHP 5.5

### ISSUE THREAD

**Issue by klaussilveira** [klaussilveira/gitlist#747]
I think everyone agrees that this should be the version we support, right?

**Comment by alehaa** [comment]
Solving this issue is pretty easy: Delete `composer.lock` and patch the `composer.json`:
```diff
diff --git a/composer.json b/composer.json
index e1137d0..877e4c8 100644
--- a/composer.json
+++ b/composer.json
@@ -2,8 +2,8 @@
     "name": "klaussilveira/gitlist",
     "description": "An elegant git repository viewer",
     "require": {
-        "silex/silex": "~2.2",
-        "twig/twig": "~2.4",
+        "silex/silex": "~2.0",
+        "twig/twig": "*",
         "symfony/twig-bridge": "~3.0",
         "symfony/filesystem": "~3.0",
         "klaussilveira/gitter": "0.2.*"
```

Although I hate this lock-file in the repository, it is recommended to be kept inside the repository. What's your opinion on it @klaussilveira?

**Comment by mckaygerhard** [comment]
i wnat to use also php 5.4 or at leas 5.5! php 7 are not supported by my vendor provider!

**Comment by alehaa** [comment]
Silex 2 requieres at least PHP 5.5.9, so 5.4 isn't possible at all. How to achieve a maximum supported platforms needs to be discussed (`composer.lock`).

**Comment by mckaygerhard** [comment]
ok, silex2 are since that specified commit and due for what?
i mean, why was updated silex 2?

and i now understand the deletion of comment..

**Comment by alehaa** [comment]
Dependencies will be updated on a regular basis, e.g. for performance- and security-updates. In addition the new API of Silex was required for other features like additional services that may be registered (see #739).

**Comment by alehaa** [comment]
@klaussilveira I think some of the features recent versions of the dependencies are using could be very useful. E.g. recent versions of Twig use more type hinting which is good for type safety. So generally disabling all PHP 7 stuff might be no good idea.

I think we shouldn't use the `composer.lock` file for a maximum flexibility and get recent versions of the dependencies for recent versions of PHP, but also pack a separate tarball of GitList for PHP 5.x with older versions of the dependencies for backwards compatibility. Without the `composer.lock`, this could be done automatically in Travis CI on new releases.

**Comment by philipabbey** [comment]
I'm not keeping up with the technical conversation above. *Is gitlist ver 0.6.0 supported for PHP 5.6.30-0+deb8u1.netgear1?*

When I installed 0.6.0 I got the error message:

> PHP Catchable fatal error: Argument 1 passed to Twig_Filter::__construct() must be an instance of string, string given, called in /data/website/gitlist/src/Application.php on line 70 and defined in /data/website/gitlist/vendor/twig/twig/lib/Twig/Filter.php on line 35

Searching the web indicated I had to upgrade to PHP ver 7 for Twig v2+. Whilst probably possible, that's going to entail a whole host of grief, so I've rolled back to the 0.5.0 tarball. The text above seemed to suggest you were still aiming for PHP 5.5.

**Comment by klaussilveira** [comment]
I've been thinking of switching the router to nikic's: https://github.com/nikic/FastRoute. Combined with Pimple, that would reduce our min target to 5.4.

**Comment by tobi-the-fraggel** [comment]
oh dear...

Issue can be closed.
After I looked at it again now I realized 'repositories' folder was lacking rw for www-data user...
I am so sorry for wasting time.

**Comment by alehaa** [comment]
@tobi-the-fraggel wrong issue? ;)

**Comment by tobi-the-fraggel** [comment]
I realized shortly after and deleted my post. I was so shocked by my discovery.^^

**Comment by klaussilveira** [comment]
1.0.0 now targets 5.3 for maximum compatibility.
