### ISSUE TITLE
a doubt about repoository url

### ISSUE THREAD

**Issue by JDias** [klaussilveira/gitlist#748]
hi,
is there somehow to show on the page the address of the repo so anyone can 'git clone path' ?
(gitweb shows url, and i am missing that from glist)

**Comment by alehaa** [comment]
Just enable it in the [config.ini](https://github.com/klaussilveira/gitlist/blob/master/config.ini-example#L20).

**Comment by JDias** [comment]
didnt worked for me:

https://github.com/klaussilveira/gitlist/pull/688/files#diff-0f101cdb11b6f7d962eaf5a2ed73e3fd
https://github.com/klaussilveira/gitlist/pull/688

is it allready in the gitlist 0.4.0 ?

dunno what i did wrong :/

**Comment by alehaa** [comment]
This feature has been introduced in ecc8e97117d5f2d7b1541f5bc7689a158579f1f and is part of `v0.6.0`. Please upgrade - `v0.4.0` is more than 4 years old.

**Comment by JDias** [comment]
hi @alehaa ,

i followed the instructions:

> Do not download a branch or tag from GitHub, unless you want to use the development version. The version available for download at the website already has all dependencies bundled, so you don't have to use composer or any other tool.

i downloaded from http://gitlist.org/ but it is 0.4.0 (the file says 0.5.0 but the page shows 0.4.0)

i will upgrade, should i clone the master or is any other "stable" and "bundled" target should i look for?

**Comment by alehaa** [comment]
The "full" tarball is attached to the release (not to be confused with tag!). https://github.com/klaussilveira/gitlist/releases/tag/0.6.0

**Comment by JDias** [comment]
hi @alehaa ,
now i got the release tarball, but:

[fcgid:warn] [pid 2214] [client 177.33.181.121:56904] mod_fcgid: stderr: PHP Catchable fatal error:  Argument 1 passed to Twig_Filter::__construct() must be an instance of string, string given, called in /home/git/public_html/src/Application.php on line 70 and defined in /home/git/public_html/vendor/twig/twig/lib/Twig/Filter.php on line 35

:/

**Comment by alehaa** [comment]
Seems you're affected by #747. Use PHP 7 if available, otherwise you'll have to wait for a fixed release.

**Comment by JDias** [comment]
well, i did a dist-upgrade yesturday (debian 8->9) just to get the php7 :)

**Comment by alehaa** [comment]
Sure you're using PHP 7? Because this issue says it's not aware of the `string` type hint - so it's not running in PHP 7.

**Comment by JDias** [comment]
ps: @alehaa i dont have composer file at all in this new install

**Comment by JDias** [comment]
yes @alehaa you are right! php7 on the system, php on apache! :/ 
thanks!
