### ISSUE TITLE
Unable to get into repository directory

### ISSUE THREAD

**Issue by okarmusk** [klaussilveira/gitlist#750]
Hi,

When I tried to get into repository directory, unknown error
```
Oops! sh: 1: Syntax error: "(" unexpected
```
has appeared.

Error appear in stable (0.5.0) release and on master branch.
Error appear on Debian 8, Apache 2.4, PHP 7.0.23-1~dotdeb+8.1

BR Konrad

**Comment by alehaa** [comment]
Do you get this error in the PHP logs or where do you get it?

**Comment by okarmusk** [comment]
Currently I have no access to server, I will have in next week, please wait a little, I will try to provide PHP traces.

**Comment by alehaa** [comment]
@okarmusk any new information about this issue?

**Comment by okarmusk** [comment]
@alehaa I have moved on Ubuntu16.04 (rest of server configuration is the same), now the problem is just like in issue https://github.com/klaussilveira/gitlist/issues/716.
I found information that the reason of the error is because of upwards-compatibility, but I cannot confirm that cause I'm not php programmer. Unfortunately, no idea how to configure it on PHP7.X.
Was gitlist migrated to PHP7?

Here are logs from apache2 access.log file:
127.0.0.1 - - [29/Oct/2017:20:05:54 +0100] "GET /gitlist/PBT/ HTTP/1.1" 404 501 "http://localhost/gitlist/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
127.0.0.1 - - [29/Oct/2017:20:06:04 +0100] "GET /gitlist/gitlist/ HTTP/1.1" 404 506 "http://localhost/gitlist/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
127.0.0.1 - - [29/Oct/2017:20:06:05 +0100] "GET /gitlist/ HTTP/1.1" 200 1155 "http://localhost/gitlist/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
127.0.0.1 - - [29/Oct/2017:20:06:21 +0100] "GET /gitlist/PBT/ HTTP/1.1" 404 502 "http://localhost/gitlist/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"

error.log file is clean.
