### ISSUE TITLE
Got error 'Primary script unknown'

### ISSUE THREAD

**Issue by Schamschula** [klaussilveira/gitlist#754]
I've seen #733, and tried the various suggestions to modify `.htaccess`. However, my problem is the failure of showing the actual files, I get the file hierarchy, history and the all diffs. This is a new problem. I've had this working correctly, with PHP 5.6 under both apache and nginx.

I have tried with both nginx 1.13.6 along with php-fpm 7.1.11 (`.htaccess` means nothing here), and apache 2.4.29, again with php-fpm 7.1.11. There results are the same:

nginx:
```
2017/10/29 16:15:32 [error] 39259#0: *3 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 10.0.1.40, server: localhost, request: "GET /git/blob/master/man1/actool/index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "10.0.1.40:8080", referrer: "http://10.0.1.40:8080/git/tree/master/man1/actool/"
```

apache:
in access_log
```
10.0.1.40 - - [29/Oct/2017:16:20:21 -0500] "GET /git/blob/master/man1/actool/index.php HTTP/1.1" 404 16
```
in error_log
```
[Sun Oct 29 16:20:21.959067 2017] [proxy_fcgi:error] [pid 39136] [client 10.0.1.40:61858] AH01071: Got error 'Primary script unknown\n', referer: http://10.0.1.40:8088/git/tree/master/man1/actool/
```

**Comment by DannyvdSluijs** [comment]
Hi @Schamschula 

It seems your configuration is trying to find the `/git/blob/master/man1/actool/index.php` file not the index.php which is "hidden" at the start of the request url. 

Hope this helps in reviewing your config.

**Comment by danixland** [comment]
Hello,
I know it's an old issue but it's still open and I'm having the same problem. 
I have this configuration:

- PHP 7.4.6 
- Apache/2.4.43 (Unix)
- GitList 1.0.2

I'm using the standard .htaccess and I'm serving my repos on a vhost. Everything is working fine except when I try to access any .php file inside any of my repositories. All php files result in a "File not found" message.

This is the .htaccess:

```
<IfModule mod_rewrite.c>
    Options -MultiViews +SymLinksIfOwnerMatch

    RewriteEngine On
    # RewriteBase /gitlist/

    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php/$1 [L,NC]
</IfModule>
<Files config.ini>
    order allow,deny
    deny from all
```

Any ideas?
