### ISSUE TITLE
Custom ssh port

### ISSUE THREAD

**Issue by sharkydog** [klaussilveira/gitlist#758]
Hi all,
I added a custom ssh port option which transforms the clone url to

ssh://git@some.domain.tld:12345/some/repo.git

I don't want to fork and PR just for this tiny thing, so I post a patch instead.
Based on master https://github.com/klaussilveira/gitlist/commit/464d4db963b7d4de02b4505f051091b9adbb41df
[klaussilveira-ssh-port.diff.txt](https://github.com/klaussilveira/gitlist/files/1545696/klaussilveira-ssh-port.diff.txt)

**Comment by DannyvdSluijs** [comment]
Why don’t you fill in the ssh host with  the port number? Quick scan doesn’t show why this wouldn’t work?

**Comment by sharkydog** [comment]
Then, the clone command would become ```git clone git@some.domain.tld:12345:some/repo.git```
If I use ssh_url_subdir and set it to "12345/", result would be ```git clone git@some.domain.tld:12345/some/repo.git``` and git thinks 12345 is part of the path, so the ssh:// wrapper is needed.
Didn't try but it will probably work if ssh_url_subdir is set to "12345/" and ssh_user to "ssh://git", if ssh_user is not subject to some cleanup, ssh_user_dynamic is not used, and it feels a bit hacky.
