### ISSUE TITLE
End of Silex announced

### ISSUE THREAD

**Issue by alehaa** [klaussilveira/gitlist#759]
Silex announced its [end of life in June 2018](http://symfony.com/blog/the-end-of-silex). Although Silex may be accessible after this date, we should think about a rewrite with Symfony 4.

**Comment by klaussilveira** [comment]
Symfony 4 rocks, I finally feel comfortable migrating the project to it.

**Comment by alehaa** [comment]
I've done some experiments with Symfony 4 and like it, too. However, I'm not sure if rewriting from scratch isn't a better option to enhance components like caching or the API described in #739. 

Also, Symfony 4 requires PHP 7.1, so I think we should keep this version of GitList for legacy PHP support.

**Comment by ITwrx** [comment]
gitlist as a laravel compat composer package would be nice for many. you still get to use symphony components in the background and users could easily integrate into their laravel projects without another stand alone framework being involved.

**Comment by rossb220** [comment]
Has someone worked on a symfony/php7.4 version on this yet? If php backwards compatibility is a concern how about using Silm?
