### ISSUE TITLE
support rendering jupyter notebook

### ISSUE THREAD

**Issue by shengc** [klaussilveira/gitlist#764]
Considering how github is able to render jupyter, I think adding this feature would be extremely useful.

**Comment by alehaa** [comment]
@shengc can you describe what jupyter is and how it works?

**Comment by refrain** [comment]
I love jupyter and I use it at work, but including it with gitlist sounds a bit monolithic to me.  Jupyter is used for data science and scientific computing, generally with GPU servers to visualize data or perform compute intensive functions with the GPUs.

**Comment by alehaa** [comment]
I‘m sorry for not getting the point, but what does this have to do with a git repository viewer?

**Comment by refrain** [comment]
I'm not the original requester, just responding about what jupyter does because I have experience with it...  I'm not sure it fits with Gitlist either.

**Comment by alehaa** [comment]
Oh, my fault. Same color auf the avatars ... ;)

**Comment by shengc** [comment]
@alehaa I am really sorry for not responding in quite such a long time. Essentially, what I want is to be able to render Jupyter notebook directly from web browser. 

For example, considering the following link,
https://github.com/shengc/tf-lstm-crf-tagger/blob/master/lstm-crf-tagger.ipynb
and its raw content,
https://raw.githubusercontent.com/shengc/tf-lstm-crf-tagger/master/lstm-crf-tagger.ipynb

Jupyter notebook has become de facto way to express and exchange ideas in the realm of data science and machine learning. Just like gitlist can render the markdown file by interpreting its syntax, if gitlist can do the same for Jupyter notebook, that'd be quite useful.

**Comment by alehaa** [comment]
Okay, as far as I understand, this is something like "render markdown to HTML if extension matches" ... 

I don't think this is a feature for the GitList core. However, we're thinking about something like a plugin system for future versions (see #739).
