### ISSUE TITLE
Error 500 brought by "PHP Fatal error:  Cannot use 'Object' as class"

### ISSUE THREAD

**Issue by donpicoro** [klaussilveira/gitlist#766]
Hello, 
apparently php 7.2.2 brings this type of errors to the server:
```
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /usr/share/webapps/gitlist/vendor/klaussilveira/gitter/lib/Gitter/Model/Object.php
```
I googled a bit and found this to be not unique to gitlist, for instance:
https://github.com/unclead/yii2-multiple-input/commit/7b79bfa60f2b2261162a5a1bd4459001a4a41973

I tried to follow the solution as featured on the git commit above on the following files:
gitter/lib/Gitter/Model/Commit/Commit.php
gitter/lib/Gitter/Model/Tree.php
gitter/lib/Gitter/Model/Blob.php
and renamed
gitter/lib/Gitter/Model/Object.php -> gitter/lib/Gitter/Model/BaseObject.php

and got it to half work. I was able to navigate the git commits and history but I was not able to retrieve files directly.

Thanks for this software, this were just my two cents on the issue.

**Comment by alehaa** [comment]
These files belong to Gitter, which has [its own repository](https://github.com/klaussilveira/gitter). See #765.
