### ISSUE TITLE
Error 404 when viewing repositories.

### ISSUE THREAD

**Issue by andrewhamili** [klaussilveira/gitlist#767]
Hi. I have completed the gitlist setup on my Server. But I cannot view my repositories. Is there something wrong with my configuration or is it a bug?

![capture](https://user-images.githubusercontent.com/20767537/36902374-38dacec4-1e65-11e8-9de1-9ba92e79b199.PNG)
![capture](https://user-images.githubusercontent.com/20767537/36902405-543f4348-1e65-11e8-8c4c-c767900ecd3d.PNG)

**Comment by andrewhamili** [comment]
Logs from Apache access logs file

![capture](https://user-images.githubusercontent.com/20767537/36902771-9a23547a-1e66-11e8-9825-43854a80af58.PNG)

**Comment by Mattleoing** [comment]
I had the same problem. Solved under linux by following the 'Restrictive apache2 configuration (linux)' section on the troubleshooting page ([https://github.com/klaussilveira/gitlist/wiki/Troubleshooting](https://github.com/klaussilveira/gitlist/wiki/Troubleshooting))

Remember to change '/srv/www/htdocs/gitlist/' to your gitlist location

**Comment by alehaa** [comment]
Thanks @Mattleoing! :)
