### ISSUE TITLE
Gitlist shows repo name only. Doesn't show repo contents

### ISSUE THREAD

**Issue by fariyaf** [klaussilveira/gitlist#768]
I am using gitlist for the first time and so I have some basic issues. Here is what I intend to do: 
* On my server, I have placed a project and run the following commands:
  ```
  cd my_folder
  git init
  git add .
  git comment -m "Version 1"
  ```

* I intend to use gitlist to be able to access the git repo "my_folder" on my local machine. I installed gitlist on the server machine. Below are the steps I used for installation:
    1. Downloaded php7.0. Apache was already present on the server machine.
    2. Downloaded gitlist from gitlist.org and placed in `/var/www/` folder
    3. Renamed the `config.ini-example` to `config.ini` and edited the `repostiories[]` to point to my folder `/home/user5/xyz/` [folder `xyz` in turn contains `my_folder` directory]
    4. Opened the browser and entered "http://localhost/gitlist". The issue is it lists my repo my_folder but when I click on the repo, it says
      ```
      The requested URL /gitlist/my_folder was not found on this server
      ```
    Any clue what  I am doing wrong?

Question-2:
In addition, my question is that from my local machine, I should be able to view the contents of the gitlist folder by entering the URL http://SERVER_IP/gitlist on the browser, isn't it?

**Comment by Mattleoing** [comment]
I had the same problem. Solved under linux by following the 'Restrictive apache2 configuration (linux)' section on the troubleshooting page ([https://github.com/klaussilveira/gitlist/wiki/Troubleshooting](https://github.com/klaussilveira/gitlist/wiki/Troubleshooting))

Remember to change '/srv/www/htdocs/gitlist/' to your gitlist location

**Comment by alehaa** [comment]
Thanks @Mattleoing! :)

**Comment by CatsNipYummy** [comment]
@Mattleoing I tried what you said and my gitlist.conf looks like this:

> <Directory /var/www/html/>
  Options FollowSymLinks
  AllowOverride All
</Directory>

I have the contents of gitlist inside my /var/www/html folder (not inside /var/www/html/gitlist)

Is this the reason why I'm getting 'The requested URL was not found on this server.' as well?
