### ISSUE TITLE
Page not found exception when the commit is huge

### ISSUE THREAD

**Issue by praneeth-nimmagadda** [klaussilveira/gitlist#769]
Commit details are not shown when the commit is very big , that is when the commit has many no of files and is a larger commit ,that may not be shown in a single page...

Ideally there should be something like pagination , and based on that it has to be shown

But it throws Page Not found Exception....!!

**This page isn’t working
versions.domainname.net is currently unable to handle this request.
HTTP ERROR 500**

**Comment by alehaa** [comment]
I think #161 also covers this issue. However, no exception should be shown in this case ...

**Comment by praneeth-nimmagadda** [comment]
Ohh..ok...Yeah that is true, there should not be any exception...
