### ISSUE TITLE
No working version for Ubuntu16.04?

### ISSUE THREAD

**Issue by tobi-the-fraggel** [klaussilveira/gitlist#770]
Hey Guys!
I adore Gitlist but since I recently moved to an Ubuntu16.04 server, I found GitList not working anymore. Apparently the problem is php7.0 which is the standard php version on Ubuntu >15.0x 

Now your stable and your development build on the website both don't support php7.0. Only the readme.md in master branch mentions php7.0 in the list of requirements. All other readme's in other tags mention php <7.0 in the requirements.

Would it be possible for you to provide a testing or development build supporting php7.0 on your website? I don't want to build from source as the build process seem to require a ton of build tools of which I know none.^^ 
I would love to continue using gitlist on my 16.04 Ubuntu

**Comment by ghuser** [comment]
I am using it on `ubuntu-16.04` / `php7.0` without any problems. Have you seen the apache log?

**Comment by tobi-the-fraggel** [comment]
I am using NginX
the error I get is visible here -> [http://git.prta.co](url)

**Comment by tobi-the-fraggel** [comment]
@alehaa any updates on the situation?

**Comment by criztovyl** [comment]
Could you attach your gitlist config?

**Comment by alehaa** [comment]
@tobi-the-fraggel Not really, can't find much time for this project at the moment :/ Afaik some of the dependencies bumped the requirements up to php 7.0. Maybe the patch described in #747 should help?

**Comment by tobi-the-fraggel** [comment]
@criztovyl I am using the standard config.ini without modifications
Only thing I added is obviously the path to my repos. I attached it but I doubt you'll find anything meaningful in there.
![config ini](https://user-images.githubusercontent.com/13629510/40131621-ca593ec0-593a-11e8-983e-9dab25486c27.png)

@alehaa Do you mean the edit of composer.json?

**Comment by alehaa** [comment]
> @alehaa Do you mean the edit of composer.json?
Yep. And then just run `rm composer.lock; composer update`.

**Comment by tobi-the-fraggel** [comment]
oh dear...

Issue can be closed.
After I looked at it again now I realized 'repositories' folder was lacking rw for www-data user. So all my repos do have correct perms. I checked it back then, but I obviously didn't check the root folder....
I am so sorry for wasting time.
