### ISSUE TITLE
Cannot add single repository

### ISSUE THREAD

**Issue by ghuser** [klaussilveira/gitlist#771]
I would like to be able to add a single repository in the configuration, but when I do it I get an error: `There are no GIT repositories in /gitrepos/myrepo`. 
I don't want to add `/gitrepos/` because I only want to expose a couple repositories from inside it.

**Comment by siburny** [comment]
Technically, you can already do this. You have to add /gitrepost/ path and then use `hidden` option to hide all but one like this:
`hidden[] = /^(?!repo)/`

**Comment by DannyvdSluijs** [comment]
Gitlist is a simple git repository viewer, by default it shows all repositories, as @siburny some tricks with configuration can be done to show a single repository.
