### ISSUE TITLE
404 for .css and .js  files after gitlist installation

### ISSUE THREAD

**Issue by frederickjh** [klaussilveira/gitlist#780]
Hi!
All the `.css` and `.js` files are returning a 404 on my gitlist installation. So currently it looks worse than git web.

<hr>

![image](https://user-images.githubusercontent.com/864159/40474410-3ac734f0-5f3f-11e8-872a-a6df2acc0830.png)

<hr>

The rewrite to the folder `gitlist` works for everything else like when I move to a repository. As you can see in the screenshot the rewrite is not working for the `.css` and `.js` files. The `/gitlist/` is not being added.

![image](https://user-images.githubusercontent.com/864159/40474092-5de41ba2-5f3e-11e8-8f2f-570b7f509b6e.png)

I installed via the instructions using a release, setup cache, .htaccess rewrite, setup apache2 conf for gitlist. I also went through the troubleshooting list and set the extra php.ini items. 

I have set `suhosin.executor.include.whitelist = phar` in my `php.ini` along with the other values but it does not show up using `phpinfo()`, but I am not sure if that is the issue as doing a search i do not find the term **suhosin** anywhere in the phpinfo.

I am using port 81 but that also does not seem to be the issue as it appears in the 404 urls for the `.css` and `.js` files.

Any helpful advice anyone can give to getting this working would be appreciated!
Frederick

**Comment by DavidBruchmann** [comment]
if you set the file-rights right (also for the folders) (0744) you still have to set the executable-bit, so the rights are then 0755.
The difference in requirement might refer to the kind how php is running I suppose: either native inside apache or as cgi (which is always the fact in nginx).

**Comment by alehaa** [comment]
Duplicate of #775 and #779?

**Comment by frederickjh** [comment]
@DavidBruchmann  Permissions look like this, which I believe is what you said they should be.
```
drwxr-xr-x 2 www-data www-data 4.0K Mai 23 22:22 css/
drwxr-xr-x 2 www-data www-data 4.0K Mai 23 22:22 img/
drwxr-xr-x 2 www-data www-data 4.0K Mai 23 22:22 js/
drwxr-xr-x 2 www-data www-data 4.0K Mai 23 22:22 less/
-rwxr-xr-x 1 www-data www-data   64 Mai 23 22:22 Makefile*
drwxr-xr-x 2 www-data www-data 4.0K Mai 23 22:22 twig/
```
```
-rwxr-xr-x 1 www-data www-data  21K Mai 23 22:22 bootstrap.js*
-rwxr-xr-x 1 www-data www-data 226K Mai 23 22:22 codemirror.js*
-rwxr-xr-x 1 www-data www-data  459 Mai 23 22:22 draw.js*
-rwxr-xr-x 1 www-data www-data  17K Mai 23 22:22 list.min.js*
-rwxr-xr-x 1 www-data www-data 2.7K Mai 23 22:22 main.js*
-rwxr-xr-x 1 www-data www-data  16K Mai 23 22:22 networkGraph.js*
-rwxr-xr-x 1 www-data www-data  89K Mai 23 22:22 raphael.js*
-rwxr-xr-x 1 www-data www-data  38K Mai 23 22:22 showdown.js*
-rwxr-xr-x 1 www-data www-data 3.3K Mai 23 22:22 table.js*
```
```
-rwxr-xr-x 1 www-data www-data 706 Mai 23 22:22 gitgraph.css*
-rwxr-xr-x 1 www-data www-data 94K Mai 23 22:22 style.css*
```
@alehaa I tried patching with commit from pull request #776, but this does not make a difference. The files are still 404.

Thanks for your advice!
Frederick

**Comment by welljsjs** [comment]
@frederickjh Absolutely looks like it is related to #776 and #777. Are you sure you patched with both PRs? #777 should fix this. If that solved your problem, please make sure to have a look at fixed and closed issues first next time you open an issue. If it really doesn't, let us know again.

**Comment by frederickjh** [comment]
@welljsjs I only patched with #776 I will need to try with both #776 and #777 and get back to you on if that worked.

**Comment by welljsjs** [comment]
@frederickjh Oh, and don't forget to clear everything inside the `cache` directory before reloading the page in your browser.

**Comment by frederickjh** [comment]
Yes patching with pull request #776 and #777 plus clearing the cache fixes this issue.
