### ISSUE TITLE
Unable to guess the mime type as no guessers are available (Did you enable the php_fileinfo extension?) 

### ISSUE THREAD

**Issue by qurbanullah** [klaussilveira/gitlist#783]
I install gitlist 1.0.0 on a shared hosting. Everything works fine but when I click on the Zip/Tar archive button I get the the error message "Unable to guess the mime type as no guessers are available (Did you enable the php_fileinfo extension?) ".

I do some googling and found that enable  php_fileinfo.so extension as a workaround found same error massage. I think probably the  php_fileinfo is not available on shared hosting.

If  php_fileinfo is not available / enabled than what is an alternative and how to fix this issue. Moreover I tried both php version ie. 5.x.x and 7.x.x.

**Comment by klaussilveira** [comment]
This is related to `Symfony\Component\HttpFoundation\BinaryFileResponse` depending on this PHP extension the guess the mimetype of the file being returned. Hard-coding the correct mimetype in the `Content-Type` header might override the guesser:

https://github.com/symfony/http-foundation/blob/2.8/BinaryFileResponse.php#L194

**Comment by qurbanullah** [comment]
Thanks a lot, I comment out these line and it fixed the issue.
