### ISSUE TITLE
Gitlist logo design

### ISSUE THREAD

**Issue by reallinfo** [klaussilveira/gitlist#784]
I want to contribute. Do you want me to design a logo for the Gitlist? I will wait for feedback.

you can look the designs in my profile. 
https://github.com/reallinfo

**Comment by DannyvdSluijs** [comment]
Hi @reallinfo. Thank you for your inputs. I think gitlist could definitely use a logo which allows for easy recognition. Perhaps make some sketches of different ideas (if your having any?) and we can check which might be the best? No idea how something like image design get handled in OSS. 

For me gitlist is heavily tied with GIT any logo based on a letter G or the +/- signs that are used in a diff are symbols that resemble some GIT tooling. But this is only my user opinion as I am no graphical designer.

**Comment by reallinfo** [comment]
I designed a logo. How is that?

![gitlist](https://user-images.githubusercontent.com/36298335/41153235-cf7277b4-6b1e-11e8-85ce-66e20a4cbbac.jpg)

**Comment by alehaa** [comment]
That looks great! ;) For the favicon I'd use the left one without text and the right one e.g. in the header.

I think the "official" spelling is "GitList" (@klaussilveira ?), maybe you can change it that way?

**Comment by DannyvdSluijs** [comment]
I’m liking it very much aswell.

**Comment by reallinfo** [comment]
Okey, i made changes. How is these? Which variations do you prefer? Left or right?

![gitlist](https://user-images.githubusercontent.com/36298335/41186140-252f080e-6b9a-11e8-84d0-89e4d8f39864.jpg)

**Comment by DannyvdSluijs** [comment]
My personal preference would be the tilted version. As it feels like it’s on the move, which has some reflection on what gitlist is trying to show (current and historical state of the sources)

**Comment by reallinfo** [comment]
Sure, when you make a final decision, I can send a pr for all the files.

**Comment by klaussilveira** [comment]
I don't think we ever had an official spelling, and given @reallinfo's talent, I think we should use whatever he thinks looks best in the logo. 

Thanks a lot, this is really cool. :)

**Comment by klaussilveira** [comment]
BTW: If we're doing a vote, I vote for the first tilted version.

**Comment by reallinfo** [comment]
Okay, then I will send a pr. ?

**Comment by reallinfo** [comment]
Oh, okay. I sent a pr. Please check it.

https://github.com/klaussilveira/gitlist/pull/793

**Comment by DannyvdSluijs** [comment]
With the #793 merged this issue can be considered resolved. @reallinfo thank you for your contribution.
