### ISSUE TITLE
Error in \vendor\klaussilveira\gitter\lib\Gitter\Repository.php

### ISSUE THREAD

**Issue by ChummerHB** [klaussilveira/gitlist#795]
Sorry, I have no git access to provide a pull request on the company PC.
Server is a windows machine.

\vendor\klaussilveira\gitter\lib\Gitter\Repository.php line 165:

$branches = explode("\n", $branches);
   should be
$branches = explode("\r?\n", $branches);

otherwise branches list from windows git will not be splitted.

**Comment by siburny** [comment]
Gitter is a separate library: https://github.com/klaussilveira/gitter
