### ISSUE TITLE
No theme on Version 1.0.0

### ISSUE THREAD

**Issue by andrewhamili** [klaussilveira/gitlist#798]
Hi. I recently downloaded the Version 1.0.0. I just copied the config.ini file from version 0.6.0. Is there something wrong with my setup or it is a bug?

![image](https://user-images.githubusercontent.com/20767537/41449171-07d86dfc-7092-11e8-9e70-d33284b8837e.png)

**Comment by andrewhamili** [comment]
I tried both bootstrap3 theme and default theme. But it seems to be not working

**Comment by alehaa** [comment]
see #777.

**Comment by andrewhamili** [comment]
BTW. I get these 404 results:

![image](https://user-images.githubusercontent.com/20767537/41449269-a077e31c-7092-11e8-9f28-a1266f343add.png)

**Comment by alehaa** [comment]
Please check [v1.0.1](https://github.com/klaussilveira/gitlist/releases/tag/v1.0.1).
