### ISSUE TITLE
Ubuntu 16.04 Install, 404 Not Found, Solved

### ISSUE THREAD

**Issue by jzamanski** [klaussilveira/gitlist#799]
standard install with php7.0 / apahce2 on Ubuntu 16.04

web app showed repo list but when I clicked on a repo it returned a 404
pulled hair out for hours
finally found this buried in some issue comments and it fixed it
sudo a2enmod rewrite

**Comment by capitalPSA** [comment]
This solved my issue.

Can this be put on the readme?
