### ISSUE TITLE
Does not work with PHP 7.2

### ISSUE THREAD

**Issue by davidnewcomb** [klaussilveira/gitlist#801]
> [Fri Jun 22 12:44:42.080183 2018] [php7:error] [pid 14521] [client 172.50.10.239:59269] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /var/www/html/gitlist/vendor/klaussilveira/gitter/lib/Gitter/Model/Object.php on line 14, referer: http://127.0.0.1/gitlist/

To fix it, I had to changed **composer.json** from

    "require": {
        "php": ">=5.3",
        "doctrine/instantiator": "1.0.*",
        "klaussilveira/gitter": "0.2.*",

to

    "require": {
        "php": ">=5.3",
        "doctrine/instantiator": "1.0.*",
        "klaussilveira/gitter": "0.4.*",    <----

**Comment by alehaa** [comment]
Can you create a PR for this? ;)

**Comment by davidnewcomb** [comment]
Sure but you won't get a nice branch name!
#803

**Comment by davidnewcomb** [comment]
Not sure how it closed itself!
