### ISSUE TITLE
PHP Fatal error:  Cannot use 'Object' as class name

### ISSUE THREAD

**Issue by j75** [klaussilveira/gitlist#805]
Hello,

I am using PHP 7.2.4 on Debian 9.5 and I am encountering the following error when trying to enter in a Git project:

> PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in 
> .../gitlist/vendor/klaussilveira/gitter/lib/Gitter/Model/Object.php on line 14

**Comment by alehaa** [comment]
See #765.
