### ISSUE TITLE
Warning: Declaration of GitList\Git\Repository::getStatistics($branch) should be compatible with Gitter\Repository::getStatistics()

### ISSUE THREAD

**Issue by espsistvc** [klaussilveira/gitlist#814]

**Comment by klaussilveira** [comment]
Latest master has this fixed, we didn't draft a new release yet.

https://github.com/klaussilveira/gitlist/compare/1.0.1...master
https://github.com/klaussilveira/gitter/commit/68c8d078cac2f5349bd61ce01742eb5dd1af52cb
