### ISSUE TITLE
Fatal error: Can't use "Object" as a class name anymore since PHP 7.2

### ISSUE THREAD

**Issue by cmanley** [klaussilveira/gitlist#815]
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /var/www/gitlist/vendor/klaussilveira/gitter/lib/Gitter/Model/Object.php on line 14

The solution is rename the class and all references to it to Objekt or something similar.

See: http://php.net/manual/en/reserved.other-reserved-words.php

**Comment by cmanley** [comment]
Not an issue anymore. I assumed the version on gitlist.org was the latest but it isn't.

**Comment by sigmap** [comment]
I'm on 1.0.1 and get that error with php 7.2

**Comment by cmanley** [comment]
That's correct. 1.0.1 is the latest build release and it has that error, however, the latest source in master is ahead of that build and pulls in a later version of  Gitter.

**Comment by sigmap** [comment]
I was hoping to avoid using docker or using something other than the latest stable

**Comment by sigmap** [comment]
well it doesn't seem so bad, running composer to install the dependencies. One error is replaced with another
