### ISSUE TITLE
Please make a new release so that the PHP 7.2 compatible gitter can be used.

### ISSUE THREAD

**Issue by cmanley** [klaussilveira/gitlist#816]
I've got a docker build ( https://github.com/cmanley/gitlist-docker ) based on alpine 3.8 + php-fpm 7.2 + nginx, but I had to use a custom build to get it to work with PHP 7.2. It would be nice if a newer 'official' release later than 1.0.1 was placed on gitlist.org.
The 1.01 build on gitlist.org does not support PHP 7.2 yet (due to the gitter class named Object).
Thanks

**Comment by afranke** [comment]
Ubuntu 18.04 here, PHP version is 7.2 as well. A 1.0.2 release would be very welcome.

**Comment by andrewborem** [comment]
Also running PHP 7.2 and would love for a patch to support. I am currently forced to use a fork of the main project, which includes a ton of extra "features" that I really do not love / make my team's life a lot less fun. An official patch that supports the latest PHP would be truly appreciated!

**Comment by parserme** [comment]
To make project work on php7 just rename the class from Object to something else for example to Objectc. These commands do it:
```
grep -rE "[^a-zA-Z0-9]Object" ./vendor/klaussilveira/ | cut -d: -f1 | while read f; do sed -ri "s/(.+[^a-zA-Z0-9])(Object)(.*)/\1\2c\3/" "$f"; done
mv ./vendor/klaussilveira/gitter/lib/Gitter/Model/Object{,c}.php

```

**Comment by andrewborem** [comment]
https://github.com/klaussilveira/gitter/tree/master/lib/Gitter/Model

This is actually fixed, now, I just foolishly did not do a `composer update`. 

@parserme also has an excellent suggestion. Either way, this is completely solvable! Thanks for the help!

**Comment by Greymerk** [comment]
I cloned the gitlist repo and did a 'composer install' and it worked out of the box. No edits necessary. Not sure why the download from the website isn't up to date. I'm running php7.3 currently.

**Comment by alehaa** [comment]
I've packged [a new release](https://github.com/klaussilveira/gitlist/releases/tag/1.0.2).

**Comment by cmanley** [comment]
Thanks! I've committed a new Docker build that uses release 1.0.2
