### ISSUE TITLE
[Windows] Oops! The filename, directory name, or volume label syntax is incorrect. 

### ISSUE THREAD

**Issue by sigmap** [klaussilveira/gitlist#819]
running the latest from master as of this writing. Windows 7. php 7.2. on xampp

```
git clone https://github.com/klaussilveira/gitlist.git
cd gitlist
composer install
```
Edited config to point to a directory containing a pair of cloned repositories.

**Comment by siburny** [comment]
I am on Windows, and don't have a problem like that. Can you post your config file?

**Comment by siburny** [comment]
It's the same problem as #817: make sure you specified the full path to your git.exe
```
client = 'c:\Program Files\Git\bin\git.exe' ; <- full path to your git.exe
```
