### ISSUE TITLE
Invalid HTML in repository browser

### ISSUE THREAD

**Issue by arnowelzel** [klaussilveira/gitlist#824]
I noticed, the the RSS icon is not placed properly in the repository browser but is shifted downwards a bit:

![image](https://user-images.githubusercontent.com/6613614/49382094-c538ad80-f715-11e8-9e3c-e596939ba303.png)

When examining the cause for the problem I also realised, that the HTML code for the header is a quite strange combination of a list and div elements. This is not valid HTML:

```
<ul class="breadcrumb">
  <li><a href="/gitlist/website/tree/master/">website</a></li>
  <div class="pull-right">
    <div class="btn-group download-buttons">
      <a href="#" class="btn btn-mini" title="Show remotes to clone this repository." id="clone-button-show">Clone</a>
      <a href="/gitlist/website/zipball/master" class="btn btn-mini" title="Download 'master' as a ZIP archive">ZIP</a>
      <a href="/gitlist/website/tarball/master" class="btn btn-mini" title="Download 'master' as a TAR archive">TAR</a>
    </div>
    <a href="/gitlist/website/master/rss/" class="rss-icon"><i class="rss"></i></a>
  </div>
  <div id="clone-popup">
    <div id="clone-popup-inner-wrapper">
      <a class="close" href="#" id="clone-button-hide">&times;</a>
      <div class="btn-group">
        <button class="btn" id="clone-button-http">HTTPS</button>
      </div><br />
      <input type="text" class="form-control visible" id="clone-input-http" value="...">
    </div>
  </div>
</ul>
```

This fragment has multiple issues:

1. DIV is not allowed as child of UL. At least there should be three LI elements and not one LI and two DIV elements inside UL.

2. The RSS icon should be inside of the DIV with the download buttons (maybe with a margin-left of 1em), so the icon will be at the same vertical position as the buttons.

**Comment by jacky0915** [comment]
vertical-align: top; for the link will solve the problem

**Comment by arnowelzel** [comment]
Thanks for the suggestion - however the HTML code is **not valid** and should be fixed.
