### ISSUE TITLE
Support for SVN / Mercurial

### ISSUE THREAD

**Issue by ahorseman** [klaussilveira/gitlist#827]
Dear developers,

first of all a big thank you for this tremendously valuable tool. It's really easy to install and quickly set up. However, a "big drawback" on it is that it as far as I see only supports Git. Would it be possible to extend it to work with Mercurial (and even better CVS and SVN as well especially to easier review legacy software repos) as well? That would be a huge thing!

Keep your great work up!

**Comment by alehaa** [comment]
I don't think GitList will support this in the near future. What do you think @klaussilveira?

**Comment by klaussilveira** [comment]
Mercurial is possible. Unfortunately, achieving a good abstraction on top of SVN/CVS without losing features is though. A SVN-specific viewer would always be better.
