### ISSUE TITLE
Enable HTTPS on GitHub Pages

### ISSUE THREAD

**Issue by FranklinYu** [klaussilveira/gitlist#830]
IIUC the site http://gitlist.org/ is hosted on GitHub Pages, which supports HTTPS out-of-box.

https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by alehaa** [comment]
@klaussilveira could you take a look at this, as I don't have access to the settings?

**Comment by klaussilveira** [comment]
> Not yet available for your site because the certificate has not finished being issued.
Please allow 24 hours for this process to complete. (gitlist.org) 

Thanks for the heads up!

**Comment by klaussilveira** [comment]
Absolutely. Every PR is welcome!

**Comment by FranklinYu** [comment]
The fix has been verified on https://gitlist.org/. Closing.
