### ISSUE TITLE
Support for php built-in web server

### ISSUE THREAD

**Issue by guoxiaoyong** [klaussilveira/gitlist#833]
First of all, thank you @klaussilveira for sharing this great tool.  My question is that does PHP built-in web server work well with GitList. If it does, then I can easily running GitList locally for personal use.

I have tried it, it seems partially working, the problem is that when I click a file name in repo, it give me Not Found page. Sometimes, for top-level files, it works, but most cases it does not work.

I'm not sure what cause this, anyone can help me? thanks.

**Comment by alehaa** [comment]
Can you provide us the command line, how you invoke the server?

**Comment by guoxiaoyong** [comment]
I use MacOS, and brew installed php (version 7.1.16), then I download gitlist, and set config file,
and in the gitlist directory, I launch php internal servery by `php -S localhost:8888`

**Comment by alehaa** [comment]
You need to specify a routing script, that handles all incoming traffic. Try adding `index.php` as next parameter, otherwise a little helper script is needed. See [example 3](http://php.net/manual/en/features.commandline.webserver.php) for details.

**Comment by guoxiaoyong** [comment]
Thank you so much. Simply run ` php -S localhost:8888 index.php` solves my problem.  

I suggest add this in the ReadMe file.

**Comment by alehaa** [comment]
The builtin webserver of php is meant for development purposes only and shouldn't be used in production. Therefore this shouldn't be part of the public README in my opinion.
