### ISSUE TITLE
Search tree error

### ISSUE THREAD

**Issue by bmdumr** [klaussilveira/gitlist#834]
Trying to use the "search tree..." results in php error:
```
Warning: preg_match_all(): Compilation failed: invalid range in character class at offset 4 in gitlist/src/Git/Repository.php on line 342
```

**Comment by alehaa** [comment]
Can you provide further information about the error like the generated regular expression?

**Comment by bmdumr** [comment]
I'm just typing in a simple text input, e.g. "searchtext" in the "search tree..." form input.

How do I get repository.php to output the generated regular expression? I've looked at the source and I'm not familiar enough with regular expression patterns to understand what line 342 of repository.php is doing:

`preg_match_all('/([\w-._]+):([^:]+):([0-9]+):(.+)/', $result, $matches, PREG_SET_ORDER);`

I can complete a text search using grep at the command prompt and yield a result.

`grep -rnw '/path/' -e 'searchtext'`

**Comment by Mattie112** [comment]
If you don't want to wait till my pull-request is merged you can change the "-" in the first part of the expression to "\-". For more details see my pull request.
