### ISSUE TITLE
Support for local checkout

### ISSUE THREAD

**Issue by rapgro** [klaussilveira/gitlist#835]
There's support for bare repository without .git subfolder.
Can you also support local checkout incl. .git subfolder? This shouldn't be difficult to implement because git has to just look in the subfolder instead.
https://stackoverflow.com/questions/3959924/whats-the-difference-between-git-clone-mirror-and-git-clone-bare

**Comment by alehaa** [comment]
Can you explain, why you need GitList to work on local checkouts?

**Comment by rapgro** [comment]
Sorry, I obviously meant vice versa and get confused. Support should be there for both alternatives.
