### ISSUE TITLE
issue in search 

### ISSUE THREAD

**Issue by el3zahaby** [klaussilveira/gitlist#837]
https://github.com/klaussilveira/gitlist/blob/c0cb5fbca0725bb4dcf43d3ff5098d7fa49f5632/src/Git/Repository.php#L342        
the error :
--
![image](https://user-images.githubusercontent.com/12745270/54479944-c6f52f80-4833-11e9-913e-8cfdc21f2187.png)

**Comment by alehaa** [comment]
See #834.
