### ISSUE TITLE
git-ls-tree process receives sigpipe signal (exit code 141)

### ISSUE THREAD

**Issue by bluppfisk** [klaussilveira/gitlist#839]
The Symfony Process spawned by the gitter dependency receives the 141 Exit Code (SIGPIPE: Write to pipe with no one reading) on HP UX if a directory contains a fairly large list of files (in my case, anything over 8000 bytes fails).

**Comment by bluppfisk** [comment]
I was able to fix (read: botch into submission) it by replacing 

        $process->run();

        if (!$process->isSuccessful()) {
              throw new ProcessFailedException($process);
        }

        return $process->getOutput();


by 

```
$oldcwd = getcwd();
chdir($repository->getPath());
$output= exec($this->getPath().' '.$command,$data);      
chdir($oldcwd);
return implode("\n", $data);
```

**Comment by alehaa** [comment]
I asume this is an issue for [the Gitter project](https://github.com/klaussilveira/gitter)?

**Comment by bluppfisk** [comment]
@alehaa and perhaps even the Symfony Process component. But because this project includes them as-is instead of through a package.json, and because it may be due to how this project uses them, I thought it wiser to open the issue here and let the maintainers escalate it from there? Is this wrong?

**Comment by alehaa** [comment]
If I get you right, the patch above needs to be applied in the Gitter sources, so I thought it needs to be done there.

**Comment by bluppfisk** [comment]
Sorry I wasn't being entirely clear. The above "patch" is not an acceptable solution, but more a dirty workaround. This workaround could be implemented either in the Gitter or in the Gitlist code, but in my opinion this project is broken on HP UX for its choices of dependencies or for how it uses them. I thought because the maintainer is the same person, this would be a good place to start. But if you maintain I should open the bug in the Symfony Process component repo or in the Gitter repo, I will.

**Comment by alehaa** [comment]
I'm just a maintainer of GitList. However, I think the Symfony maintainers will appreciate any contribution.

**Comment by bluppfisk** [comment]
I will try my luck with them. But I'm afraid they'll point me right back here :)
