### ISSUE TITLE
Could a download also include GIT-LFS Server Directories? - feature

### ISSUE THREAD

**Issue by HartmutWoehrle** [klaussilveira/gitlist#841]
Hello Developer

now that we successfully integrated a git-LFS server/service, the remaining file in git is the small pointer to the source. When downloading ZIP (or TAR) it is the same.
Could there be a possibillity to integrate git-lfs into the download (git-lfs client software is installed on the git server)?

Thanks for the good work

Regards
Hartmut

**Comment by alehaa** [comment]
I don't think this is possible, as the archive contains the repository as it is.

In my opinion your requested feature should be implemented in a continuous deploy task. Travis CI and similar tools could help with this.
