### ISSUE TITLE
Please, edit the config file and provide your repositories directory

### ISSUE THREAD

**Issue by sigmap** [klaussilveira/gitlist#843]
I have the config.ini pointing to a directory that exists. Does it need to contain a git repository, does it need chown or chmod?

I've tried pointing it to a directory that has multiple git repos in it and pointing to a single repo and it doesn't seem to take. I'm in need of clarification.

**Comment by alehaa** [comment]
According to the documentation, the path points to a folder containing the repositories. It needs to be readable by the webserver.
