### ISSUE TITLE
'404 Not Found. ' and then some

### ISSUE THREAD

**Issue by sigmap** [klaussilveira/gitlist#844]
Cloned a couple repositories. Each one is owned by http:http. Trying to access them yields a 404. 

I followed the instructions in `Install.md` but now when I try to access  the base url I get a file spat out at me unless I add an index.php to the urlbar of my browser.

**Comment by guzzisti** [comment]
I guess you need to add some more info if somebody should be able to help you.
Does the gitlist site itself work without a repo included?

**Comment by markathomas** [comment]
I'm having the same issue.  All my repositories are found but clicking on any of them yields a 404 in Apache

**Comment by alehaa** [comment]
Maybe this is related to #799?

**Comment by markathomas** [comment]
Yup, that solved my problem
