### ISSUE TITLE
Gitlist fatal error in xcode While cloning the Develop Branch

### ISSUE THREAD

**Issue by dvudutharpi** [klaussilveira/gitlist#847]
Hi as shown in Bellow image i am getting Fatal Error while cloning Develop branch from Gitlist in XCode.

Master branch, I was able to clone the master branch with my credentials. But I could not able to clone the **Develop Branch**. Even could not read the fatal error message to browse. Can any one please suggest is there any way to clone the branches other than master in GitList.

Thanks in advance

![Screenshot 2019-11-11 at 3 47 15 PM](https://user-images.githubusercontent.com/30502380/68740329-d4f08f80-0610-11ea-8d4b-6665278c9f04.png)

**Comment by alehaa** [comment]
Do you mean cloning this repository or cloning a repository from a GitList server?

**Comment by klaussilveira** [comment]
I think this was fixed?
