### ISSUE TITLE
Clarify what kind of contributions are currently welcome

### ISSUE THREAD

**Issue by camilstaps** [klaussilveira/gitlist#849]
The readme currently says the following:

> If you are a developer, we need your help. GitList is a young project and we have lots of stuff to do. Some developers are contributing with new features, others with bug fixes. But you can also dedicate yourself to refactoring the current codebase and improving what we already have.

However it seems that you are not really interested in new contributions aside from obvious bug fixes. It would save many people a lot of time if you would clarify right on top of the readme that this project is not actively maintained.

@klaussilveira @alehaa

**Comment by klaussilveira** [comment]
It's hard to clarify. I'm not actively working on gitlist other than fixing bugs and making sure it keeps working. Same for other maintainers, apparently. New features, as long as not major, are welcome. Major would be anything that affects a current installation: requiring new versions of X, requiring new libraries, requiring new configs, etc.

There are some forks available that have a different architecture vision. You can contribute here, or to a fork, or both. It's really up to you.

**Comment by camilstaps** [comment]
> New features, as long as not major, are welcome.

Are they really, though, since there are several rather old PRs that do not receive any attention from maintainers?

I appreciate that sometimes no maintainers can be found, but then maybe it's time to accept that and say that only bug fixes will be considered. Everyone has been in situations like this where you just can't devote as much time as you'd wish on older projects and that's perfectly fine; it just seems like clarifying this will lead to less work for both you and outside contributors.

Feel free to close this issue.
