### ISSUE TITLE
Separate branches and tags in browsing drop down box

### ISSUE THREAD

**Issue by stdbull** [klaussilveira/gitlist#850]
Hi. I've just installed gitlist on my server. It's very nice. Thank you. One nice thing for a feature enhancement might be - when typing into the 'browsing' box and search/filtered results are listed, if the branches and tags headings were kept in the search results it would help differentiate between branches and tags in the searched/filtered results. At the moment, the searching/filtering works, but there is no way to tell what's a branch and what's a tag (unless you know by name).
Thanks for your consideration.
Regards.

**Comment by klaussilveira** [comment]
I've added to correct labels here to help potential contributors. That's also a great task for new developers coming into the project. Thanks for the report!
