### ISSUE TITLE
Be able to view single branch in Graph view

### ISSUE THREAD

**Issue by stdbull** [klaussilveira/gitlist#851]
Hi again. It does not seem to be possible to 'isolate' your view to one branch alone when in the Graph view (unless I missed something). How is the Graph view supposed to work exactly? On a repository with a few branches in it, I can visit FQDN/gitlist/path/to/repo.git/treegraph?branch=branchname and if I change branchname to different branch names, the view is identical (except with different colours). This is with the default theme.
Maybe I'm missing something with the Graph view?
Regards.

**Comment by yangbo02** [comment]
It seems to be including up to 100 commit on all branches. The relevant git command in [here](https://github.com/klaussilveira/gitlist/blob/master/src/Controller/TreeGraphController.php#L20).
