### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function ctype_alpha

### ISSUE THREAD

**Issue by xoneill007** [klaussilveira/gitlist#854]
I installed gitlist on FreeBSD 12.x with PHP v7.2. Previously I have this working on FreeBSD 11.0 with PHP v5.6. 

I was careful to install all of the required PHP extensions (including php72-ctype-7.2.26).

Came across this post and decided to try a composer based installation (no luck):

https://github.com/klaussilveira/gitlist/issues/816

Here's the one-line error from the Apache error log when I attempt to load gitlist:

`[Sun Dec 29 22:41:07.676549 2019] [php7:error] [pid 777] [client 192.168.1.1:18271] PHP Fatal error:  Uncaught Error: Call to undefined function ctype_alpha() in /usr/local/www/gitlist/vendor/twig/twig/lib/Twig/Lexer.php:396\nStack trace:\n#0 /usr/local/www/gitlist/vendor/twig/twig/lib/Twig/Lexer.php(68): Twig_Lexer->getOperatorRegex()\n#1 /usr/local/www/gitlist/vendor/twig/twig/lib/Twig/Environment.php(674): Twig_Lexer->__construct(Object(Twig_Environment))\n#2 /usr/local/www/gitlist/vendor/twig/twig/lib/Twig/Environment.php(774): Twig_Environment->tokenize(Object(Twig_Source))\n#3 /usr/local/www/gitlist/vendor/twig/twig/lib/Twig/Environment.php(452): Twig_Environment->compileSource(Object(Twig_Source))\n#4 /usr/local/www/gitlist/vendor/twig/twig/lib/Twig/Environment.php(363): Twig_Environment->loadTemplate('index.twig')\n#5 /usr/local/www/gitlist/src/Controller/MainController.php(20): Twig_Environment->render('index.twig', Array)\n#6 [internal function]: GitList\\Controller\\MainController->GitList\\Controller\\{closure}()\n#7 /usr/local/www/gitlist/vendor/symfony/http-kernel/HttpKernel.php(144): call_user_func_array(Ob in /usr/local/www/gitlist/vendor/twig/twig/lib/Twig/Lexer.php on line 396`

**Comment by alehaa** [comment]
Seems like your PHP installation is broken. See twigphp/twig#2051.

**Comment by xoneill007** [comment]
Thanks sir! Once I et some time, I'll take a VM snapshot and change the version of PHP to perhaps v.74 via the FreeBSD package system.  I'll report back once I have the result...

**Comment by xoneill007** [comment]
Thanks sir. Tried 4 different versions of PHP packages on FreeBSD 12.x - same result. Something else must be at play here (perhaps compile options for php7X-ctype-7.X.1). If I ever figure it out, I'll come back to post. Just leaving this reference here in case others encounter this problem.
