### ISSUE TITLE
"Graph" view is truncated, not possible to page down or scroll down.

### ISSUE THREAD

**Issue by prof7bit** [klaussilveira/gitlist#855]
The "graph" view in its current form is not very usable. It only shows the newest commits but there is no "older" button nor any other means to scroll further down.

**Comment by yangbo02** [comment]
Not sure if there is any consideration, it limits up to 100 commits on [this line](https://github.com/klaussilveira/gitlist/blob/master/src/Controller/TreeGraphController.php#L20) with "-n 100". Removing that and you will get the full graph.
