### ISSUE TITLE
git repos should not be exposed under /

### ISSUE THREAD

**Issue by hholst80** [klaussilveira/gitlist#857]
What happens if I have a repository called "themes"? All git repos should be placed in a virtual directory (/r/ or similar) to avoid a name collision with reserved directory names.

```
nginx_1  | 172.28.0.1 - - [03/Feb/2020:20:19:54 +0000] "GET /themes/default/img/feed.png HTTP/1.1" 304 0 "http://0.0.0.0:32775/themes/default/css/style.css" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
nginx_1  | 172.28.0.1 - - [03/Feb/2020:20:19:55 +0000] "GET /api-server/ HTTP/1.1" 200 13950 "http://0.0.0.0:32775/" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
```

**Comment by alehaa** [comment]
I see the point in this. However, as this is rarely the case, I wouldn't change the URL scheme. GitList doesn't get new features anymore (right now) and this would break the "API" of the URL scheme.

**Comment by hholst80** [comment]
You make a strong point. Breaking exposed APIs is not something one should do without judgement.

But there are also other aspects of this. How do we then allow config.ini to be read from inside a repo but denied outside a repo without scoping the repos? It becomes much harder to write these rules without a well-defined area where git repos are located.

![image](https://user-images.githubusercontent.com/6200749/73728916-741ab400-4734-11ea-8d1c-c701db9b22ec.png)
![image](https://user-images.githubusercontent.com/6200749/73728939-7ed54900-4734-11ea-8eeb-daa298c1261b.png)

**Comment by alehaa** [comment]
One could adjust the server configuration to blacklist just `/config.ini`, but not `config.ini` in any path.
