### ISSUE TITLE
Development branches e.g. 1.x / 2.x

### ISSUE THREAD

**Issue by MacHoel** [klaussilveira/gitlist#865]
Hi,

I started filing a few pull  requests, and then read issue #849 from @camilstaps.

I would find it great that this initial repository remains the central point for developers who still want to bring in evolutions, including major ones.

Could we discuss the option to create development branches for such pull requests ?

This way, most wanted features could be integrated, deployed and tested efficiently by active users, without impacting master, until decided by maintainers (e.g. based on issues status on dev branch).

Cheers,
Hoel

**Comment by alehaa** [comment]
I don't think this is useful, as there is no active development on new major features for GitList at the moment. Fixes will be merged directly into `master`.
