### ISSUE TITLE
Readme.md images not working?

### ISSUE THREAD

**Issue by Zaptopod4001** [klaussilveira/gitlist#866]
I downloaded the 1.0.2 version and tried to install it on a server. GitList seems to be working, I can browse the files and syntax highlighting is working, but readme.md file's images are broken, although the same repository and markdown file works just fine in GitHub. 

I did find some issue already here, but the solution given there only makes images work when root link (or whatever it is called in that bar with zip DL link) is clicked, only then I can see images, but it is not a working solution, if someone else doesn't know this...

Is this still in development or should I look into some other software, as I was interested about GitList mostly to use it as private GitHub alternative, and big part of it is being able to see readme.md files with images.

I also tried the development build, but I couldn't even get it working properly, no style for page and the repo pages didn't work.

**Comment by alehaa** [comment]
#659 is related.

At the moment, there is no active development on this feature.
