### ISSUE TITLE
kent/src/hg/utils/hubCheck/makefile

### ISSUE THREAD

**Issue by jerviedog** [klaussilveira/gitlist#867]
I think the included mk file in the makefile is wrong, because there is no "install" target in the common.mk. The correct mk file to be included is userApp.mk. 

The modified top part of the makefile is:

```shell
kentSrc = ../../..
# include ../../../inc/common.mk # comment-out

L += ${HALLIBS} ${MYSQLLIBS} -lm
MYLIBDIR = ../../../lib/${MACHTYPE}
MYLIBS =  ${MYLIBDIR}/jkhgap.a ${MYLIBDIR}/jkweb.a

A = hubCheck
O = hubCheck.o

include ${kentSrc}/inc/userApp.mk # added
```

**Comment by alehaa** [comment]
I'm sorry, but this doesn't look like GitList code?

**Comment by jerviedog** [comment]
Hi, maybe I don't follow the community rule. I think I should not open an issue. 

I just wanted to point out that the if I modified the makefile as I did, the "make" process went on successfully.

Now I am going to close the issue:)
