### ISSUE TITLE
Uncaught Error: Class 'GitList\Config' not found

### ISSUE THREAD

**Issue by MomentQYC** [klaussilveira/gitlist#869]
Fatal error: Uncaught Error: Class 'GitList\Config' not found in (dir)/index.php:22 Stack trace: #0 {main} thrown in (dir)/index.php on line 22

**Comment by alehaa** [comment]
Seems like you didn't run composer. You can download a prebuilt version including all dependencies from [the releases page](https://github.com/klaussilveira/gitlist/releases).

**Comment by MomentQYC** [comment]
It's&nbsp;the&nbsp;prebuild&nbsp;version.




Forever☆七夜草°
yateam@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Alexander Haase"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月6日(星期一) 凌晨5:18
收件人:&nbsp;"klaussilveira/gitlist"<gitlist@noreply.github.com&gt;;
抄送:&nbsp;"Forever☆七夜草°"<yateam@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [klaussilveira/gitlist] Uncaught Error: Class 'GitList\Config' not found (#869)





 
Seems like you didn't run composer. You can download a prebuilt version including all dependencies from the releases page.

**Comment by alehaa** [comment]
Can you provide the web server configuration? Apparently the autoloader paths aren't configured correctly.

**Comment by MomentQYC** [comment]
CentOS7.8+PHP7.3+Nginx1.18+MySQL5.7
