### ISSUE TITLE
Git Clone is missing space

### ISSUE THREAD

**Issue by tuxthepenguin84** [klaussilveira/gitlist#872]
![image](https://user-images.githubusercontent.com/12042822/94371469-a609cd80-00ab-11eb-9e7d-52fd398d83e3.png)

I tried to edit tree.twig but that seems to not make a difference at all.

Here's my config.ini section
```
[clone_button]
; ssh remote
show_ssh_remote = true ; display remote URL for SSH
ssh_host = 'git' ; host to use for cloning via HTTP (default: none => uses gitlist web host)
ssh_url_subdir = '/var/www/git/' ; if cloning via SSH is triggered using special dir (e.g. ssh://example.com/git/repo.git)
                ; has to end with trailing slash
ssh_port = '' ; port to use for cloning via SSH (default: 22 => standard ssh port)
ssh_user = 'git' ; user to use for cloning via SSH
ssh_user_dynamic = false ; when enabled, ssh_user is set to $_SERVER['PHP_AUTH_USER']

; http remote
show_http_remote = false ; display remote URL for HTTP
http_host = '' ; host to use for cloning via HTTP (default: none => uses gitlist web host)
use_https = false ; generate URL with https://
http_url_subdir = '' ; if cloning via HTTP is triggered using virtual dir (e.g. https://example.com/git/repo.git)
                    ; has to end with trailing slash
http_user = '' ; user to use for cloning via HTTP (default: none)
http_user_dynamic = false ; when enabled, http_user is set to $_SERVER['PHP_AUTH_USER']
```

**Comment by Rob4226** [comment]
I have same problem...no space after the `git clone`.

**Comment by mlcpap** [comment]
I had the same problem.  I changed line 33 of themes/default/twig/tree.twig and line 35 of themes/bootstrap3/twig/tree.twig to read as follows.  Basically, adding ": ' '" after "ssh://'":

`                    <input type="text" class="form-control{{ show_ssh_remote ? ' visible' }}" id="clone-input-ssh" value="git clone {{ ssh_port ? **'ssh://': ' '** }}{{ ssh_user | url_encode }}{{ ssh_user ? '@' }}{{ ssh_host ? ssh_host : app.request.host }}:{{ ssh_port ? ssh_port ~ '/' : '' }}{{ ssh_url_subdir }}{{ repo }}">`
