### ISSUE TITLE
GitList don't work on php7.4 and php8

### ISSUE THREAD

**Issue by Acksop** [klaussilveira/gitlist#875]
I've test with multiples docker image.
When I run php 7.4, and php8, Twig as a fatal error.
Maybe Gitlist need to update Twig in composer.json

Are you ok ?
Great Job, It work fine on php7.3 !

**Comment by Webbeh** [comment]
If you need details, here's the error :
```
PHP Fatal Error:
Unparenthesized `a ? b : c = d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /usr/share/webapps/gitlist/vendor/twig/twig/lib/Twig/Node.php on line 42.
```

**Comment by lbayle** [comment]
In deed, I have the same pb

**Comment by demib72** [comment]
Aye, that has popped up once I got the folder permissions right (PHP 8.0.3).

**Comment by MacHoel** [comment]
Hi, this should be fixed in #880 . Looking forward to your feedback

**Comment by MacHoel** [comment]
Hi, for those interested, @fox34 mentioned #880 fixes the issue with PHP8

**Comment by klaussilveira** [comment]
It should now: https://github.com/klaussilveira/gitlist/releases/tag/1.1.0
