### ISSUE TITLE
Installation/Configuration issue

### ISSUE THREAD

**Issue by fasherman** [klaussilveira/gitlist#881]
Initial page loads fine and shows the different repositories. Selecting any one of them or the refresh option produces a 404 The requested URL was not found on this server. 
Webserver is apache.

Please let me know what diagnostic data you require to assist and thank you in advance.

**Comment by fasherman** [comment]
Self-resolved.

**Comment by ted423** [comment]
which cause this , it seems I had same issue too

**Comment by ted423** [comment]
that seems not work for me
