### ISSUE TITLE
Archive generated without zip or tar extension

### ISSUE THREAD

**Issue by Fred-Zweig** [klaussilveira/gitlist#882]
I have a small problem: when I download a repository by clicking on the `ZIP` or `TAR` button (on the upper bar), it works fine, in the sense that the archive generated for download has the `zip` or `tar` extension. In this way, a user that finds the downloaded archive on his Desktop knows that it is a zip or tar archive and he can easily extract it. The problem arises when a user tries to right click on the `ZIP` or `TAR` button, then select `Copy Link` to copy the download link to his clipboard, and then goes to a terminal and tries to download the archive on a remote server, or on the local machine with the command:
```
wget https://git.mydomain.com/projectname/zipball/master
```
or
```
wget https://git.mydomain.com/projectname/tarball/master
```
Ths command is very often used, especially to download archives on remote servers to which the user is connected via SSH, since in this way he can get software on the remote server without using FTP.  So, the problem is that when using one of the above commands, the archive is downloaded fine, but the archive name is not `master.zip` or `master.tar`, as it should, but simply `master`. Because of this, the user doesn't know what kind of archive it is and how to extract it in command line.

**Please, tell me what file do I have to modify in order to obtain a downloaded file with the `zip` or `tar` termination, when using the right-click method of download**!

**Comment by alehaa** [comment]
This is not possible, as GitList uses the `Content-Disposition` HTTP header [to define the filename](https://github.com/klaussilveira/gitlist/blob/master/src/Controller/TreeController.php#L105) of the download file, while `wget` determines the filename from the URL. However, you can tell `wget` to honor this header by using [this option](https://unix.stackexchange.com/a/453471).
