### ISSUE TITLE
Oops! Unexpected "endfor" tag (expecting closing tag for the "block" tag defined near line 8).

### ISSUE THREAD

**Issue by apoyrazo** [klaussilveira/gitlist#884]
Hello everyone,

Did someone have this issue already:

Oops! Unexpected "endfor" tag (expecting closing tag for the "block" tag defined near line 8).

If so, could you please help me to fix it?

Kind regards,

Ata

**Comment by apoyrazo** [comment]
For information, this happens when I want to display a specific commit

**Comment by alehaa** [comment]
Sounds like something in your commit is breaking the Twig template. Is there any Twig-specific keyword in this commit?

**Comment by apoyrazo** [comment]
I have checked it and in facts it is in all commit, example of URL:

https://<server_name>/gitlist/<git_repo>/commit/<commitnumber>

Do you also get this issue? To reach it, when I go to a specific repos, I click on "Commits" on the right of "Files", then I choose any commit by clicking "view <commit>", then I get the issue

**Comment by apoyrazo** [comment]
Hi,

This issue is fixed it was an issue in one of the twig file in the template, it was indeed a human mistake in the code :)

Thanks for the tips,

Kind regards,

Ata
