### ISSUE TITLE
wrong timezone

### ISSUE THREAD

**Issue by dmolony** [klaussilveira/gitlist#885]
I cannot get the gitlist display to show the correct commit time. I have checked php.ini, the gitlist config and the git timezone setting. They all look correct to me, but something, somewhere is wrong.

Could you suggest some debugging commands to at least narrow down where the problem lies?

**Comment by alehaa** [comment]
You can place an extra file named `test.php` in the folder of GitList with the content `<?php phpinfo();` to see the current PHP configuration. As for GitList, I would suggest to check the spelling in the ini variable. For debugging you can `echo` the timezone configured in the index.php.
https://github.com/klaussilveira/gitlist/blob/271e6c5518080f2da59983da0385d88c9f3c0d1c/index.php#L25
