### ISSUE TITLE
How to not save the comment in a cookie ?

### ISSUE THREAD

**Issue by Aditya20kul** [klaussilveira/gitlist#889]
I can see that a commit comment is saved in a cookie and also the other things like when uploading a file when I try to re-upload, it shows me the name of the file that was previously uploaded?
Can we avoid this behavior, can we not save anything in the cookie, if yes, where can we do it?

**Comment by alehaa** [comment]
I'm confused. GitList is a viewer only and no upload is provided. Can you describe the issue more specific?
