### ISSUE TITLE
Instructions on how to deploy

### ISSUE THREAD

**Issue by andrewhamili** [klaussilveira/gitlist#895]
![image](https://user-images.githubusercontent.com/20767537/149609334-9bde999a-85ca-4ff4-8d7d-d3d67763afab.png)

Hi, I have downloaded the 2.0.0 zip but I got this file structure which is different from 1.0.1.

How will I deploy this on Apache2.4?

**Comment by klaussilveira** [comment]
This should be able to help you: https://symfony.com/doc/current/deployment.html#symfony-deployment-basics

`2.0` just came out and there is not enough documentation yet. I've created a ticket for that: https://github.com/klaussilveira/gitlist/issues/893
