### ISSUE TITLE
Hello, I use Gitlist 1.1.1 and I want to know if I respect the BSD-2-Clause

### ISSUE THREAD

**Issue by Acksop** [klaussilveira/gitlist#918]
Hello, for one of my project, I push some ref on gitlist about the 1.1.1 version, by inadvertance...
I've repair it this night.
And I want to know if I respect your BSD-2-Clause

Thanks in advance.

PS: If my work can make you a new gitlist evolved, I sould be happy.

[SAND-framework](https://github.com/Acksop/SAND-framework)

**Comment by klaussilveira** [comment]
You're all good. :+1:

**Comment by Acksop** [comment]
thanks
