### ISSUE TITLE
Can't create development environment 

### ISSUE THREAD

**Issue by wykasz** [klaussilveira/gitlist#922]
First, instruction does not provide with details about what is neccesary to run development enoviroment
 - os
 -  docker version
 -  git
 - etc

I've tried to install it on a fresh and clean debian 11 instalation.

Couldn't becouse, there is no git and make on default.
Then, docker. I've instaled docker using instruction provided on docker site: https://docs.docker.com/engine/install/debian/
Tured out, that docker-compose was missing.
I've installed it, then:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'node'
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'php-fpm'
make: *** [Makefile:27: setup] Error 1
root@git-20221118-dev:~/gitlist# docker-compose -v
docker-compose version 1.25.0, build unknown

```
So. What version of docker-compose do i need?

Regards,

**Comment by klaussilveira** [comment]
You would need docker-compose 2.x.
