### ISSUE TITLE
Can't list repositories

### ISSUE THREAD

**Issue by wykasz** [klaussilveira/gitlist#923]
Repository created with git version 2.30.2 under /var/www/gitr/projecta/repoa with www-data owner.
gitlist 2.0.0 installed on debian 11 with php 8.1 (fpm) and nginx pointing to /var/www/git/public 

Config
```
 # List of directories containing repositories
  default_repository_dir: /var/www/gitr/projectc/repoa
  repositories:
    - '%env(default:default_repository_dir:DEFAULT_REPOSITORY_DIR)%'

```

Result:
![image](https://user-images.githubusercontent.com/11601490/202747016-a9a10ceb-5399-4c96-98e2-b3fdc0b8c7a5.png)

Changing  `repository_depth:` '0'` to 1 or changing path doesn't help.

**Comment by klaussilveira** [comment]
You have mentioned `/var/www/gitr/projecta/repoa`, but your config lists `/var/www/gitr/projectc/repoa`. Regardless of that, you should be listing folders that contain repository folders. So I'm assuming:

    /var/www/gitr/projecta
    /var/www/gitr/projectc

Just use that as values for your `repositories` value.

**Comment by nataliesweep** [comment]
+1

**Comment by iamnatalie** [comment]
This Nginx works: 
**install php, php-fpm, nginx. ubuntu 22
```
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/gitlist/public;
	index index.php index.html index.htm index.nginx-debian.html;
	location / {
		try_files $uri /index.php$is_args$args;
	}
	location ~ \.php$ {
		include snippets/fastcgi-php.conf;

		fastcgi_pass unix:/run/php/php8.1-fpm.sock;
	}
}

```
