### ISSUE TITLE
public/.htaccess is missing

### ISSUE THREAD

**Issue by indeed-a-genius** [klaussilveira/gitlist#926]
no way to view repos without it

**Comment by supyrow** [comment]
`.htaccess`
```
<IfModule mod_rewrite.c>
    Options -MultiViews +FollowSymLinks
    RewriteEngine On
    #RewriteBase /
		RewriteCond %{REQUEST_FILENAME} !-f
		RewriteCond $0#%{REQUEST_URI} ([^#]*)#(.*)\1$
		RewriteRule ^.*$ %2index.php [QSA,L]
                SetEnv default_repository_dir ../../repositories
</ifmodule>
```

apache2 config>>
`gitlist.conf`

```
Alias /gitlist /var/www/YOURS/public
Alias /assets /var/www/YOURS/public/assets
<Directory /var/www/YOURS/public>
  Options FollowSymLinks
  AllowOverride All
</Directory>
	#LogLevel info ssl:warn
	ErrorLog ${APACHE_LOG_DIR}/error_gitlist.log
	CustomLog ${APACHE_LOG_DIR}/access_gitlist.log combined
```
see a working demonstration>
https://git.supyrow.com

**Comment by klaussilveira** [comment]
`.htaccess` is specific to Apache and should not belong in the gitlist package. Maybe in the docs?

**Comment by qistoph** [comment]
The information in this issue regarding Apache was very very useful. I did not find this in the docs.

My suggestion would be to reopen this issue to track inclusion of these instructions in the docs.

**Comment by supyrow** [comment]
yeah..  it's discouraging, to post improvements or fixes, cause they just get shot down.   it's not just here, its everywhere.  ..maybe we should add age verification to it as well.   fuck it.   no reason to share or improve code anymore, cause it just gets shut down once it takes off.

**Comment by klaussilveira** [comment]
What are you talking about? Just send a PR.

**Comment by qistoph** [comment]
I can't send a PR for the wiki, but here is an instruction for it:

* Download gitlist stable version from [releases](https://github.com/klaussilveira/gitlist/releases)
* Extract the contents of the zip in `/var/www/gitlist`
* Add a new configuration file `/etc/apache2/conf-available/gitlist.conf`:

```apache
Alias /gitlist/ /var/www/gitlist/public/
Alias /assets/ /var/www/gitlist/public/assets/
<Directory /var/www/gitlist/public/>
    SSLRequireSSL

    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride All

    RewriteEngine On
    #RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond $0#%{REQUEST_URI} ([^#]*)#(.*)\1$
    RewriteRule ^.*$ %2index.php [QSA,L]
</Directory>
```

* Copy `config.ini-example` to `config.ini` and change the repositories and hidden properties to your likes:
```ini
[git]
client = '/usr/bin/git' ; Your git executable path
default_branch = 'master' ; Default branch when HEAD is detached
repositories[] = '/var/www/html/' ;Path to your repositories
hidden[] = '/var/www/html/opcache-gui';You can hide repositories from GitList
```
* Restart apache: `apache2ctl restart`

**Comment by klaussilveira** [comment]
Thanks! Feel free to send a PR updating the README. Having the README as documentation is way more portable than GitHub Wiki, specially in the event of migration to Codeberg or other providers.
